pub use crate::prelude::*;

/// Two-letter code of the US state (or `DC`) to form the company in. We recommend `WY` because Wyoming formations are completed the same day.
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum FormCompanyAccountsRequestFormationState {
    Al,
    Ak,
    Az,
    Ar,
    Ca,
    Co,
    Ct,
    De,
    Dc,
    Fl,
    Ga,
    Hi,
    Id,
    Il,
    In,
    Ia,
    Ks,
    Ky,
    La,
    Me,
    Md,
    Ma,
    Mi,
    Mn,
    Ms,
    Mo,
    Mt,
    Ne,
    Nv,
    Nh,
    Nj,
    Nm,
    Ny,
    Nc,
    Nd,
    Oh,
    Ok,
    Or,
    Pa,
    Ri,
    Sc,
    Sd,
    Tn,
    Tx,
    Ut,
    Vt,
    Va,
    Wa,
    Wv,
    Wi,
    Wy,
    /// This variant is used for forward compatibility.
    /// If the server sends a value not recognized by the current SDK version,
    /// it will be captured here with the raw string value.
    __Unknown(String),
}
impl Serialize for FormCompanyAccountsRequestFormationState {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        match self {
            Self::Al => serializer.serialize_str("AL"),
            Self::Ak => serializer.serialize_str("AK"),
            Self::Az => serializer.serialize_str("AZ"),
            Self::Ar => serializer.serialize_str("AR"),
            Self::Ca => serializer.serialize_str("CA"),
            Self::Co => serializer.serialize_str("CO"),
            Self::Ct => serializer.serialize_str("CT"),
            Self::De => serializer.serialize_str("DE"),
            Self::Dc => serializer.serialize_str("DC"),
            Self::Fl => serializer.serialize_str("FL"),
            Self::Ga => serializer.serialize_str("GA"),
            Self::Hi => serializer.serialize_str("HI"),
            Self::Id => serializer.serialize_str("ID"),
            Self::Il => serializer.serialize_str("IL"),
            Self::In => serializer.serialize_str("IN"),
            Self::Ia => serializer.serialize_str("IA"),
            Self::Ks => serializer.serialize_str("KS"),
            Self::Ky => serializer.serialize_str("KY"),
            Self::La => serializer.serialize_str("LA"),
            Self::Me => serializer.serialize_str("ME"),
            Self::Md => serializer.serialize_str("MD"),
            Self::Ma => serializer.serialize_str("MA"),
            Self::Mi => serializer.serialize_str("MI"),
            Self::Mn => serializer.serialize_str("MN"),
            Self::Ms => serializer.serialize_str("MS"),
            Self::Mo => serializer.serialize_str("MO"),
            Self::Mt => serializer.serialize_str("MT"),
            Self::Ne => serializer.serialize_str("NE"),
            Self::Nv => serializer.serialize_str("NV"),
            Self::Nh => serializer.serialize_str("NH"),
            Self::Nj => serializer.serialize_str("NJ"),
            Self::Nm => serializer.serialize_str("NM"),
            Self::Ny => serializer.serialize_str("NY"),
            Self::Nc => serializer.serialize_str("NC"),
            Self::Nd => serializer.serialize_str("ND"),
            Self::Oh => serializer.serialize_str("OH"),
            Self::Ok => serializer.serialize_str("OK"),
            Self::Or => serializer.serialize_str("OR"),
            Self::Pa => serializer.serialize_str("PA"),
            Self::Ri => serializer.serialize_str("RI"),
            Self::Sc => serializer.serialize_str("SC"),
            Self::Sd => serializer.serialize_str("SD"),
            Self::Tn => serializer.serialize_str("TN"),
            Self::Tx => serializer.serialize_str("TX"),
            Self::Ut => serializer.serialize_str("UT"),
            Self::Vt => serializer.serialize_str("VT"),
            Self::Va => serializer.serialize_str("VA"),
            Self::Wa => serializer.serialize_str("WA"),
            Self::Wv => serializer.serialize_str("WV"),
            Self::Wi => serializer.serialize_str("WI"),
            Self::Wy => serializer.serialize_str("WY"),
            Self::__Unknown(val) => serializer.serialize_str(val),
        }
    }
}

impl<'de> Deserialize<'de> for FormCompanyAccountsRequestFormationState {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        match value.as_str() {
            "AL" => Ok(Self::Al),
            "AK" => Ok(Self::Ak),
            "AZ" => Ok(Self::Az),
            "AR" => Ok(Self::Ar),
            "CA" => Ok(Self::Ca),
            "CO" => Ok(Self::Co),
            "CT" => Ok(Self::Ct),
            "DE" => Ok(Self::De),
            "DC" => Ok(Self::Dc),
            "FL" => Ok(Self::Fl),
            "GA" => Ok(Self::Ga),
            "HI" => Ok(Self::Hi),
            "ID" => Ok(Self::Id),
            "IL" => Ok(Self::Il),
            "IN" => Ok(Self::In),
            "IA" => Ok(Self::Ia),
            "KS" => Ok(Self::Ks),
            "KY" => Ok(Self::Ky),
            "LA" => Ok(Self::La),
            "ME" => Ok(Self::Me),
            "MD" => Ok(Self::Md),
            "MA" => Ok(Self::Ma),
            "MI" => Ok(Self::Mi),
            "MN" => Ok(Self::Mn),
            "MS" => Ok(Self::Ms),
            "MO" => Ok(Self::Mo),
            "MT" => Ok(Self::Mt),
            "NE" => Ok(Self::Ne),
            "NV" => Ok(Self::Nv),
            "NH" => Ok(Self::Nh),
            "NJ" => Ok(Self::Nj),
            "NM" => Ok(Self::Nm),
            "NY" => Ok(Self::Ny),
            "NC" => Ok(Self::Nc),
            "ND" => Ok(Self::Nd),
            "OH" => Ok(Self::Oh),
            "OK" => Ok(Self::Ok),
            "OR" => Ok(Self::Or),
            "PA" => Ok(Self::Pa),
            "RI" => Ok(Self::Ri),
            "SC" => Ok(Self::Sc),
            "SD" => Ok(Self::Sd),
            "TN" => Ok(Self::Tn),
            "TX" => Ok(Self::Tx),
            "UT" => Ok(Self::Ut),
            "VT" => Ok(Self::Vt),
            "VA" => Ok(Self::Va),
            "WA" => Ok(Self::Wa),
            "WV" => Ok(Self::Wv),
            "WI" => Ok(Self::Wi),
            "WY" => Ok(Self::Wy),
            _ => Ok(Self::__Unknown(value)),
        }
    }
}

impl fmt::Display for FormCompanyAccountsRequestFormationState {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Al => write!(f, "AL"),
            Self::Ak => write!(f, "AK"),
            Self::Az => write!(f, "AZ"),
            Self::Ar => write!(f, "AR"),
            Self::Ca => write!(f, "CA"),
            Self::Co => write!(f, "CO"),
            Self::Ct => write!(f, "CT"),
            Self::De => write!(f, "DE"),
            Self::Dc => write!(f, "DC"),
            Self::Fl => write!(f, "FL"),
            Self::Ga => write!(f, "GA"),
            Self::Hi => write!(f, "HI"),
            Self::Id => write!(f, "ID"),
            Self::Il => write!(f, "IL"),
            Self::In => write!(f, "IN"),
            Self::Ia => write!(f, "IA"),
            Self::Ks => write!(f, "KS"),
            Self::Ky => write!(f, "KY"),
            Self::La => write!(f, "LA"),
            Self::Me => write!(f, "ME"),
            Self::Md => write!(f, "MD"),
            Self::Ma => write!(f, "MA"),
            Self::Mi => write!(f, "MI"),
            Self::Mn => write!(f, "MN"),
            Self::Ms => write!(f, "MS"),
            Self::Mo => write!(f, "MO"),
            Self::Mt => write!(f, "MT"),
            Self::Ne => write!(f, "NE"),
            Self::Nv => write!(f, "NV"),
            Self::Nh => write!(f, "NH"),
            Self::Nj => write!(f, "NJ"),
            Self::Nm => write!(f, "NM"),
            Self::Ny => write!(f, "NY"),
            Self::Nc => write!(f, "NC"),
            Self::Nd => write!(f, "ND"),
            Self::Oh => write!(f, "OH"),
            Self::Ok => write!(f, "OK"),
            Self::Or => write!(f, "OR"),
            Self::Pa => write!(f, "PA"),
            Self::Ri => write!(f, "RI"),
            Self::Sc => write!(f, "SC"),
            Self::Sd => write!(f, "SD"),
            Self::Tn => write!(f, "TN"),
            Self::Tx => write!(f, "TX"),
            Self::Ut => write!(f, "UT"),
            Self::Vt => write!(f, "VT"),
            Self::Va => write!(f, "VA"),
            Self::Wa => write!(f, "WA"),
            Self::Wv => write!(f, "WV"),
            Self::Wi => write!(f, "WI"),
            Self::Wy => write!(f, "WY"),
            Self::__Unknown(val) => write!(f, "{}", val),
        }
    }
}
