pub use crate::prelude::*;

/// An affiliate tracks a user's referral performance and commission earnings for a company, including retention rates, revenue metrics, and payout configurations.
#[derive(Debug, Clone, Serialize, Deserialize, Default, PartialEq, Eq, Hash)]
pub struct AffiliateListItem {
    /// The total active members of the affiliate
    #[serde(default)]
    pub active_members_count: i64,
    /// The company attached to this affiliate
    #[serde(default)]
    pub company: AffiliateListItemCompany,
    /// The datetime the affiliate was created.
    #[serde(default)]
    #[serde(with = "crate::core::flexible_datetime::offset")]
    pub created_at: DateTime<FixedOffset>,
    /// The percentage of referred customers who are still active members
    #[serde(default)]
    pub customer_retention_rate: String,
    /// The percentage of referred customers who remained active over the last 90 days
    #[serde(default)]
    pub customer_retention_rate_ninety_days: String,
    /// The unique identifier for the affiliate.
    #[serde(default)]
    pub id: String,
    /// The monthly recurring revenue generated by this affiliate's referrals, formatted as a USD currency string
    #[serde(default)]
    pub monthly_recurring_revenue_usd: String,
    /// The status of the affiliate
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    /// The total count of all overrides for this affiliate
    #[serde(default)]
    pub total_overrides_count: i64,
    /// The total commission earnings paid to this affiliate, formatted as a USD currency string
    #[serde(default)]
    pub total_referral_earnings_usd: String,
    /// The total referrals of the affiliate
    #[serde(default)]
    pub total_referrals_count: i64,
    /// The total revenue generated from this affiliate's referrals, formatted as a USD currency string
    #[serde(default)]
    pub total_revenue_usd: String,
    /// The datetime the affiliate was last updated.
    #[serde(default)]
    #[serde(with = "crate::core::flexible_datetime::offset")]
    pub updated_at: DateTime<FixedOffset>,
    /// The user attached to this affiliate
    #[serde(default)]
    pub user: AffiliateListItemUser,
}

impl AffiliateListItem {
    pub fn builder() -> AffiliateListItemBuilder {
        <AffiliateListItemBuilder as Default>::default()
    }
}

#[derive(Clone, PartialEq, Default, Debug)]
#[non_exhaustive]
pub struct AffiliateListItemBuilder {
    active_members_count: Option<i64>,
    company: Option<AffiliateListItemCompany>,
    created_at: Option<DateTime<FixedOffset>>,
    customer_retention_rate: Option<String>,
    customer_retention_rate_ninety_days: Option<String>,
    id: Option<String>,
    monthly_recurring_revenue_usd: Option<String>,
    status: Option<Status>,
    total_overrides_count: Option<i64>,
    total_referral_earnings_usd: Option<String>,
    total_referrals_count: Option<i64>,
    total_revenue_usd: Option<String>,
    updated_at: Option<DateTime<FixedOffset>>,
    user: Option<AffiliateListItemUser>,
}

impl AffiliateListItemBuilder {
    pub fn active_members_count(mut self, value: i64) -> Self {
        self.active_members_count = Some(value);
        self
    }

    pub fn company(mut self, value: AffiliateListItemCompany) -> Self {
        self.company = Some(value);
        self
    }

    pub fn created_at(mut self, value: DateTime<FixedOffset>) -> Self {
        self.created_at = Some(value);
        self
    }

    pub fn customer_retention_rate(mut self, value: impl Into<String>) -> Self {
        self.customer_retention_rate = Some(value.into());
        self
    }

    pub fn customer_retention_rate_ninety_days(mut self, value: impl Into<String>) -> Self {
        self.customer_retention_rate_ninety_days = Some(value.into());
        self
    }

    pub fn id(mut self, value: impl Into<String>) -> Self {
        self.id = Some(value.into());
        self
    }

    pub fn monthly_recurring_revenue_usd(mut self, value: impl Into<String>) -> Self {
        self.monthly_recurring_revenue_usd = Some(value.into());
        self
    }

    pub fn status(mut self, value: Status) -> Self {
        self.status = Some(value);
        self
    }

    pub fn total_overrides_count(mut self, value: i64) -> Self {
        self.total_overrides_count = Some(value);
        self
    }

    pub fn total_referral_earnings_usd(mut self, value: impl Into<String>) -> Self {
        self.total_referral_earnings_usd = Some(value.into());
        self
    }

    pub fn total_referrals_count(mut self, value: i64) -> Self {
        self.total_referrals_count = Some(value);
        self
    }

    pub fn total_revenue_usd(mut self, value: impl Into<String>) -> Self {
        self.total_revenue_usd = Some(value.into());
        self
    }

    pub fn updated_at(mut self, value: DateTime<FixedOffset>) -> Self {
        self.updated_at = Some(value);
        self
    }

    pub fn user(mut self, value: AffiliateListItemUser) -> Self {
        self.user = Some(value);
        self
    }

    /// Consumes the builder and constructs a [`AffiliateListItem`].
    /// This method will fail if any of the following fields are not set:
    /// - [`active_members_count`](AffiliateListItemBuilder::active_members_count)
    /// - [`company`](AffiliateListItemBuilder::company)
    /// - [`created_at`](AffiliateListItemBuilder::created_at)
    /// - [`customer_retention_rate`](AffiliateListItemBuilder::customer_retention_rate)
    /// - [`customer_retention_rate_ninety_days`](AffiliateListItemBuilder::customer_retention_rate_ninety_days)
    /// - [`id`](AffiliateListItemBuilder::id)
    /// - [`monthly_recurring_revenue_usd`](AffiliateListItemBuilder::monthly_recurring_revenue_usd)
    /// - [`total_overrides_count`](AffiliateListItemBuilder::total_overrides_count)
    /// - [`total_referral_earnings_usd`](AffiliateListItemBuilder::total_referral_earnings_usd)
    /// - [`total_referrals_count`](AffiliateListItemBuilder::total_referrals_count)
    /// - [`total_revenue_usd`](AffiliateListItemBuilder::total_revenue_usd)
    /// - [`updated_at`](AffiliateListItemBuilder::updated_at)
    /// - [`user`](AffiliateListItemBuilder::user)
    pub fn build(self) -> Result<AffiliateListItem, BuildError> {
        Ok(AffiliateListItem {
            active_members_count: self
                .active_members_count
                .ok_or_else(|| BuildError::missing_field("active_members_count"))?,
            company: self
                .company
                .ok_or_else(|| BuildError::missing_field("company"))?,
            created_at: self
                .created_at
                .ok_or_else(|| BuildError::missing_field("created_at"))?,
            customer_retention_rate: self
                .customer_retention_rate
                .ok_or_else(|| BuildError::missing_field("customer_retention_rate"))?,
            customer_retention_rate_ninety_days: self
                .customer_retention_rate_ninety_days
                .ok_or_else(|| BuildError::missing_field("customer_retention_rate_ninety_days"))?,
            id: self.id.ok_or_else(|| BuildError::missing_field("id"))?,
            monthly_recurring_revenue_usd: self
                .monthly_recurring_revenue_usd
                .ok_or_else(|| BuildError::missing_field("monthly_recurring_revenue_usd"))?,
            status: self.status,
            total_overrides_count: self
                .total_overrides_count
                .ok_or_else(|| BuildError::missing_field("total_overrides_count"))?,
            total_referral_earnings_usd: self
                .total_referral_earnings_usd
                .ok_or_else(|| BuildError::missing_field("total_referral_earnings_usd"))?,
            total_referrals_count: self
                .total_referrals_count
                .ok_or_else(|| BuildError::missing_field("total_referrals_count"))?,
            total_revenue_usd: self
                .total_revenue_usd
                .ok_or_else(|| BuildError::missing_field("total_revenue_usd"))?,
            updated_at: self
                .updated_at
                .ok_or_else(|| BuildError::missing_field("updated_at"))?,
            user: self.user.ok_or_else(|| BuildError::missing_field("user"))?,
        })
    }
}
