pub use crate::prelude::*;

/// A versioned build artifact for a Whop React Native App, submitted for review and deployment to a specific platform.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash)]
pub struct AppBuildListItem {
    /// A SHA-256 hash of the uploaded build file, generated by the client and used to verify file integrity.
    #[serde(default)]
    pub checksum: String,
    /// The datetime the app build was created.
    #[serde(default)]
    #[serde(with = "crate::core::flexible_datetime::offset")]
    pub created_at: DateTime<FixedOffset>,
    /// A URL to download the app build as a .zip archive.
    #[serde(default)]
    pub file_url: String,
    /// The unique identifier for the app build.
    #[serde(default)]
    pub id: String,
    /// Whether this build is the currently active production build for its platform.
    #[serde(default)]
    pub is_production: bool,
    /// The target platform for this build.
    pub platform: AppBuildPlatforms,
    /// Feedback from the reviewer explaining why the build was rejected. Null if the build has not been reviewed or was approved.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub review_message: Option<String>,
    /// A URL to download the compressed source code archive that produced this build. Null if the build was uploaded without a source archive.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source_url: Option<String>,
    /// The current review status of this build.
    pub status: AppBuildStatuses,
    /// The list of view types this build supports, as declared by the developer.
    #[serde(default)]
    pub supported_app_view_types: Vec<AppViewTypes>,
}

impl AppBuildListItem {
    pub fn builder() -> AppBuildListItemBuilder {
        <AppBuildListItemBuilder as Default>::default()
    }
}

#[derive(Clone, PartialEq, Default, Debug)]
#[non_exhaustive]
pub struct AppBuildListItemBuilder {
    checksum: Option<String>,
    created_at: Option<DateTime<FixedOffset>>,
    file_url: Option<String>,
    id: Option<String>,
    is_production: Option<bool>,
    platform: Option<AppBuildPlatforms>,
    review_message: Option<String>,
    source_url: Option<String>,
    status: Option<AppBuildStatuses>,
    supported_app_view_types: Option<Vec<AppViewTypes>>,
}

impl AppBuildListItemBuilder {
    pub fn checksum(mut self, value: impl Into<String>) -> Self {
        self.checksum = Some(value.into());
        self
    }

    pub fn created_at(mut self, value: DateTime<FixedOffset>) -> Self {
        self.created_at = Some(value);
        self
    }

    pub fn file_url(mut self, value: impl Into<String>) -> Self {
        self.file_url = Some(value.into());
        self
    }

    pub fn id(mut self, value: impl Into<String>) -> Self {
        self.id = Some(value.into());
        self
    }

    pub fn is_production(mut self, value: bool) -> Self {
        self.is_production = Some(value);
        self
    }

    pub fn platform(mut self, value: AppBuildPlatforms) -> Self {
        self.platform = Some(value);
        self
    }

    pub fn review_message(mut self, value: impl Into<String>) -> Self {
        self.review_message = Some(value.into());
        self
    }

    pub fn source_url(mut self, value: impl Into<String>) -> Self {
        self.source_url = Some(value.into());
        self
    }

    pub fn status(mut self, value: AppBuildStatuses) -> Self {
        self.status = Some(value);
        self
    }

    pub fn supported_app_view_types(mut self, value: Vec<AppViewTypes>) -> Self {
        self.supported_app_view_types = Some(value);
        self
    }

    /// Consumes the builder and constructs a [`AppBuildListItem`].
    /// This method will fail if any of the following fields are not set:
    /// - [`checksum`](AppBuildListItemBuilder::checksum)
    /// - [`created_at`](AppBuildListItemBuilder::created_at)
    /// - [`file_url`](AppBuildListItemBuilder::file_url)
    /// - [`id`](AppBuildListItemBuilder::id)
    /// - [`is_production`](AppBuildListItemBuilder::is_production)
    /// - [`platform`](AppBuildListItemBuilder::platform)
    /// - [`status`](AppBuildListItemBuilder::status)
    /// - [`supported_app_view_types`](AppBuildListItemBuilder::supported_app_view_types)
    pub fn build(self) -> Result<AppBuildListItem, BuildError> {
        Ok(AppBuildListItem {
            checksum: self
                .checksum
                .ok_or_else(|| BuildError::missing_field("checksum"))?,
            created_at: self
                .created_at
                .ok_or_else(|| BuildError::missing_field("created_at"))?,
            file_url: self
                .file_url
                .ok_or_else(|| BuildError::missing_field("file_url"))?,
            id: self.id.ok_or_else(|| BuildError::missing_field("id"))?,
            is_production: self
                .is_production
                .ok_or_else(|| BuildError::missing_field("is_production"))?,
            platform: self
                .platform
                .ok_or_else(|| BuildError::missing_field("platform"))?,
            review_message: self.review_message,
            source_url: self.source_url,
            status: self
                .status
                .ok_or_else(|| BuildError::missing_field("status"))?,
            supported_app_view_types: self
                .supported_app_view_types
                .ok_or_else(|| BuildError::missing_field("supported_app_view_types"))?,
        })
    }
}
