pub use crate::prelude::*;

/// Possible card brands that a payment token can have
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum CardBrands {
    Mastercard,
    Visa,
    Amex,
    Discover,
    Unionpay,
    Jcb,
    Diners,
    Link,
    Troy,
    Visadankort,
    Visabancontact,
    ChinaUnionPay,
    Rupay,
    Jcbrupay,
    Elo,
    Maestro,
    TarjetaNaranja,
    Cirrus,
    NspkMir,
    Verve,
    Ebt,
    PrivateLabel,
    LocalBrand,
    Uatp,
    Wexcard,
    Uzcard,
    Meeza,
    HrgStoreCard,
    Girocard,
    FuelCard,
    Dankort,
    Carnet,
    AtmCard,
    ChinaUnionPayuzcard,
    Codensa,
    Cabal,
    Hipercard,
    Jcblankapay,
    Cmi,
    Aura,
    Unknown,
    /// This variant is used for forward compatibility.
    /// If the server sends a value not recognized by the current SDK version,
    /// it will be captured here with the raw string value.
    __Unknown(String),
}
impl Serialize for CardBrands {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        match self {
            Self::Mastercard => serializer.serialize_str("mastercard"),
            Self::Visa => serializer.serialize_str("visa"),
            Self::Amex => serializer.serialize_str("amex"),
            Self::Discover => serializer.serialize_str("discover"),
            Self::Unionpay => serializer.serialize_str("unionpay"),
            Self::Jcb => serializer.serialize_str("jcb"),
            Self::Diners => serializer.serialize_str("diners"),
            Self::Link => serializer.serialize_str("link"),
            Self::Troy => serializer.serialize_str("troy"),
            Self::Visadankort => serializer.serialize_str("visadankort"),
            Self::Visabancontact => serializer.serialize_str("visabancontact"),
            Self::ChinaUnionPay => serializer.serialize_str("china_union_pay"),
            Self::Rupay => serializer.serialize_str("rupay"),
            Self::Jcbrupay => serializer.serialize_str("jcbrupay"),
            Self::Elo => serializer.serialize_str("elo"),
            Self::Maestro => serializer.serialize_str("maestro"),
            Self::TarjetaNaranja => serializer.serialize_str("tarjeta_naranja"),
            Self::Cirrus => serializer.serialize_str("cirrus"),
            Self::NspkMir => serializer.serialize_str("nspk_mir"),
            Self::Verve => serializer.serialize_str("verve"),
            Self::Ebt => serializer.serialize_str("ebt"),
            Self::PrivateLabel => serializer.serialize_str("private_label"),
            Self::LocalBrand => serializer.serialize_str("local_brand"),
            Self::Uatp => serializer.serialize_str("uatp"),
            Self::Wexcard => serializer.serialize_str("wexcard"),
            Self::Uzcard => serializer.serialize_str("uzcard"),
            Self::Meeza => serializer.serialize_str("meeza"),
            Self::HrgStoreCard => serializer.serialize_str("hrg_store_card"),
            Self::Girocard => serializer.serialize_str("girocard"),
            Self::FuelCard => serializer.serialize_str("fuel_card"),
            Self::Dankort => serializer.serialize_str("dankort"),
            Self::Carnet => serializer.serialize_str("carnet"),
            Self::AtmCard => serializer.serialize_str("atm_card"),
            Self::ChinaUnionPayuzcard => serializer.serialize_str("china_union_payuzcard"),
            Self::Codensa => serializer.serialize_str("codensa"),
            Self::Cabal => serializer.serialize_str("cabal"),
            Self::Hipercard => serializer.serialize_str("hipercard"),
            Self::Jcblankapay => serializer.serialize_str("jcblankapay"),
            Self::Cmi => serializer.serialize_str("cmi"),
            Self::Aura => serializer.serialize_str("aura"),
            Self::Unknown => serializer.serialize_str("unknown"),
            Self::__Unknown(val) => serializer.serialize_str(val),
        }
    }
}

impl<'de> Deserialize<'de> for CardBrands {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        match value.as_str() {
            "mastercard" => Ok(Self::Mastercard),
            "visa" => Ok(Self::Visa),
            "amex" => Ok(Self::Amex),
            "discover" => Ok(Self::Discover),
            "unionpay" => Ok(Self::Unionpay),
            "jcb" => Ok(Self::Jcb),
            "diners" => Ok(Self::Diners),
            "link" => Ok(Self::Link),
            "troy" => Ok(Self::Troy),
            "visadankort" => Ok(Self::Visadankort),
            "visabancontact" => Ok(Self::Visabancontact),
            "china_union_pay" => Ok(Self::ChinaUnionPay),
            "rupay" => Ok(Self::Rupay),
            "jcbrupay" => Ok(Self::Jcbrupay),
            "elo" => Ok(Self::Elo),
            "maestro" => Ok(Self::Maestro),
            "tarjeta_naranja" => Ok(Self::TarjetaNaranja),
            "cirrus" => Ok(Self::Cirrus),
            "nspk_mir" => Ok(Self::NspkMir),
            "verve" => Ok(Self::Verve),
            "ebt" => Ok(Self::Ebt),
            "private_label" => Ok(Self::PrivateLabel),
            "local_brand" => Ok(Self::LocalBrand),
            "uatp" => Ok(Self::Uatp),
            "wexcard" => Ok(Self::Wexcard),
            "uzcard" => Ok(Self::Uzcard),
            "meeza" => Ok(Self::Meeza),
            "hrg_store_card" => Ok(Self::HrgStoreCard),
            "girocard" => Ok(Self::Girocard),
            "fuel_card" => Ok(Self::FuelCard),
            "dankort" => Ok(Self::Dankort),
            "carnet" => Ok(Self::Carnet),
            "atm_card" => Ok(Self::AtmCard),
            "china_union_payuzcard" => Ok(Self::ChinaUnionPayuzcard),
            "codensa" => Ok(Self::Codensa),
            "cabal" => Ok(Self::Cabal),
            "hipercard" => Ok(Self::Hipercard),
            "jcblankapay" => Ok(Self::Jcblankapay),
            "cmi" => Ok(Self::Cmi),
            "aura" => Ok(Self::Aura),
            "unknown" => Ok(Self::Unknown),
            _ => Ok(Self::__Unknown(value)),
        }
    }
}

impl fmt::Display for CardBrands {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Mastercard => write!(f, "mastercard"),
            Self::Visa => write!(f, "visa"),
            Self::Amex => write!(f, "amex"),
            Self::Discover => write!(f, "discover"),
            Self::Unionpay => write!(f, "unionpay"),
            Self::Jcb => write!(f, "jcb"),
            Self::Diners => write!(f, "diners"),
            Self::Link => write!(f, "link"),
            Self::Troy => write!(f, "troy"),
            Self::Visadankort => write!(f, "visadankort"),
            Self::Visabancontact => write!(f, "visabancontact"),
            Self::ChinaUnionPay => write!(f, "china_union_pay"),
            Self::Rupay => write!(f, "rupay"),
            Self::Jcbrupay => write!(f, "jcbrupay"),
            Self::Elo => write!(f, "elo"),
            Self::Maestro => write!(f, "maestro"),
            Self::TarjetaNaranja => write!(f, "tarjeta_naranja"),
            Self::Cirrus => write!(f, "cirrus"),
            Self::NspkMir => write!(f, "nspk_mir"),
            Self::Verve => write!(f, "verve"),
            Self::Ebt => write!(f, "ebt"),
            Self::PrivateLabel => write!(f, "private_label"),
            Self::LocalBrand => write!(f, "local_brand"),
            Self::Uatp => write!(f, "uatp"),
            Self::Wexcard => write!(f, "wexcard"),
            Self::Uzcard => write!(f, "uzcard"),
            Self::Meeza => write!(f, "meeza"),
            Self::HrgStoreCard => write!(f, "hrg_store_card"),
            Self::Girocard => write!(f, "girocard"),
            Self::FuelCard => write!(f, "fuel_card"),
            Self::Dankort => write!(f, "dankort"),
            Self::Carnet => write!(f, "carnet"),
            Self::AtmCard => write!(f, "atm_card"),
            Self::ChinaUnionPayuzcard => write!(f, "china_union_payuzcard"),
            Self::Codensa => write!(f, "codensa"),
            Self::Cabal => write!(f, "cabal"),
            Self::Hipercard => write!(f, "hipercard"),
            Self::Jcblankapay => write!(f, "jcblankapay"),
            Self::Cmi => write!(f, "cmi"),
            Self::Aura => write!(f, "aura"),
            Self::Unknown => write!(f, "unknown"),
            Self::__Unknown(val) => write!(f, "{}", val),
        }
    }
}
