pub use crate::prelude::*;

/// The available countries on the platform
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum Countries {
    Us,
    Ca,
    Gb,
    Ab,
    Af,
    Al,
    Dz,
    As,
    Ad,
    Ao,
    Ai,
    Aq,
    Ag,
    Ar,
    Am,
    Aw,
    Au,
    At,
    Az,
    Bs,
    Bh,
    Bd,
    Bb,
    By,
    Be,
    Bz,
    Bj,
    Bm,
    Bt,
    Bo,
    Ba,
    Bw,
    Br,
    Io,
    Vg,
    Bn,
    Bg,
    Bf,
    Bi,
    Kh,
    Cm,
    Cv,
    Ky,
    Cf,
    Td,
    Cl,
    Cn,
    Cx,
    Cc,
    Co,
    Km,
    Cg,
    Ck,
    Cr,
    Ci,
    Hr,
    Cu,
    Cw,
    Cy,
    Cz,
    Cd,
    Dk,
    Dj,
    Dm,
    Do,
    Ec,
    Eg,
    Sv,
    Gq,
    Ee,
    Et,
    Fk,
    Fo,
    Fj,
    Fi,
    Fr,
    Gf,
    Pf,
    Ga,
    Gm,
    Ge,
    De,
    Gh,
    Gi,
    Gr,
    Gl,
    Gd,
    Gp,
    Gu,
    Gt,
    Gg,
    Gn,
    Gw,
    Gy,
    Ht,
    Hn,
    Hk,
    Hu,
    Is,
    In,
    Id,
    Iq,
    Ie,
    Im,
    Il,
    It,
    Jm,
    Sj,
    Jp,
    Je,
    Jo,
    Kz,
    Ke,
    Ki,
    Xk,
    Kw,
    Kg,
    La,
    Lv,
    Lb,
    Ls,
    Lr,
    Ly,
    Li,
    Lt,
    Lu,
    Mo,
    Mk,
    Mg,
    Mw,
    My,
    Mv,
    Ml,
    Mt,
    Mh,
    Mq,
    Mr,
    Mu,
    Yt,
    Mx,
    Fm,
    Md,
    Mc,
    Mn,
    Me,
    Ms,
    Ma,
    Mz,
    Mm,
    Na,
    Nr,
    Np,
    Nl,
    An,
    Nc,
    Nz,
    Ni,
    Ne,
    Ng,
    Nu,
    Mp,
    No,
    Om,
    Pk,
    Pw,
    Ps,
    Pa,
    Pg,
    Py,
    Pe,
    Ph,
    Pn,
    Pl,
    Pt,
    Pr,
    Qa,
    Re,
    Ro,
    Ru,
    Rw,
    Bl,
    Sh,
    Kn,
    Lc,
    Mf,
    Pm,
    Vc,
    Ws,
    Sm,
    St,
    Sa,
    Sn,
    Rs,
    Sc,
    Sl,
    Sg,
    Sx,
    Sk,
    Si,
    Sb,
    So,
    Za,
    Kr,
    Ss,
    Es,
    Lk,
    Sd,
    Sr,
    Sz,
    Se,
    Ch,
    Tw,
    Tj,
    Tz,
    Th,
    Tl,
    Tg,
    Tk,
    To,
    Tt,
    Tn,
    Tr,
    Tm,
    Tc,
    Tv,
    Vi,
    Ug,
    Ua,
    Ae,
    Um,
    Uy,
    Uz,
    Vu,
    Va,
    Ve,
    Vn,
    Wf,
    Eh,
    Ye,
    Zm,
    Zw,
    Sy,
    /// This variant is used for forward compatibility.
    /// If the server sends a value not recognized by the current SDK version,
    /// it will be captured here with the raw string value.
    __Unknown(String),
}
impl Serialize for Countries {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        match self {
            Self::Us => serializer.serialize_str("us"),
            Self::Ca => serializer.serialize_str("ca"),
            Self::Gb => serializer.serialize_str("gb"),
            Self::Ab => serializer.serialize_str("ab"),
            Self::Af => serializer.serialize_str("af"),
            Self::Al => serializer.serialize_str("al"),
            Self::Dz => serializer.serialize_str("dz"),
            Self::As => serializer.serialize_str("as"),
            Self::Ad => serializer.serialize_str("ad"),
            Self::Ao => serializer.serialize_str("ao"),
            Self::Ai => serializer.serialize_str("ai"),
            Self::Aq => serializer.serialize_str("aq"),
            Self::Ag => serializer.serialize_str("ag"),
            Self::Ar => serializer.serialize_str("ar"),
            Self::Am => serializer.serialize_str("am"),
            Self::Aw => serializer.serialize_str("aw"),
            Self::Au => serializer.serialize_str("au"),
            Self::At => serializer.serialize_str("at"),
            Self::Az => serializer.serialize_str("az"),
            Self::Bs => serializer.serialize_str("bs"),
            Self::Bh => serializer.serialize_str("bh"),
            Self::Bd => serializer.serialize_str("bd"),
            Self::Bb => serializer.serialize_str("bb"),
            Self::By => serializer.serialize_str("by"),
            Self::Be => serializer.serialize_str("be"),
            Self::Bz => serializer.serialize_str("bz"),
            Self::Bj => serializer.serialize_str("bj"),
            Self::Bm => serializer.serialize_str("bm"),
            Self::Bt => serializer.serialize_str("bt"),
            Self::Bo => serializer.serialize_str("bo"),
            Self::Ba => serializer.serialize_str("ba"),
            Self::Bw => serializer.serialize_str("bw"),
            Self::Br => serializer.serialize_str("br"),
            Self::Io => serializer.serialize_str("io"),
            Self::Vg => serializer.serialize_str("vg"),
            Self::Bn => serializer.serialize_str("bn"),
            Self::Bg => serializer.serialize_str("bg"),
            Self::Bf => serializer.serialize_str("bf"),
            Self::Bi => serializer.serialize_str("bi"),
            Self::Kh => serializer.serialize_str("kh"),
            Self::Cm => serializer.serialize_str("cm"),
            Self::Cv => serializer.serialize_str("cv"),
            Self::Ky => serializer.serialize_str("ky"),
            Self::Cf => serializer.serialize_str("cf"),
            Self::Td => serializer.serialize_str("td"),
            Self::Cl => serializer.serialize_str("cl"),
            Self::Cn => serializer.serialize_str("cn"),
            Self::Cx => serializer.serialize_str("cx"),
            Self::Cc => serializer.serialize_str("cc"),
            Self::Co => serializer.serialize_str("co"),
            Self::Km => serializer.serialize_str("km"),
            Self::Cg => serializer.serialize_str("cg"),
            Self::Ck => serializer.serialize_str("ck"),
            Self::Cr => serializer.serialize_str("cr"),
            Self::Ci => serializer.serialize_str("ci"),
            Self::Hr => serializer.serialize_str("hr"),
            Self::Cu => serializer.serialize_str("cu"),
            Self::Cw => serializer.serialize_str("cw"),
            Self::Cy => serializer.serialize_str("cy"),
            Self::Cz => serializer.serialize_str("cz"),
            Self::Cd => serializer.serialize_str("cd"),
            Self::Dk => serializer.serialize_str("dk"),
            Self::Dj => serializer.serialize_str("dj"),
            Self::Dm => serializer.serialize_str("dm"),
            Self::Do => serializer.serialize_str("do"),
            Self::Ec => serializer.serialize_str("ec"),
            Self::Eg => serializer.serialize_str("eg"),
            Self::Sv => serializer.serialize_str("sv"),
            Self::Gq => serializer.serialize_str("gq"),
            Self::Ee => serializer.serialize_str("ee"),
            Self::Et => serializer.serialize_str("et"),
            Self::Fk => serializer.serialize_str("fk"),
            Self::Fo => serializer.serialize_str("fo"),
            Self::Fj => serializer.serialize_str("fj"),
            Self::Fi => serializer.serialize_str("fi"),
            Self::Fr => serializer.serialize_str("fr"),
            Self::Gf => serializer.serialize_str("gf"),
            Self::Pf => serializer.serialize_str("pf"),
            Self::Ga => serializer.serialize_str("ga"),
            Self::Gm => serializer.serialize_str("gm"),
            Self::Ge => serializer.serialize_str("ge"),
            Self::De => serializer.serialize_str("de"),
            Self::Gh => serializer.serialize_str("gh"),
            Self::Gi => serializer.serialize_str("gi"),
            Self::Gr => serializer.serialize_str("gr"),
            Self::Gl => serializer.serialize_str("gl"),
            Self::Gd => serializer.serialize_str("gd"),
            Self::Gp => serializer.serialize_str("gp"),
            Self::Gu => serializer.serialize_str("gu"),
            Self::Gt => serializer.serialize_str("gt"),
            Self::Gg => serializer.serialize_str("gg"),
            Self::Gn => serializer.serialize_str("gn"),
            Self::Gw => serializer.serialize_str("gw"),
            Self::Gy => serializer.serialize_str("gy"),
            Self::Ht => serializer.serialize_str("ht"),
            Self::Hn => serializer.serialize_str("hn"),
            Self::Hk => serializer.serialize_str("hk"),
            Self::Hu => serializer.serialize_str("hu"),
            Self::Is => serializer.serialize_str("is"),
            Self::In => serializer.serialize_str("in"),
            Self::Id => serializer.serialize_str("id"),
            Self::Iq => serializer.serialize_str("iq"),
            Self::Ie => serializer.serialize_str("ie"),
            Self::Im => serializer.serialize_str("im"),
            Self::Il => serializer.serialize_str("il"),
            Self::It => serializer.serialize_str("it"),
            Self::Jm => serializer.serialize_str("jm"),
            Self::Sj => serializer.serialize_str("sj"),
            Self::Jp => serializer.serialize_str("jp"),
            Self::Je => serializer.serialize_str("je"),
            Self::Jo => serializer.serialize_str("jo"),
            Self::Kz => serializer.serialize_str("kz"),
            Self::Ke => serializer.serialize_str("ke"),
            Self::Ki => serializer.serialize_str("ki"),
            Self::Xk => serializer.serialize_str("xk"),
            Self::Kw => serializer.serialize_str("kw"),
            Self::Kg => serializer.serialize_str("kg"),
            Self::La => serializer.serialize_str("la"),
            Self::Lv => serializer.serialize_str("lv"),
            Self::Lb => serializer.serialize_str("lb"),
            Self::Ls => serializer.serialize_str("ls"),
            Self::Lr => serializer.serialize_str("lr"),
            Self::Ly => serializer.serialize_str("ly"),
            Self::Li => serializer.serialize_str("li"),
            Self::Lt => serializer.serialize_str("lt"),
            Self::Lu => serializer.serialize_str("lu"),
            Self::Mo => serializer.serialize_str("mo"),
            Self::Mk => serializer.serialize_str("mk"),
            Self::Mg => serializer.serialize_str("mg"),
            Self::Mw => serializer.serialize_str("mw"),
            Self::My => serializer.serialize_str("my"),
            Self::Mv => serializer.serialize_str("mv"),
            Self::Ml => serializer.serialize_str("ml"),
            Self::Mt => serializer.serialize_str("mt"),
            Self::Mh => serializer.serialize_str("mh"),
            Self::Mq => serializer.serialize_str("mq"),
            Self::Mr => serializer.serialize_str("mr"),
            Self::Mu => serializer.serialize_str("mu"),
            Self::Yt => serializer.serialize_str("yt"),
            Self::Mx => serializer.serialize_str("mx"),
            Self::Fm => serializer.serialize_str("fm"),
            Self::Md => serializer.serialize_str("md"),
            Self::Mc => serializer.serialize_str("mc"),
            Self::Mn => serializer.serialize_str("mn"),
            Self::Me => serializer.serialize_str("me"),
            Self::Ms => serializer.serialize_str("ms"),
            Self::Ma => serializer.serialize_str("ma"),
            Self::Mz => serializer.serialize_str("mz"),
            Self::Mm => serializer.serialize_str("mm"),
            Self::Na => serializer.serialize_str("na"),
            Self::Nr => serializer.serialize_str("nr"),
            Self::Np => serializer.serialize_str("np"),
            Self::Nl => serializer.serialize_str("nl"),
            Self::An => serializer.serialize_str("an"),
            Self::Nc => serializer.serialize_str("nc"),
            Self::Nz => serializer.serialize_str("nz"),
            Self::Ni => serializer.serialize_str("ni"),
            Self::Ne => serializer.serialize_str("ne"),
            Self::Ng => serializer.serialize_str("ng"),
            Self::Nu => serializer.serialize_str("nu"),
            Self::Mp => serializer.serialize_str("mp"),
            Self::No => serializer.serialize_str("no"),
            Self::Om => serializer.serialize_str("om"),
            Self::Pk => serializer.serialize_str("pk"),
            Self::Pw => serializer.serialize_str("pw"),
            Self::Ps => serializer.serialize_str("ps"),
            Self::Pa => serializer.serialize_str("pa"),
            Self::Pg => serializer.serialize_str("pg"),
            Self::Py => serializer.serialize_str("py"),
            Self::Pe => serializer.serialize_str("pe"),
            Self::Ph => serializer.serialize_str("ph"),
            Self::Pn => serializer.serialize_str("pn"),
            Self::Pl => serializer.serialize_str("pl"),
            Self::Pt => serializer.serialize_str("pt"),
            Self::Pr => serializer.serialize_str("pr"),
            Self::Qa => serializer.serialize_str("qa"),
            Self::Re => serializer.serialize_str("re"),
            Self::Ro => serializer.serialize_str("ro"),
            Self::Ru => serializer.serialize_str("ru"),
            Self::Rw => serializer.serialize_str("rw"),
            Self::Bl => serializer.serialize_str("bl"),
            Self::Sh => serializer.serialize_str("sh"),
            Self::Kn => serializer.serialize_str("kn"),
            Self::Lc => serializer.serialize_str("lc"),
            Self::Mf => serializer.serialize_str("mf"),
            Self::Pm => serializer.serialize_str("pm"),
            Self::Vc => serializer.serialize_str("vc"),
            Self::Ws => serializer.serialize_str("ws"),
            Self::Sm => serializer.serialize_str("sm"),
            Self::St => serializer.serialize_str("st"),
            Self::Sa => serializer.serialize_str("sa"),
            Self::Sn => serializer.serialize_str("sn"),
            Self::Rs => serializer.serialize_str("rs"),
            Self::Sc => serializer.serialize_str("sc"),
            Self::Sl => serializer.serialize_str("sl"),
            Self::Sg => serializer.serialize_str("sg"),
            Self::Sx => serializer.serialize_str("sx"),
            Self::Sk => serializer.serialize_str("sk"),
            Self::Si => serializer.serialize_str("si"),
            Self::Sb => serializer.serialize_str("sb"),
            Self::So => serializer.serialize_str("so"),
            Self::Za => serializer.serialize_str("za"),
            Self::Kr => serializer.serialize_str("kr"),
            Self::Ss => serializer.serialize_str("ss"),
            Self::Es => serializer.serialize_str("es"),
            Self::Lk => serializer.serialize_str("lk"),
            Self::Sd => serializer.serialize_str("sd"),
            Self::Sr => serializer.serialize_str("sr"),
            Self::Sz => serializer.serialize_str("sz"),
            Self::Se => serializer.serialize_str("se"),
            Self::Ch => serializer.serialize_str("ch"),
            Self::Tw => serializer.serialize_str("tw"),
            Self::Tj => serializer.serialize_str("tj"),
            Self::Tz => serializer.serialize_str("tz"),
            Self::Th => serializer.serialize_str("th"),
            Self::Tl => serializer.serialize_str("tl"),
            Self::Tg => serializer.serialize_str("tg"),
            Self::Tk => serializer.serialize_str("tk"),
            Self::To => serializer.serialize_str("to"),
            Self::Tt => serializer.serialize_str("tt"),
            Self::Tn => serializer.serialize_str("tn"),
            Self::Tr => serializer.serialize_str("tr"),
            Self::Tm => serializer.serialize_str("tm"),
            Self::Tc => serializer.serialize_str("tc"),
            Self::Tv => serializer.serialize_str("tv"),
            Self::Vi => serializer.serialize_str("vi"),
            Self::Ug => serializer.serialize_str("ug"),
            Self::Ua => serializer.serialize_str("ua"),
            Self::Ae => serializer.serialize_str("ae"),
            Self::Um => serializer.serialize_str("um"),
            Self::Uy => serializer.serialize_str("uy"),
            Self::Uz => serializer.serialize_str("uz"),
            Self::Vu => serializer.serialize_str("vu"),
            Self::Va => serializer.serialize_str("va"),
            Self::Ve => serializer.serialize_str("ve"),
            Self::Vn => serializer.serialize_str("vn"),
            Self::Wf => serializer.serialize_str("wf"),
            Self::Eh => serializer.serialize_str("eh"),
            Self::Ye => serializer.serialize_str("ye"),
            Self::Zm => serializer.serialize_str("zm"),
            Self::Zw => serializer.serialize_str("zw"),
            Self::Sy => serializer.serialize_str("sy"),
            Self::__Unknown(val) => serializer.serialize_str(val),
        }
    }
}

impl<'de> Deserialize<'de> for Countries {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        match value.as_str() {
            "us" => Ok(Self::Us),
            "ca" => Ok(Self::Ca),
            "gb" => Ok(Self::Gb),
            "ab" => Ok(Self::Ab),
            "af" => Ok(Self::Af),
            "al" => Ok(Self::Al),
            "dz" => Ok(Self::Dz),
            "as" => Ok(Self::As),
            "ad" => Ok(Self::Ad),
            "ao" => Ok(Self::Ao),
            "ai" => Ok(Self::Ai),
            "aq" => Ok(Self::Aq),
            "ag" => Ok(Self::Ag),
            "ar" => Ok(Self::Ar),
            "am" => Ok(Self::Am),
            "aw" => Ok(Self::Aw),
            "au" => Ok(Self::Au),
            "at" => Ok(Self::At),
            "az" => Ok(Self::Az),
            "bs" => Ok(Self::Bs),
            "bh" => Ok(Self::Bh),
            "bd" => Ok(Self::Bd),
            "bb" => Ok(Self::Bb),
            "by" => Ok(Self::By),
            "be" => Ok(Self::Be),
            "bz" => Ok(Self::Bz),
            "bj" => Ok(Self::Bj),
            "bm" => Ok(Self::Bm),
            "bt" => Ok(Self::Bt),
            "bo" => Ok(Self::Bo),
            "ba" => Ok(Self::Ba),
            "bw" => Ok(Self::Bw),
            "br" => Ok(Self::Br),
            "io" => Ok(Self::Io),
            "vg" => Ok(Self::Vg),
            "bn" => Ok(Self::Bn),
            "bg" => Ok(Self::Bg),
            "bf" => Ok(Self::Bf),
            "bi" => Ok(Self::Bi),
            "kh" => Ok(Self::Kh),
            "cm" => Ok(Self::Cm),
            "cv" => Ok(Self::Cv),
            "ky" => Ok(Self::Ky),
            "cf" => Ok(Self::Cf),
            "td" => Ok(Self::Td),
            "cl" => Ok(Self::Cl),
            "cn" => Ok(Self::Cn),
            "cx" => Ok(Self::Cx),
            "cc" => Ok(Self::Cc),
            "co" => Ok(Self::Co),
            "km" => Ok(Self::Km),
            "cg" => Ok(Self::Cg),
            "ck" => Ok(Self::Ck),
            "cr" => Ok(Self::Cr),
            "ci" => Ok(Self::Ci),
            "hr" => Ok(Self::Hr),
            "cu" => Ok(Self::Cu),
            "cw" => Ok(Self::Cw),
            "cy" => Ok(Self::Cy),
            "cz" => Ok(Self::Cz),
            "cd" => Ok(Self::Cd),
            "dk" => Ok(Self::Dk),
            "dj" => Ok(Self::Dj),
            "dm" => Ok(Self::Dm),
            "do" => Ok(Self::Do),
            "ec" => Ok(Self::Ec),
            "eg" => Ok(Self::Eg),
            "sv" => Ok(Self::Sv),
            "gq" => Ok(Self::Gq),
            "ee" => Ok(Self::Ee),
            "et" => Ok(Self::Et),
            "fk" => Ok(Self::Fk),
            "fo" => Ok(Self::Fo),
            "fj" => Ok(Self::Fj),
            "fi" => Ok(Self::Fi),
            "fr" => Ok(Self::Fr),
            "gf" => Ok(Self::Gf),
            "pf" => Ok(Self::Pf),
            "ga" => Ok(Self::Ga),
            "gm" => Ok(Self::Gm),
            "ge" => Ok(Self::Ge),
            "de" => Ok(Self::De),
            "gh" => Ok(Self::Gh),
            "gi" => Ok(Self::Gi),
            "gr" => Ok(Self::Gr),
            "gl" => Ok(Self::Gl),
            "gd" => Ok(Self::Gd),
            "gp" => Ok(Self::Gp),
            "gu" => Ok(Self::Gu),
            "gt" => Ok(Self::Gt),
            "gg" => Ok(Self::Gg),
            "gn" => Ok(Self::Gn),
            "gw" => Ok(Self::Gw),
            "gy" => Ok(Self::Gy),
            "ht" => Ok(Self::Ht),
            "hn" => Ok(Self::Hn),
            "hk" => Ok(Self::Hk),
            "hu" => Ok(Self::Hu),
            "is" => Ok(Self::Is),
            "in" => Ok(Self::In),
            "id" => Ok(Self::Id),
            "iq" => Ok(Self::Iq),
            "ie" => Ok(Self::Ie),
            "im" => Ok(Self::Im),
            "il" => Ok(Self::Il),
            "it" => Ok(Self::It),
            "jm" => Ok(Self::Jm),
            "sj" => Ok(Self::Sj),
            "jp" => Ok(Self::Jp),
            "je" => Ok(Self::Je),
            "jo" => Ok(Self::Jo),
            "kz" => Ok(Self::Kz),
            "ke" => Ok(Self::Ke),
            "ki" => Ok(Self::Ki),
            "xk" => Ok(Self::Xk),
            "kw" => Ok(Self::Kw),
            "kg" => Ok(Self::Kg),
            "la" => Ok(Self::La),
            "lv" => Ok(Self::Lv),
            "lb" => Ok(Self::Lb),
            "ls" => Ok(Self::Ls),
            "lr" => Ok(Self::Lr),
            "ly" => Ok(Self::Ly),
            "li" => Ok(Self::Li),
            "lt" => Ok(Self::Lt),
            "lu" => Ok(Self::Lu),
            "mo" => Ok(Self::Mo),
            "mk" => Ok(Self::Mk),
            "mg" => Ok(Self::Mg),
            "mw" => Ok(Self::Mw),
            "my" => Ok(Self::My),
            "mv" => Ok(Self::Mv),
            "ml" => Ok(Self::Ml),
            "mt" => Ok(Self::Mt),
            "mh" => Ok(Self::Mh),
            "mq" => Ok(Self::Mq),
            "mr" => Ok(Self::Mr),
            "mu" => Ok(Self::Mu),
            "yt" => Ok(Self::Yt),
            "mx" => Ok(Self::Mx),
            "fm" => Ok(Self::Fm),
            "md" => Ok(Self::Md),
            "mc" => Ok(Self::Mc),
            "mn" => Ok(Self::Mn),
            "me" => Ok(Self::Me),
            "ms" => Ok(Self::Ms),
            "ma" => Ok(Self::Ma),
            "mz" => Ok(Self::Mz),
            "mm" => Ok(Self::Mm),
            "na" => Ok(Self::Na),
            "nr" => Ok(Self::Nr),
            "np" => Ok(Self::Np),
            "nl" => Ok(Self::Nl),
            "an" => Ok(Self::An),
            "nc" => Ok(Self::Nc),
            "nz" => Ok(Self::Nz),
            "ni" => Ok(Self::Ni),
            "ne" => Ok(Self::Ne),
            "ng" => Ok(Self::Ng),
            "nu" => Ok(Self::Nu),
            "mp" => Ok(Self::Mp),
            "no" => Ok(Self::No),
            "om" => Ok(Self::Om),
            "pk" => Ok(Self::Pk),
            "pw" => Ok(Self::Pw),
            "ps" => Ok(Self::Ps),
            "pa" => Ok(Self::Pa),
            "pg" => Ok(Self::Pg),
            "py" => Ok(Self::Py),
            "pe" => Ok(Self::Pe),
            "ph" => Ok(Self::Ph),
            "pn" => Ok(Self::Pn),
            "pl" => Ok(Self::Pl),
            "pt" => Ok(Self::Pt),
            "pr" => Ok(Self::Pr),
            "qa" => Ok(Self::Qa),
            "re" => Ok(Self::Re),
            "ro" => Ok(Self::Ro),
            "ru" => Ok(Self::Ru),
            "rw" => Ok(Self::Rw),
            "bl" => Ok(Self::Bl),
            "sh" => Ok(Self::Sh),
            "kn" => Ok(Self::Kn),
            "lc" => Ok(Self::Lc),
            "mf" => Ok(Self::Mf),
            "pm" => Ok(Self::Pm),
            "vc" => Ok(Self::Vc),
            "ws" => Ok(Self::Ws),
            "sm" => Ok(Self::Sm),
            "st" => Ok(Self::St),
            "sa" => Ok(Self::Sa),
            "sn" => Ok(Self::Sn),
            "rs" => Ok(Self::Rs),
            "sc" => Ok(Self::Sc),
            "sl" => Ok(Self::Sl),
            "sg" => Ok(Self::Sg),
            "sx" => Ok(Self::Sx),
            "sk" => Ok(Self::Sk),
            "si" => Ok(Self::Si),
            "sb" => Ok(Self::Sb),
            "so" => Ok(Self::So),
            "za" => Ok(Self::Za),
            "kr" => Ok(Self::Kr),
            "ss" => Ok(Self::Ss),
            "es" => Ok(Self::Es),
            "lk" => Ok(Self::Lk),
            "sd" => Ok(Self::Sd),
            "sr" => Ok(Self::Sr),
            "sz" => Ok(Self::Sz),
            "se" => Ok(Self::Se),
            "ch" => Ok(Self::Ch),
            "tw" => Ok(Self::Tw),
            "tj" => Ok(Self::Tj),
            "tz" => Ok(Self::Tz),
            "th" => Ok(Self::Th),
            "tl" => Ok(Self::Tl),
            "tg" => Ok(Self::Tg),
            "tk" => Ok(Self::Tk),
            "to" => Ok(Self::To),
            "tt" => Ok(Self::Tt),
            "tn" => Ok(Self::Tn),
            "tr" => Ok(Self::Tr),
            "tm" => Ok(Self::Tm),
            "tc" => Ok(Self::Tc),
            "tv" => Ok(Self::Tv),
            "vi" => Ok(Self::Vi),
            "ug" => Ok(Self::Ug),
            "ua" => Ok(Self::Ua),
            "ae" => Ok(Self::Ae),
            "um" => Ok(Self::Um),
            "uy" => Ok(Self::Uy),
            "uz" => Ok(Self::Uz),
            "vu" => Ok(Self::Vu),
            "va" => Ok(Self::Va),
            "ve" => Ok(Self::Ve),
            "vn" => Ok(Self::Vn),
            "wf" => Ok(Self::Wf),
            "eh" => Ok(Self::Eh),
            "ye" => Ok(Self::Ye),
            "zm" => Ok(Self::Zm),
            "zw" => Ok(Self::Zw),
            "sy" => Ok(Self::Sy),
            _ => Ok(Self::__Unknown(value)),
        }
    }
}

impl fmt::Display for Countries {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Us => write!(f, "us"),
            Self::Ca => write!(f, "ca"),
            Self::Gb => write!(f, "gb"),
            Self::Ab => write!(f, "ab"),
            Self::Af => write!(f, "af"),
            Self::Al => write!(f, "al"),
            Self::Dz => write!(f, "dz"),
            Self::As => write!(f, "as"),
            Self::Ad => write!(f, "ad"),
            Self::Ao => write!(f, "ao"),
            Self::Ai => write!(f, "ai"),
            Self::Aq => write!(f, "aq"),
            Self::Ag => write!(f, "ag"),
            Self::Ar => write!(f, "ar"),
            Self::Am => write!(f, "am"),
            Self::Aw => write!(f, "aw"),
            Self::Au => write!(f, "au"),
            Self::At => write!(f, "at"),
            Self::Az => write!(f, "az"),
            Self::Bs => write!(f, "bs"),
            Self::Bh => write!(f, "bh"),
            Self::Bd => write!(f, "bd"),
            Self::Bb => write!(f, "bb"),
            Self::By => write!(f, "by"),
            Self::Be => write!(f, "be"),
            Self::Bz => write!(f, "bz"),
            Self::Bj => write!(f, "bj"),
            Self::Bm => write!(f, "bm"),
            Self::Bt => write!(f, "bt"),
            Self::Bo => write!(f, "bo"),
            Self::Ba => write!(f, "ba"),
            Self::Bw => write!(f, "bw"),
            Self::Br => write!(f, "br"),
            Self::Io => write!(f, "io"),
            Self::Vg => write!(f, "vg"),
            Self::Bn => write!(f, "bn"),
            Self::Bg => write!(f, "bg"),
            Self::Bf => write!(f, "bf"),
            Self::Bi => write!(f, "bi"),
            Self::Kh => write!(f, "kh"),
            Self::Cm => write!(f, "cm"),
            Self::Cv => write!(f, "cv"),
            Self::Ky => write!(f, "ky"),
            Self::Cf => write!(f, "cf"),
            Self::Td => write!(f, "td"),
            Self::Cl => write!(f, "cl"),
            Self::Cn => write!(f, "cn"),
            Self::Cx => write!(f, "cx"),
            Self::Cc => write!(f, "cc"),
            Self::Co => write!(f, "co"),
            Self::Km => write!(f, "km"),
            Self::Cg => write!(f, "cg"),
            Self::Ck => write!(f, "ck"),
            Self::Cr => write!(f, "cr"),
            Self::Ci => write!(f, "ci"),
            Self::Hr => write!(f, "hr"),
            Self::Cu => write!(f, "cu"),
            Self::Cw => write!(f, "cw"),
            Self::Cy => write!(f, "cy"),
            Self::Cz => write!(f, "cz"),
            Self::Cd => write!(f, "cd"),
            Self::Dk => write!(f, "dk"),
            Self::Dj => write!(f, "dj"),
            Self::Dm => write!(f, "dm"),
            Self::Do => write!(f, "do"),
            Self::Ec => write!(f, "ec"),
            Self::Eg => write!(f, "eg"),
            Self::Sv => write!(f, "sv"),
            Self::Gq => write!(f, "gq"),
            Self::Ee => write!(f, "ee"),
            Self::Et => write!(f, "et"),
            Self::Fk => write!(f, "fk"),
            Self::Fo => write!(f, "fo"),
            Self::Fj => write!(f, "fj"),
            Self::Fi => write!(f, "fi"),
            Self::Fr => write!(f, "fr"),
            Self::Gf => write!(f, "gf"),
            Self::Pf => write!(f, "pf"),
            Self::Ga => write!(f, "ga"),
            Self::Gm => write!(f, "gm"),
            Self::Ge => write!(f, "ge"),
            Self::De => write!(f, "de"),
            Self::Gh => write!(f, "gh"),
            Self::Gi => write!(f, "gi"),
            Self::Gr => write!(f, "gr"),
            Self::Gl => write!(f, "gl"),
            Self::Gd => write!(f, "gd"),
            Self::Gp => write!(f, "gp"),
            Self::Gu => write!(f, "gu"),
            Self::Gt => write!(f, "gt"),
            Self::Gg => write!(f, "gg"),
            Self::Gn => write!(f, "gn"),
            Self::Gw => write!(f, "gw"),
            Self::Gy => write!(f, "gy"),
            Self::Ht => write!(f, "ht"),
            Self::Hn => write!(f, "hn"),
            Self::Hk => write!(f, "hk"),
            Self::Hu => write!(f, "hu"),
            Self::Is => write!(f, "is"),
            Self::In => write!(f, "in"),
            Self::Id => write!(f, "id"),
            Self::Iq => write!(f, "iq"),
            Self::Ie => write!(f, "ie"),
            Self::Im => write!(f, "im"),
            Self::Il => write!(f, "il"),
            Self::It => write!(f, "it"),
            Self::Jm => write!(f, "jm"),
            Self::Sj => write!(f, "sj"),
            Self::Jp => write!(f, "jp"),
            Self::Je => write!(f, "je"),
            Self::Jo => write!(f, "jo"),
            Self::Kz => write!(f, "kz"),
            Self::Ke => write!(f, "ke"),
            Self::Ki => write!(f, "ki"),
            Self::Xk => write!(f, "xk"),
            Self::Kw => write!(f, "kw"),
            Self::Kg => write!(f, "kg"),
            Self::La => write!(f, "la"),
            Self::Lv => write!(f, "lv"),
            Self::Lb => write!(f, "lb"),
            Self::Ls => write!(f, "ls"),
            Self::Lr => write!(f, "lr"),
            Self::Ly => write!(f, "ly"),
            Self::Li => write!(f, "li"),
            Self::Lt => write!(f, "lt"),
            Self::Lu => write!(f, "lu"),
            Self::Mo => write!(f, "mo"),
            Self::Mk => write!(f, "mk"),
            Self::Mg => write!(f, "mg"),
            Self::Mw => write!(f, "mw"),
            Self::My => write!(f, "my"),
            Self::Mv => write!(f, "mv"),
            Self::Ml => write!(f, "ml"),
            Self::Mt => write!(f, "mt"),
            Self::Mh => write!(f, "mh"),
            Self::Mq => write!(f, "mq"),
            Self::Mr => write!(f, "mr"),
            Self::Mu => write!(f, "mu"),
            Self::Yt => write!(f, "yt"),
            Self::Mx => write!(f, "mx"),
            Self::Fm => write!(f, "fm"),
            Self::Md => write!(f, "md"),
            Self::Mc => write!(f, "mc"),
            Self::Mn => write!(f, "mn"),
            Self::Me => write!(f, "me"),
            Self::Ms => write!(f, "ms"),
            Self::Ma => write!(f, "ma"),
            Self::Mz => write!(f, "mz"),
            Self::Mm => write!(f, "mm"),
            Self::Na => write!(f, "na"),
            Self::Nr => write!(f, "nr"),
            Self::Np => write!(f, "np"),
            Self::Nl => write!(f, "nl"),
            Self::An => write!(f, "an"),
            Self::Nc => write!(f, "nc"),
            Self::Nz => write!(f, "nz"),
            Self::Ni => write!(f, "ni"),
            Self::Ne => write!(f, "ne"),
            Self::Ng => write!(f, "ng"),
            Self::Nu => write!(f, "nu"),
            Self::Mp => write!(f, "mp"),
            Self::No => write!(f, "no"),
            Self::Om => write!(f, "om"),
            Self::Pk => write!(f, "pk"),
            Self::Pw => write!(f, "pw"),
            Self::Ps => write!(f, "ps"),
            Self::Pa => write!(f, "pa"),
            Self::Pg => write!(f, "pg"),
            Self::Py => write!(f, "py"),
            Self::Pe => write!(f, "pe"),
            Self::Ph => write!(f, "ph"),
            Self::Pn => write!(f, "pn"),
            Self::Pl => write!(f, "pl"),
            Self::Pt => write!(f, "pt"),
            Self::Pr => write!(f, "pr"),
            Self::Qa => write!(f, "qa"),
            Self::Re => write!(f, "re"),
            Self::Ro => write!(f, "ro"),
            Self::Ru => write!(f, "ru"),
            Self::Rw => write!(f, "rw"),
            Self::Bl => write!(f, "bl"),
            Self::Sh => write!(f, "sh"),
            Self::Kn => write!(f, "kn"),
            Self::Lc => write!(f, "lc"),
            Self::Mf => write!(f, "mf"),
            Self::Pm => write!(f, "pm"),
            Self::Vc => write!(f, "vc"),
            Self::Ws => write!(f, "ws"),
            Self::Sm => write!(f, "sm"),
            Self::St => write!(f, "st"),
            Self::Sa => write!(f, "sa"),
            Self::Sn => write!(f, "sn"),
            Self::Rs => write!(f, "rs"),
            Self::Sc => write!(f, "sc"),
            Self::Sl => write!(f, "sl"),
            Self::Sg => write!(f, "sg"),
            Self::Sx => write!(f, "sx"),
            Self::Sk => write!(f, "sk"),
            Self::Si => write!(f, "si"),
            Self::Sb => write!(f, "sb"),
            Self::So => write!(f, "so"),
            Self::Za => write!(f, "za"),
            Self::Kr => write!(f, "kr"),
            Self::Ss => write!(f, "ss"),
            Self::Es => write!(f, "es"),
            Self::Lk => write!(f, "lk"),
            Self::Sd => write!(f, "sd"),
            Self::Sr => write!(f, "sr"),
            Self::Sz => write!(f, "sz"),
            Self::Se => write!(f, "se"),
            Self::Ch => write!(f, "ch"),
            Self::Tw => write!(f, "tw"),
            Self::Tj => write!(f, "tj"),
            Self::Tz => write!(f, "tz"),
            Self::Th => write!(f, "th"),
            Self::Tl => write!(f, "tl"),
            Self::Tg => write!(f, "tg"),
            Self::Tk => write!(f, "tk"),
            Self::To => write!(f, "to"),
            Self::Tt => write!(f, "tt"),
            Self::Tn => write!(f, "tn"),
            Self::Tr => write!(f, "tr"),
            Self::Tm => write!(f, "tm"),
            Self::Tc => write!(f, "tc"),
            Self::Tv => write!(f, "tv"),
            Self::Vi => write!(f, "vi"),
            Self::Ug => write!(f, "ug"),
            Self::Ua => write!(f, "ua"),
            Self::Ae => write!(f, "ae"),
            Self::Um => write!(f, "um"),
            Self::Uy => write!(f, "uy"),
            Self::Uz => write!(f, "uz"),
            Self::Vu => write!(f, "vu"),
            Self::Va => write!(f, "va"),
            Self::Ve => write!(f, "ve"),
            Self::Vn => write!(f, "vn"),
            Self::Wf => write!(f, "wf"),
            Self::Eh => write!(f, "eh"),
            Self::Ye => write!(f, "ye"),
            Self::Zm => write!(f, "zm"),
            Self::Zw => write!(f, "zw"),
            Self::Sy => write!(f, "sy"),
            Self::__Unknown(val) => write!(f, "{}", val),
        }
    }
}
