pub use crate::prelude::*;

/// The resource to export, e.g. `payouts`, `receipts`, or `members`.
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum CreateExportsRequestResource {
    AdCampaigns,
    AdGroups,
    Ads,
    Apps,
    Audiences,
    Bounties,
    BountySubmissions,
    CardTransactions,
    CheckoutConfigurations,
    Disputes,
    Events,
    FinancialActivity,
    Members,
    Memberships,
    PayoutMethods,
    Payouts,
    People,
    Plans,
    Products,
    ResolutionCenterCases,
    Shipments,
    SocialAccounts,
    TeamMembers,
    Transfers,
    Webhooks,
    Receipts,
    UnclaimedMemberships,
    TrackingLinks,
    PromoCodes,
    Resolutions,
    Entries,
    Leads,
    ContentRewardsSubmissions,
    Invoices,
    CancelationReasons,
    ChildCompanies,
    /// This variant is used for forward compatibility.
    /// If the server sends a value not recognized by the current SDK version,
    /// it will be captured here with the raw string value.
    __Unknown(String),
}
impl Serialize for CreateExportsRequestResource {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        match self {
            Self::AdCampaigns => serializer.serialize_str("ad_campaigns"),
            Self::AdGroups => serializer.serialize_str("ad_groups"),
            Self::Ads => serializer.serialize_str("ads"),
            Self::Apps => serializer.serialize_str("apps"),
            Self::Audiences => serializer.serialize_str("audiences"),
            Self::Bounties => serializer.serialize_str("bounties"),
            Self::BountySubmissions => serializer.serialize_str("bounty_submissions"),
            Self::CardTransactions => serializer.serialize_str("card_transactions"),
            Self::CheckoutConfigurations => serializer.serialize_str("checkout_configurations"),
            Self::Disputes => serializer.serialize_str("disputes"),
            Self::Events => serializer.serialize_str("events"),
            Self::FinancialActivity => serializer.serialize_str("financial-activity"),
            Self::Members => serializer.serialize_str("members"),
            Self::Memberships => serializer.serialize_str("memberships"),
            Self::PayoutMethods => serializer.serialize_str("payout_methods"),
            Self::Payouts => serializer.serialize_str("payouts"),
            Self::People => serializer.serialize_str("people"),
            Self::Plans => serializer.serialize_str("plans"),
            Self::Products => serializer.serialize_str("products"),
            Self::ResolutionCenterCases => serializer.serialize_str("resolution_center_cases"),
            Self::Shipments => serializer.serialize_str("shipments"),
            Self::SocialAccounts => serializer.serialize_str("social_accounts"),
            Self::TeamMembers => serializer.serialize_str("team_members"),
            Self::Transfers => serializer.serialize_str("transfers"),
            Self::Webhooks => serializer.serialize_str("webhooks"),
            Self::Receipts => serializer.serialize_str("receipts"),
            Self::UnclaimedMemberships => serializer.serialize_str("unclaimed_memberships"),
            Self::TrackingLinks => serializer.serialize_str("tracking_links"),
            Self::PromoCodes => serializer.serialize_str("promo_codes"),
            Self::Resolutions => serializer.serialize_str("resolutions"),
            Self::Entries => serializer.serialize_str("entries"),
            Self::Leads => serializer.serialize_str("leads"),
            Self::ContentRewardsSubmissions => {
                serializer.serialize_str("content_rewards_submissions")
            }
            Self::Invoices => serializer.serialize_str("invoices"),
            Self::CancelationReasons => serializer.serialize_str("cancelation_reasons"),
            Self::ChildCompanies => serializer.serialize_str("child_companies"),
            Self::__Unknown(val) => serializer.serialize_str(val),
        }
    }
}

impl<'de> Deserialize<'de> for CreateExportsRequestResource {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        match value.as_str() {
            "ad_campaigns" => Ok(Self::AdCampaigns),
            "ad_groups" => Ok(Self::AdGroups),
            "ads" => Ok(Self::Ads),
            "apps" => Ok(Self::Apps),
            "audiences" => Ok(Self::Audiences),
            "bounties" => Ok(Self::Bounties),
            "bounty_submissions" => Ok(Self::BountySubmissions),
            "card_transactions" => Ok(Self::CardTransactions),
            "checkout_configurations" => Ok(Self::CheckoutConfigurations),
            "disputes" => Ok(Self::Disputes),
            "events" => Ok(Self::Events),
            "financial-activity" => Ok(Self::FinancialActivity),
            "members" => Ok(Self::Members),
            "memberships" => Ok(Self::Memberships),
            "payout_methods" => Ok(Self::PayoutMethods),
            "payouts" => Ok(Self::Payouts),
            "people" => Ok(Self::People),
            "plans" => Ok(Self::Plans),
            "products" => Ok(Self::Products),
            "resolution_center_cases" => Ok(Self::ResolutionCenterCases),
            "shipments" => Ok(Self::Shipments),
            "social_accounts" => Ok(Self::SocialAccounts),
            "team_members" => Ok(Self::TeamMembers),
            "transfers" => Ok(Self::Transfers),
            "webhooks" => Ok(Self::Webhooks),
            "receipts" => Ok(Self::Receipts),
            "unclaimed_memberships" => Ok(Self::UnclaimedMemberships),
            "tracking_links" => Ok(Self::TrackingLinks),
            "promo_codes" => Ok(Self::PromoCodes),
            "resolutions" => Ok(Self::Resolutions),
            "entries" => Ok(Self::Entries),
            "leads" => Ok(Self::Leads),
            "content_rewards_submissions" => Ok(Self::ContentRewardsSubmissions),
            "invoices" => Ok(Self::Invoices),
            "cancelation_reasons" => Ok(Self::CancelationReasons),
            "child_companies" => Ok(Self::ChildCompanies),
            _ => Ok(Self::__Unknown(value)),
        }
    }
}

impl fmt::Display for CreateExportsRequestResource {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::AdCampaigns => write!(f, "ad_campaigns"),
            Self::AdGroups => write!(f, "ad_groups"),
            Self::Ads => write!(f, "ads"),
            Self::Apps => write!(f, "apps"),
            Self::Audiences => write!(f, "audiences"),
            Self::Bounties => write!(f, "bounties"),
            Self::BountySubmissions => write!(f, "bounty_submissions"),
            Self::CardTransactions => write!(f, "card_transactions"),
            Self::CheckoutConfigurations => write!(f, "checkout_configurations"),
            Self::Disputes => write!(f, "disputes"),
            Self::Events => write!(f, "events"),
            Self::FinancialActivity => write!(f, "financial-activity"),
            Self::Members => write!(f, "members"),
            Self::Memberships => write!(f, "memberships"),
            Self::PayoutMethods => write!(f, "payout_methods"),
            Self::Payouts => write!(f, "payouts"),
            Self::People => write!(f, "people"),
            Self::Plans => write!(f, "plans"),
            Self::Products => write!(f, "products"),
            Self::ResolutionCenterCases => write!(f, "resolution_center_cases"),
            Self::Shipments => write!(f, "shipments"),
            Self::SocialAccounts => write!(f, "social_accounts"),
            Self::TeamMembers => write!(f, "team_members"),
            Self::Transfers => write!(f, "transfers"),
            Self::Webhooks => write!(f, "webhooks"),
            Self::Receipts => write!(f, "receipts"),
            Self::UnclaimedMemberships => write!(f, "unclaimed_memberships"),
            Self::TrackingLinks => write!(f, "tracking_links"),
            Self::PromoCodes => write!(f, "promo_codes"),
            Self::Resolutions => write!(f, "resolutions"),
            Self::Entries => write!(f, "entries"),
            Self::Leads => write!(f, "leads"),
            Self::ContentRewardsSubmissions => write!(f, "content_rewards_submissions"),
            Self::Invoices => write!(f, "invoices"),
            Self::CancelationReasons => write!(f, "cancelation_reasons"),
            Self::ChildCompanies => write!(f, "child_companies"),
            Self::__Unknown(val) => write!(f, "{}", val),
        }
    }
}
