pub use crate::prelude::*;

/// Autogenerated input type of CreateInvoice
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct CreateInvoicesRequestProductId {
    /// The date and time when the invoice will be automatically finalized. For charge_automatically, triggers an automatic charge. For send_invoice, sends the invoice email to the customer at the specified time.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub automatically_finalizes_at: Option<DateTime<FixedOffset>>,
    /// Inline billing address to create a new mailing address for this invoice. Cannot be used together with mailing_address_id.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub billing_address: Option<CreateInvoicesRequestProductIdBillingAddress>,
    /// Whether to charge the customer a buyer fee on this invoice.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub charge_buyer_fee: Option<bool>,
    /// How the invoice should be collected. Use charge_automatically to charge a stored payment method, or send_invoice to email the customer.
    pub collection_method: InvoiceCollectionMethods,
    /// The unique identifier of the company to create this invoice for.
    #[serde(default)]
    pub company_id: String,
    /// The name of the customer. Required when creating an invoice for a customer who is not yet a member of the company.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub customer_name: Option<String>,
    /// The date by which the invoice must be paid. Required unless save_as_draft is true.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub due_date: Option<DateTime<FixedOffset>>,
    /// The email address of the customer. Required when creating an invoice for a customer who is not yet a member of the company.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub email_address: Option<String>,
    /// Optional line items that break down the invoice total. When provided, the sum of (quantity * unit_price) for all items must equal the plan price. Individual items may be negative to represent a credit, as long as the sum is not negative and clears the currency's minimum charge.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub line_items: Option<Vec<CreateInvoicesRequestProductIdLineItemsItem>>,
    /// The unique identifier of an existing mailing address to attach to this invoice. Cannot be used together with billing_address.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mailing_address_id: Option<String>,
    /// The unique identifier of an existing member to create this invoice for. If not provided, you must supply an email_address and customer_name.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub member_id: Option<String>,
    /// The unique identifier of the payment method to charge. Required when collection_method is charge_automatically.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payment_method_id: Option<String>,
    /// The payment token ID to use for this invoice. If using charge_automatically, you must provide a payment_token.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payment_token_id: Option<String>,
    /// The plan attributes defining the price, currency, and billing interval for this invoice.
    #[serde(default)]
    pub plan: CreateInvoicesRequestProductIdPlan,
    /// The unique identifier of an existing product to create this invoice for.
    #[serde(default)]
    pub product_id: String,
    /// When true, creates the invoice as a draft without sending or charging. Relaxes customer and due date requirements.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub save_as_draft: Option<bool>,
    /// The date that defines when the subscription billing cycle should start. When set on a renewal plan invoice, this anchors all future billing periods to this date.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub subscription_billing_anchor_at: Option<DateTime<FixedOffset>>,
}

impl CreateInvoicesRequestProductId {
    pub fn builder() -> CreateInvoicesRequestProductIdBuilder {
        <CreateInvoicesRequestProductIdBuilder as Default>::default()
    }
}

#[derive(Clone, PartialEq, Default, Debug)]
#[non_exhaustive]
pub struct CreateInvoicesRequestProductIdBuilder {
    automatically_finalizes_at: Option<DateTime<FixedOffset>>,
    billing_address: Option<CreateInvoicesRequestProductIdBillingAddress>,
    charge_buyer_fee: Option<bool>,
    collection_method: Option<InvoiceCollectionMethods>,
    company_id: Option<String>,
    customer_name: Option<String>,
    due_date: Option<DateTime<FixedOffset>>,
    email_address: Option<String>,
    line_items: Option<Vec<CreateInvoicesRequestProductIdLineItemsItem>>,
    mailing_address_id: Option<String>,
    member_id: Option<String>,
    payment_method_id: Option<String>,
    payment_token_id: Option<String>,
    plan: Option<CreateInvoicesRequestProductIdPlan>,
    product_id: Option<String>,
    save_as_draft: Option<bool>,
    subscription_billing_anchor_at: Option<DateTime<FixedOffset>>,
}

impl CreateInvoicesRequestProductIdBuilder {
    pub fn automatically_finalizes_at(mut self, value: DateTime<FixedOffset>) -> Self {
        self.automatically_finalizes_at = Some(value);
        self
    }

    pub fn billing_address(mut self, value: CreateInvoicesRequestProductIdBillingAddress) -> Self {
        self.billing_address = Some(value);
        self
    }

    pub fn charge_buyer_fee(mut self, value: bool) -> Self {
        self.charge_buyer_fee = Some(value);
        self
    }

    pub fn collection_method(mut self, value: InvoiceCollectionMethods) -> Self {
        self.collection_method = Some(value);
        self
    }

    pub fn company_id(mut self, value: impl Into<String>) -> Self {
        self.company_id = Some(value.into());
        self
    }

    pub fn customer_name(mut self, value: impl Into<String>) -> Self {
        self.customer_name = Some(value.into());
        self
    }

    pub fn due_date(mut self, value: DateTime<FixedOffset>) -> Self {
        self.due_date = Some(value);
        self
    }

    pub fn email_address(mut self, value: impl Into<String>) -> Self {
        self.email_address = Some(value.into());
        self
    }

    pub fn line_items(mut self, value: Vec<CreateInvoicesRequestProductIdLineItemsItem>) -> Self {
        self.line_items = Some(value);
        self
    }

    pub fn mailing_address_id(mut self, value: impl Into<String>) -> Self {
        self.mailing_address_id = Some(value.into());
        self
    }

    pub fn member_id(mut self, value: impl Into<String>) -> Self {
        self.member_id = Some(value.into());
        self
    }

    pub fn payment_method_id(mut self, value: impl Into<String>) -> Self {
        self.payment_method_id = Some(value.into());
        self
    }

    pub fn payment_token_id(mut self, value: impl Into<String>) -> Self {
        self.payment_token_id = Some(value.into());
        self
    }

    pub fn plan(mut self, value: CreateInvoicesRequestProductIdPlan) -> Self {
        self.plan = Some(value);
        self
    }

    pub fn product_id(mut self, value: impl Into<String>) -> Self {
        self.product_id = Some(value.into());
        self
    }

    pub fn save_as_draft(mut self, value: bool) -> Self {
        self.save_as_draft = Some(value);
        self
    }

    pub fn subscription_billing_anchor_at(mut self, value: DateTime<FixedOffset>) -> Self {
        self.subscription_billing_anchor_at = Some(value);
        self
    }

    /// Consumes the builder and constructs a [`CreateInvoicesRequestProductId`].
    /// This method will fail if any of the following fields are not set:
    /// - [`collection_method`](CreateInvoicesRequestProductIdBuilder::collection_method)
    /// - [`company_id`](CreateInvoicesRequestProductIdBuilder::company_id)
    /// - [`plan`](CreateInvoicesRequestProductIdBuilder::plan)
    /// - [`product_id`](CreateInvoicesRequestProductIdBuilder::product_id)
    pub fn build(self) -> Result<CreateInvoicesRequestProductId, BuildError> {
        Ok(CreateInvoicesRequestProductId {
            automatically_finalizes_at: self.automatically_finalizes_at,
            billing_address: self.billing_address,
            charge_buyer_fee: self.charge_buyer_fee,
            collection_method: self
                .collection_method
                .ok_or_else(|| BuildError::missing_field("collection_method"))?,
            company_id: self
                .company_id
                .ok_or_else(|| BuildError::missing_field("company_id"))?,
            customer_name: self.customer_name,
            due_date: self.due_date,
            email_address: self.email_address,
            line_items: self.line_items,
            mailing_address_id: self.mailing_address_id,
            member_id: self.member_id,
            payment_method_id: self.payment_method_id,
            payment_token_id: self.payment_token_id,
            plan: self.plan.ok_or_else(|| BuildError::missing_field("plan"))?,
            product_id: self
                .product_id
                .ok_or_else(|| BuildError::missing_field("product_id"))?,
            save_as_draft: self.save_as_draft,
            subscription_billing_anchor_at: self.subscription_billing_anchor_at,
        })
    }
}
