pub use crate::prelude::*;

/// The reason a payment was declined.
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum PaymentDeclineCodes {
    InsufficientFunds,
    LostCard,
    StolenCard,
    ExpiredCard,
    SuspectedFraud,
    InvalidCardNumber,
    InvalidCvc,
    InvalidCvcOrExpiration,
    IncorrectPin,
    AuthenticationRequired,
    CardNotSupported,
    CurrencyNotSupported,
    DuplicateTransaction,
    GenericDecline,
    InvalidAccount,
    InvalidAmount,
    ProcessingError,
    RestrictedCard,
    CardVelocityExceeded,
    ContactIssuer,
    BankDeclined,
    RegulatoryBlocked,
    TransactionNotPermitted,
    TransactionStopped,
    CardTypeNotSupported,
    IssuerNotFound,
    ClosedAccount,
    IssuerUnavailable,
    InvalidZip,
    InvalidExpiryMonth,
    InvalidExpiryYear,
    InvalidExpiry,
    InvalidTransaction,
    CannotAuthorize,
    PinRequired,
    PinTryExceeded,
    ProviderDeclined,
    HighRisk,
    TestModeDecline,
    MerchantBlacklist,
    ReenterTransaction,
    InvalidPin,
    PinRequiredAs,
    WithdrawalCountLimitExceeded,
    InvalidCountry,
    IssuerError,
    InvalidCardHolderName,
    NoAccounts,
    TransactionCancelled,
    ThreeDSecureSuccess,
    ThreeDSecureCanceled,
    ThreeDSecureInvalidCardNumber,
    ThreeDSecureGenericError,
    ThreeDSecureTimeout,
    ThreeDSecureFailed,
    ThreeDSecureCardNotEnrolled,
    ThreeDSecureFraud,
    ThreeDSecureTooManyAttempts,
    ThreeDSecureRejectedByBank,
    ThreeDSecureReportedLostOrStolen,
    BlockedByCardholder,
    TestModeTestCard,
    TryAgainLater,
    TransactionNotAllowed,
    BankInsufficientFunds,
    BankAccountNotFound,
    BankAccountClosed,
    BankAccountFrozen,
    BankInvalidRoutingNumber,
    BankNonTransactionAccount,
    BankAuthorizationRevoked,
    BankPaymentStopped,
    BankNotAuthorized,
    BankAccountHolderDeceased,
    BankDuplicate,
    BankAmountError,
    BankRegulatoryBlocked,
    BankDetailsInvalid,
    BankProcessingError,
    BankGenericDecline,
    SepaInvalidIban,
    SepaNoMandate,
    SepaMandateDataInvalid,
    SepaDisputed,
    SepaRefusedByCustomer,
    SepaGenericDecline,
    /// This variant is used for forward compatibility.
    /// If the server sends a value not recognized by the current SDK version,
    /// it will be captured here with the raw string value.
    __Unknown(String),
}
impl Serialize for PaymentDeclineCodes {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        match self {
            Self::InsufficientFunds => serializer.serialize_str("insufficient_funds"),
            Self::LostCard => serializer.serialize_str("lost_card"),
            Self::StolenCard => serializer.serialize_str("stolen_card"),
            Self::ExpiredCard => serializer.serialize_str("expired_card"),
            Self::SuspectedFraud => serializer.serialize_str("suspected_fraud"),
            Self::InvalidCardNumber => serializer.serialize_str("invalid_card_number"),
            Self::InvalidCvc => serializer.serialize_str("invalid_cvc"),
            Self::InvalidCvcOrExpiration => serializer.serialize_str("invalid_cvc_or_expiration"),
            Self::IncorrectPin => serializer.serialize_str("incorrect_pin"),
            Self::AuthenticationRequired => serializer.serialize_str("authentication_required"),
            Self::CardNotSupported => serializer.serialize_str("card_not_supported"),
            Self::CurrencyNotSupported => serializer.serialize_str("currency_not_supported"),
            Self::DuplicateTransaction => serializer.serialize_str("duplicate_transaction"),
            Self::GenericDecline => serializer.serialize_str("generic_decline"),
            Self::InvalidAccount => serializer.serialize_str("invalid_account"),
            Self::InvalidAmount => serializer.serialize_str("invalid_amount"),
            Self::ProcessingError => serializer.serialize_str("processing_error"),
            Self::RestrictedCard => serializer.serialize_str("restricted_card"),
            Self::CardVelocityExceeded => serializer.serialize_str("card_velocity_exceeded"),
            Self::ContactIssuer => serializer.serialize_str("contact_issuer"),
            Self::BankDeclined => serializer.serialize_str("bank_declined"),
            Self::RegulatoryBlocked => serializer.serialize_str("regulatory_blocked"),
            Self::TransactionNotPermitted => serializer.serialize_str("transaction_not_permitted"),
            Self::TransactionStopped => serializer.serialize_str("transaction_stopped"),
            Self::CardTypeNotSupported => serializer.serialize_str("card_type_not_supported"),
            Self::IssuerNotFound => serializer.serialize_str("issuer_not_found"),
            Self::ClosedAccount => serializer.serialize_str("closed_account"),
            Self::IssuerUnavailable => serializer.serialize_str("issuer_unavailable"),
            Self::InvalidZip => serializer.serialize_str("invalid_zip"),
            Self::InvalidExpiryMonth => serializer.serialize_str("invalid_expiry_month"),
            Self::InvalidExpiryYear => serializer.serialize_str("invalid_expiry_year"),
            Self::InvalidExpiry => serializer.serialize_str("invalid_expiry"),
            Self::InvalidTransaction => serializer.serialize_str("invalid_transaction"),
            Self::CannotAuthorize => serializer.serialize_str("cannot_authorize"),
            Self::PinRequired => serializer.serialize_str("pin_required"),
            Self::PinTryExceeded => serializer.serialize_str("pin_try_exceeded"),
            Self::ProviderDeclined => serializer.serialize_str("provider_declined"),
            Self::HighRisk => serializer.serialize_str("high_risk"),
            Self::TestModeDecline => serializer.serialize_str("test_mode_decline"),
            Self::MerchantBlacklist => serializer.serialize_str("merchant_blacklist"),
            Self::ReenterTransaction => serializer.serialize_str("reenter_transaction"),
            Self::InvalidPin => serializer.serialize_str("invalid_pin"),
            Self::PinRequiredAs => serializer.serialize_str("pin_required_as"),
            Self::WithdrawalCountLimitExceeded => {
                serializer.serialize_str("withdrawal_count_limit_exceeded")
            }
            Self::InvalidCountry => serializer.serialize_str("invalid_country"),
            Self::IssuerError => serializer.serialize_str("issuer_error"),
            Self::InvalidCardHolderName => serializer.serialize_str("invalid_card_holder_name"),
            Self::NoAccounts => serializer.serialize_str("no_accounts"),
            Self::TransactionCancelled => serializer.serialize_str("transaction_cancelled"),
            Self::ThreeDSecureSuccess => serializer.serialize_str("three_d_secure_success"),
            Self::ThreeDSecureCanceled => serializer.serialize_str("three_d_secure_canceled"),
            Self::ThreeDSecureInvalidCardNumber => {
                serializer.serialize_str("three_d_secure_invalid_card_number")
            }
            Self::ThreeDSecureGenericError => {
                serializer.serialize_str("three_d_secure_generic_error")
            }
            Self::ThreeDSecureTimeout => serializer.serialize_str("three_d_secure_timeout"),
            Self::ThreeDSecureFailed => serializer.serialize_str("three_d_secure_failed"),
            Self::ThreeDSecureCardNotEnrolled => {
                serializer.serialize_str("three_d_secure_card_not_enrolled")
            }
            Self::ThreeDSecureFraud => serializer.serialize_str("three_d_secure_fraud"),
            Self::ThreeDSecureTooManyAttempts => {
                serializer.serialize_str("three_d_secure_too_many_attempts")
            }
            Self::ThreeDSecureRejectedByBank => {
                serializer.serialize_str("three_d_secure_rejected_by_bank")
            }
            Self::ThreeDSecureReportedLostOrStolen => {
                serializer.serialize_str("three_d_secure_reported_lost_or_stolen")
            }
            Self::BlockedByCardholder => serializer.serialize_str("blocked_by_cardholder"),
            Self::TestModeTestCard => serializer.serialize_str("test_mode_test_card"),
            Self::TryAgainLater => serializer.serialize_str("try_again_later"),
            Self::TransactionNotAllowed => serializer.serialize_str("transaction_not_allowed"),
            Self::BankInsufficientFunds => serializer.serialize_str("bank_insufficient_funds"),
            Self::BankAccountNotFound => serializer.serialize_str("bank_account_not_found"),
            Self::BankAccountClosed => serializer.serialize_str("bank_account_closed"),
            Self::BankAccountFrozen => serializer.serialize_str("bank_account_frozen"),
            Self::BankInvalidRoutingNumber => {
                serializer.serialize_str("bank_invalid_routing_number")
            }
            Self::BankNonTransactionAccount => {
                serializer.serialize_str("bank_non_transaction_account")
            }
            Self::BankAuthorizationRevoked => {
                serializer.serialize_str("bank_authorization_revoked")
            }
            Self::BankPaymentStopped => serializer.serialize_str("bank_payment_stopped"),
            Self::BankNotAuthorized => serializer.serialize_str("bank_not_authorized"),
            Self::BankAccountHolderDeceased => {
                serializer.serialize_str("bank_account_holder_deceased")
            }
            Self::BankDuplicate => serializer.serialize_str("bank_duplicate"),
            Self::BankAmountError => serializer.serialize_str("bank_amount_error"),
            Self::BankRegulatoryBlocked => serializer.serialize_str("bank_regulatory_blocked"),
            Self::BankDetailsInvalid => serializer.serialize_str("bank_details_invalid"),
            Self::BankProcessingError => serializer.serialize_str("bank_processing_error"),
            Self::BankGenericDecline => serializer.serialize_str("bank_generic_decline"),
            Self::SepaInvalidIban => serializer.serialize_str("sepa_invalid_iban"),
            Self::SepaNoMandate => serializer.serialize_str("sepa_no_mandate"),
            Self::SepaMandateDataInvalid => serializer.serialize_str("sepa_mandate_data_invalid"),
            Self::SepaDisputed => serializer.serialize_str("sepa_disputed"),
            Self::SepaRefusedByCustomer => serializer.serialize_str("sepa_refused_by_customer"),
            Self::SepaGenericDecline => serializer.serialize_str("sepa_generic_decline"),
            Self::__Unknown(val) => serializer.serialize_str(val),
        }
    }
}

impl<'de> Deserialize<'de> for PaymentDeclineCodes {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        match value.as_str() {
            "insufficient_funds" => Ok(Self::InsufficientFunds),
            "lost_card" => Ok(Self::LostCard),
            "stolen_card" => Ok(Self::StolenCard),
            "expired_card" => Ok(Self::ExpiredCard),
            "suspected_fraud" => Ok(Self::SuspectedFraud),
            "invalid_card_number" => Ok(Self::InvalidCardNumber),
            "invalid_cvc" => Ok(Self::InvalidCvc),
            "invalid_cvc_or_expiration" => Ok(Self::InvalidCvcOrExpiration),
            "incorrect_pin" => Ok(Self::IncorrectPin),
            "authentication_required" => Ok(Self::AuthenticationRequired),
            "card_not_supported" => Ok(Self::CardNotSupported),
            "currency_not_supported" => Ok(Self::CurrencyNotSupported),
            "duplicate_transaction" => Ok(Self::DuplicateTransaction),
            "generic_decline" => Ok(Self::GenericDecline),
            "invalid_account" => Ok(Self::InvalidAccount),
            "invalid_amount" => Ok(Self::InvalidAmount),
            "processing_error" => Ok(Self::ProcessingError),
            "restricted_card" => Ok(Self::RestrictedCard),
            "card_velocity_exceeded" => Ok(Self::CardVelocityExceeded),
            "contact_issuer" => Ok(Self::ContactIssuer),
            "bank_declined" => Ok(Self::BankDeclined),
            "regulatory_blocked" => Ok(Self::RegulatoryBlocked),
            "transaction_not_permitted" => Ok(Self::TransactionNotPermitted),
            "transaction_stopped" => Ok(Self::TransactionStopped),
            "card_type_not_supported" => Ok(Self::CardTypeNotSupported),
            "issuer_not_found" => Ok(Self::IssuerNotFound),
            "closed_account" => Ok(Self::ClosedAccount),
            "issuer_unavailable" => Ok(Self::IssuerUnavailable),
            "invalid_zip" => Ok(Self::InvalidZip),
            "invalid_expiry_month" => Ok(Self::InvalidExpiryMonth),
            "invalid_expiry_year" => Ok(Self::InvalidExpiryYear),
            "invalid_expiry" => Ok(Self::InvalidExpiry),
            "invalid_transaction" => Ok(Self::InvalidTransaction),
            "cannot_authorize" => Ok(Self::CannotAuthorize),
            "pin_required" => Ok(Self::PinRequired),
            "pin_try_exceeded" => Ok(Self::PinTryExceeded),
            "provider_declined" => Ok(Self::ProviderDeclined),
            "high_risk" => Ok(Self::HighRisk),
            "test_mode_decline" => Ok(Self::TestModeDecline),
            "merchant_blacklist" => Ok(Self::MerchantBlacklist),
            "reenter_transaction" => Ok(Self::ReenterTransaction),
            "invalid_pin" => Ok(Self::InvalidPin),
            "pin_required_as" => Ok(Self::PinRequiredAs),
            "withdrawal_count_limit_exceeded" => Ok(Self::WithdrawalCountLimitExceeded),
            "invalid_country" => Ok(Self::InvalidCountry),
            "issuer_error" => Ok(Self::IssuerError),
            "invalid_card_holder_name" => Ok(Self::InvalidCardHolderName),
            "no_accounts" => Ok(Self::NoAccounts),
            "transaction_cancelled" => Ok(Self::TransactionCancelled),
            "three_d_secure_success" => Ok(Self::ThreeDSecureSuccess),
            "three_d_secure_canceled" => Ok(Self::ThreeDSecureCanceled),
            "three_d_secure_invalid_card_number" => Ok(Self::ThreeDSecureInvalidCardNumber),
            "three_d_secure_generic_error" => Ok(Self::ThreeDSecureGenericError),
            "three_d_secure_timeout" => Ok(Self::ThreeDSecureTimeout),
            "three_d_secure_failed" => Ok(Self::ThreeDSecureFailed),
            "three_d_secure_card_not_enrolled" => Ok(Self::ThreeDSecureCardNotEnrolled),
            "three_d_secure_fraud" => Ok(Self::ThreeDSecureFraud),
            "three_d_secure_too_many_attempts" => Ok(Self::ThreeDSecureTooManyAttempts),
            "three_d_secure_rejected_by_bank" => Ok(Self::ThreeDSecureRejectedByBank),
            "three_d_secure_reported_lost_or_stolen" => Ok(Self::ThreeDSecureReportedLostOrStolen),
            "blocked_by_cardholder" => Ok(Self::BlockedByCardholder),
            "test_mode_test_card" => Ok(Self::TestModeTestCard),
            "try_again_later" => Ok(Self::TryAgainLater),
            "transaction_not_allowed" => Ok(Self::TransactionNotAllowed),
            "bank_insufficient_funds" => Ok(Self::BankInsufficientFunds),
            "bank_account_not_found" => Ok(Self::BankAccountNotFound),
            "bank_account_closed" => Ok(Self::BankAccountClosed),
            "bank_account_frozen" => Ok(Self::BankAccountFrozen),
            "bank_invalid_routing_number" => Ok(Self::BankInvalidRoutingNumber),
            "bank_non_transaction_account" => Ok(Self::BankNonTransactionAccount),
            "bank_authorization_revoked" => Ok(Self::BankAuthorizationRevoked),
            "bank_payment_stopped" => Ok(Self::BankPaymentStopped),
            "bank_not_authorized" => Ok(Self::BankNotAuthorized),
            "bank_account_holder_deceased" => Ok(Self::BankAccountHolderDeceased),
            "bank_duplicate" => Ok(Self::BankDuplicate),
            "bank_amount_error" => Ok(Self::BankAmountError),
            "bank_regulatory_blocked" => Ok(Self::BankRegulatoryBlocked),
            "bank_details_invalid" => Ok(Self::BankDetailsInvalid),
            "bank_processing_error" => Ok(Self::BankProcessingError),
            "bank_generic_decline" => Ok(Self::BankGenericDecline),
            "sepa_invalid_iban" => Ok(Self::SepaInvalidIban),
            "sepa_no_mandate" => Ok(Self::SepaNoMandate),
            "sepa_mandate_data_invalid" => Ok(Self::SepaMandateDataInvalid),
            "sepa_disputed" => Ok(Self::SepaDisputed),
            "sepa_refused_by_customer" => Ok(Self::SepaRefusedByCustomer),
            "sepa_generic_decline" => Ok(Self::SepaGenericDecline),
            _ => Ok(Self::__Unknown(value)),
        }
    }
}

impl fmt::Display for PaymentDeclineCodes {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InsufficientFunds => write!(f, "insufficient_funds"),
            Self::LostCard => write!(f, "lost_card"),
            Self::StolenCard => write!(f, "stolen_card"),
            Self::ExpiredCard => write!(f, "expired_card"),
            Self::SuspectedFraud => write!(f, "suspected_fraud"),
            Self::InvalidCardNumber => write!(f, "invalid_card_number"),
            Self::InvalidCvc => write!(f, "invalid_cvc"),
            Self::InvalidCvcOrExpiration => write!(f, "invalid_cvc_or_expiration"),
            Self::IncorrectPin => write!(f, "incorrect_pin"),
            Self::AuthenticationRequired => write!(f, "authentication_required"),
            Self::CardNotSupported => write!(f, "card_not_supported"),
            Self::CurrencyNotSupported => write!(f, "currency_not_supported"),
            Self::DuplicateTransaction => write!(f, "duplicate_transaction"),
            Self::GenericDecline => write!(f, "generic_decline"),
            Self::InvalidAccount => write!(f, "invalid_account"),
            Self::InvalidAmount => write!(f, "invalid_amount"),
            Self::ProcessingError => write!(f, "processing_error"),
            Self::RestrictedCard => write!(f, "restricted_card"),
            Self::CardVelocityExceeded => write!(f, "card_velocity_exceeded"),
            Self::ContactIssuer => write!(f, "contact_issuer"),
            Self::BankDeclined => write!(f, "bank_declined"),
            Self::RegulatoryBlocked => write!(f, "regulatory_blocked"),
            Self::TransactionNotPermitted => write!(f, "transaction_not_permitted"),
            Self::TransactionStopped => write!(f, "transaction_stopped"),
            Self::CardTypeNotSupported => write!(f, "card_type_not_supported"),
            Self::IssuerNotFound => write!(f, "issuer_not_found"),
            Self::ClosedAccount => write!(f, "closed_account"),
            Self::IssuerUnavailable => write!(f, "issuer_unavailable"),
            Self::InvalidZip => write!(f, "invalid_zip"),
            Self::InvalidExpiryMonth => write!(f, "invalid_expiry_month"),
            Self::InvalidExpiryYear => write!(f, "invalid_expiry_year"),
            Self::InvalidExpiry => write!(f, "invalid_expiry"),
            Self::InvalidTransaction => write!(f, "invalid_transaction"),
            Self::CannotAuthorize => write!(f, "cannot_authorize"),
            Self::PinRequired => write!(f, "pin_required"),
            Self::PinTryExceeded => write!(f, "pin_try_exceeded"),
            Self::ProviderDeclined => write!(f, "provider_declined"),
            Self::HighRisk => write!(f, "high_risk"),
            Self::TestModeDecline => write!(f, "test_mode_decline"),
            Self::MerchantBlacklist => write!(f, "merchant_blacklist"),
            Self::ReenterTransaction => write!(f, "reenter_transaction"),
            Self::InvalidPin => write!(f, "invalid_pin"),
            Self::PinRequiredAs => write!(f, "pin_required_as"),
            Self::WithdrawalCountLimitExceeded => write!(f, "withdrawal_count_limit_exceeded"),
            Self::InvalidCountry => write!(f, "invalid_country"),
            Self::IssuerError => write!(f, "issuer_error"),
            Self::InvalidCardHolderName => write!(f, "invalid_card_holder_name"),
            Self::NoAccounts => write!(f, "no_accounts"),
            Self::TransactionCancelled => write!(f, "transaction_cancelled"),
            Self::ThreeDSecureSuccess => write!(f, "three_d_secure_success"),
            Self::ThreeDSecureCanceled => write!(f, "three_d_secure_canceled"),
            Self::ThreeDSecureInvalidCardNumber => write!(f, "three_d_secure_invalid_card_number"),
            Self::ThreeDSecureGenericError => write!(f, "three_d_secure_generic_error"),
            Self::ThreeDSecureTimeout => write!(f, "three_d_secure_timeout"),
            Self::ThreeDSecureFailed => write!(f, "three_d_secure_failed"),
            Self::ThreeDSecureCardNotEnrolled => write!(f, "three_d_secure_card_not_enrolled"),
            Self::ThreeDSecureFraud => write!(f, "three_d_secure_fraud"),
            Self::ThreeDSecureTooManyAttempts => write!(f, "three_d_secure_too_many_attempts"),
            Self::ThreeDSecureRejectedByBank => write!(f, "three_d_secure_rejected_by_bank"),
            Self::ThreeDSecureReportedLostOrStolen => {
                write!(f, "three_d_secure_reported_lost_or_stolen")
            }
            Self::BlockedByCardholder => write!(f, "blocked_by_cardholder"),
            Self::TestModeTestCard => write!(f, "test_mode_test_card"),
            Self::TryAgainLater => write!(f, "try_again_later"),
            Self::TransactionNotAllowed => write!(f, "transaction_not_allowed"),
            Self::BankInsufficientFunds => write!(f, "bank_insufficient_funds"),
            Self::BankAccountNotFound => write!(f, "bank_account_not_found"),
            Self::BankAccountClosed => write!(f, "bank_account_closed"),
            Self::BankAccountFrozen => write!(f, "bank_account_frozen"),
            Self::BankInvalidRoutingNumber => write!(f, "bank_invalid_routing_number"),
            Self::BankNonTransactionAccount => write!(f, "bank_non_transaction_account"),
            Self::BankAuthorizationRevoked => write!(f, "bank_authorization_revoked"),
            Self::BankPaymentStopped => write!(f, "bank_payment_stopped"),
            Self::BankNotAuthorized => write!(f, "bank_not_authorized"),
            Self::BankAccountHolderDeceased => write!(f, "bank_account_holder_deceased"),
            Self::BankDuplicate => write!(f, "bank_duplicate"),
            Self::BankAmountError => write!(f, "bank_amount_error"),
            Self::BankRegulatoryBlocked => write!(f, "bank_regulatory_blocked"),
            Self::BankDetailsInvalid => write!(f, "bank_details_invalid"),
            Self::BankProcessingError => write!(f, "bank_processing_error"),
            Self::BankGenericDecline => write!(f, "bank_generic_decline"),
            Self::SepaInvalidIban => write!(f, "sepa_invalid_iban"),
            Self::SepaNoMandate => write!(f, "sepa_no_mandate"),
            Self::SepaMandateDataInvalid => write!(f, "sepa_mandate_data_invalid"),
            Self::SepaDisputed => write!(f, "sepa_disputed"),
            Self::SepaRefusedByCustomer => write!(f, "sepa_refused_by_customer"),
            Self::SepaGenericDecline => write!(f, "sepa_generic_decline"),
            Self::__Unknown(val) => write!(f, "{}", val),
        }
    }
}
