pub use crate::prelude::*;

/// Autogenerated input type of CreatePayment
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct CreatePaymentsRequestBodyOne {
    /// Whether to capture the card payment immediately. Pass false to place an authorization hold that must be captured in full within five days.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub capture: Option<bool>,
    /// The ID of the company to create the payment for.
    #[serde(default)]
    pub company_id: String,
    /// Overrides the buyer email carried on the confirmation token, resolving or creating the Whop user the payment belongs to. Ignored when the confirmation token was created by a signed-in buyer, and unless confirmation_token is provided.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// The ID of the member to create the payment for. Required unless confirmation_token is provided.
    #[serde(default)]
    pub member_id: String,
    /// Custom metadata to attach to the payment.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<HashMap<String, serde_json::Value>>,
    /// The ID of the payment method to use for the payment. It must be connected to the Member being charged. Required unless confirmation_token is provided.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payment_method_id: Option<String>,
    /// Pass this object to create a new plan for this payment
    pub plan: CreatePaymentsRequestBodyOnePlan,
    /// The ID of an active promo code to apply to this payment. The promo code must belong to the company and be valid for the plan being purchased. The plan must be attached to a product — promo codes are not eligible for one-off purchases.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub promo_code_id: Option<String>,
    /// Where the buyer continues after completing an off-site step. Must be an absolute https URL without credentials (http is allowed for localhost), at most 2,048 characters. Editable until they return — see the payment's update endpoint. Ignored unless confirmation_token is provided.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub return_url: Option<String>,
}

impl CreatePaymentsRequestBodyOne {
    pub fn builder() -> CreatePaymentsRequestBodyOneBuilder {
        <CreatePaymentsRequestBodyOneBuilder as Default>::default()
    }
}

#[derive(Clone, PartialEq, Default, Debug)]
#[non_exhaustive]
pub struct CreatePaymentsRequestBodyOneBuilder {
    capture: Option<bool>,
    company_id: Option<String>,
    email: Option<String>,
    member_id: Option<String>,
    metadata: Option<HashMap<String, serde_json::Value>>,
    payment_method_id: Option<String>,
    plan: Option<CreatePaymentsRequestBodyOnePlan>,
    promo_code_id: Option<String>,
    return_url: Option<String>,
}

impl CreatePaymentsRequestBodyOneBuilder {
    pub fn capture(mut self, value: bool) -> Self {
        self.capture = Some(value);
        self
    }

    pub fn company_id(mut self, value: impl Into<String>) -> Self {
        self.company_id = Some(value.into());
        self
    }

    pub fn email(mut self, value: impl Into<String>) -> Self {
        self.email = Some(value.into());
        self
    }

    pub fn member_id(mut self, value: impl Into<String>) -> Self {
        self.member_id = Some(value.into());
        self
    }

    pub fn metadata(mut self, value: HashMap<String, serde_json::Value>) -> Self {
        self.metadata = Some(value);
        self
    }

    pub fn payment_method_id(mut self, value: impl Into<String>) -> Self {
        self.payment_method_id = Some(value.into());
        self
    }

    pub fn plan(mut self, value: CreatePaymentsRequestBodyOnePlan) -> Self {
        self.plan = Some(value);
        self
    }

    pub fn promo_code_id(mut self, value: impl Into<String>) -> Self {
        self.promo_code_id = Some(value.into());
        self
    }

    pub fn return_url(mut self, value: impl Into<String>) -> Self {
        self.return_url = Some(value.into());
        self
    }

    /// Consumes the builder and constructs a [`CreatePaymentsRequestBodyOne`].
    /// This method will fail if any of the following fields are not set:
    /// - [`company_id`](CreatePaymentsRequestBodyOneBuilder::company_id)
    /// - [`member_id`](CreatePaymentsRequestBodyOneBuilder::member_id)
    /// - [`plan`](CreatePaymentsRequestBodyOneBuilder::plan)
    pub fn build(self) -> Result<CreatePaymentsRequestBodyOne, BuildError> {
        Ok(CreatePaymentsRequestBodyOne {
            capture: self.capture,
            company_id: self
                .company_id
                .ok_or_else(|| BuildError::missing_field("company_id"))?,
            email: self.email,
            member_id: self
                .member_id
                .ok_or_else(|| BuildError::missing_field("member_id"))?,
            metadata: self.metadata,
            payment_method_id: self.payment_method_id,
            plan: self.plan.ok_or_else(|| BuildError::missing_field("plan"))?,
            promo_code_id: self.promo_code_id,
            return_url: self.return_url,
        })
    }
}
