pub use crate::prelude::*;

/// The different types of payment methods that can be used.
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum PaymentMethodTypes {
    AcssDebit,
    Addi,
    Affirm,
    AfterpayClearpay,
    Alipay,
    Alma,
    AmazonPay,
    Apple,
    ApplePay,
    AuBankTransfer,
    AuBecsDebit,
    BacsDebit,
    Bancolombia,
    Bancontact,
    BankWire,
    Billie,
    Bizum,
    Blik,
    Boleto,
    BreB,
    CaBankTransfer,
    CapchasePay,
    Card,
    CardInstallmentsThree,
    CardInstallmentsSix,
    CardInstallmentsTwelve,
    Cashapp,
    Claritypay,
    Coinbase,
    Crypto,
    Custom,
    CustomerBalance,
    DemoPay,
    Efecty,
    Eps,
    EuBankTransfer,
    Fpx,
    FlexPay,
    GbBankTransfer,
    Gcash,
    Giropay,
    GooglePay,
    Gopay,
    Grabpay,
    IdBankTransfer,
    Ideal,
    Interac,
    KakaoPay,
    Klarna,
    KlarnaPayNow,
    Konbini,
    KrCard,
    KrMarket,
    Kriya,
    Kueski,
    Link,
    MbWay,
    MPesa,
    MercadoPago,
    Mobilepay,
    Modo,
    Mondu,
    Multibanco,
    NaverPay,
    Nequi,
    Netbanking,
    NgBank,
    NgBankTransfer,
    NgCard,
    NgMarket,
    NgUssd,
    NgWallet,
    NzBankAccount,
    Oxxo,
    P24,
    PagoEfectivo,
    Pse,
    PayByBank,
    Payco,
    Paynow,
    Paypal,
    Paypay,
    Payto,
    Pix,
    PlatformBalance,
    Promptpay,
    Qris,
    Rapipago,
    Rechnung,
    RevolutPay,
    SamsungPay,
    Satispay,
    Scalapay,
    Sencillito,
    SepaDebit,
    Sequra,
    Servipag,
    Sezzle,
    ShopPay,
    Shopeepay,
    Sofort,
    SouthKoreaMarket,
    Spei,
    Splitit,
    Sunbit,
    Swish,
    Tamara,
    Twint,
    Upi,
    UsBankAccount,
    UsBankTransfer,
    Venmo,
    Vipps,
    Webpay,
    WechatPay,
    Yape,
    Zip,
    Coinflow,
    Unknown,
    /// This variant is used for forward compatibility.
    /// If the server sends a value not recognized by the current SDK version,
    /// it will be captured here with the raw string value.
    __Unknown(String),
}
impl Serialize for PaymentMethodTypes {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        match self {
            Self::AcssDebit => serializer.serialize_str("acss_debit"),
            Self::Addi => serializer.serialize_str("addi"),
            Self::Affirm => serializer.serialize_str("affirm"),
            Self::AfterpayClearpay => serializer.serialize_str("afterpay_clearpay"),
            Self::Alipay => serializer.serialize_str("alipay"),
            Self::Alma => serializer.serialize_str("alma"),
            Self::AmazonPay => serializer.serialize_str("amazon_pay"),
            Self::Apple => serializer.serialize_str("apple"),
            Self::ApplePay => serializer.serialize_str("apple_pay"),
            Self::AuBankTransfer => serializer.serialize_str("au_bank_transfer"),
            Self::AuBecsDebit => serializer.serialize_str("au_becs_debit"),
            Self::BacsDebit => serializer.serialize_str("bacs_debit"),
            Self::Bancolombia => serializer.serialize_str("bancolombia"),
            Self::Bancontact => serializer.serialize_str("bancontact"),
            Self::BankWire => serializer.serialize_str("bank_wire"),
            Self::Billie => serializer.serialize_str("billie"),
            Self::Bizum => serializer.serialize_str("bizum"),
            Self::Blik => serializer.serialize_str("blik"),
            Self::Boleto => serializer.serialize_str("boleto"),
            Self::BreB => serializer.serialize_str("bre_b"),
            Self::CaBankTransfer => serializer.serialize_str("ca_bank_transfer"),
            Self::CapchasePay => serializer.serialize_str("capchase_pay"),
            Self::Card => serializer.serialize_str("card"),
            Self::CardInstallmentsThree => serializer.serialize_str("card_installments_three"),
            Self::CardInstallmentsSix => serializer.serialize_str("card_installments_six"),
            Self::CardInstallmentsTwelve => serializer.serialize_str("card_installments_twelve"),
            Self::Cashapp => serializer.serialize_str("cashapp"),
            Self::Claritypay => serializer.serialize_str("claritypay"),
            Self::Coinbase => serializer.serialize_str("coinbase"),
            Self::Crypto => serializer.serialize_str("crypto"),
            Self::Custom => serializer.serialize_str("custom"),
            Self::CustomerBalance => serializer.serialize_str("customer_balance"),
            Self::DemoPay => serializer.serialize_str("demo_pay"),
            Self::Efecty => serializer.serialize_str("efecty"),
            Self::Eps => serializer.serialize_str("eps"),
            Self::EuBankTransfer => serializer.serialize_str("eu_bank_transfer"),
            Self::Fpx => serializer.serialize_str("fpx"),
            Self::FlexPay => serializer.serialize_str("flex_pay"),
            Self::GbBankTransfer => serializer.serialize_str("gb_bank_transfer"),
            Self::Gcash => serializer.serialize_str("gcash"),
            Self::Giropay => serializer.serialize_str("giropay"),
            Self::GooglePay => serializer.serialize_str("google_pay"),
            Self::Gopay => serializer.serialize_str("gopay"),
            Self::Grabpay => serializer.serialize_str("grabpay"),
            Self::IdBankTransfer => serializer.serialize_str("id_bank_transfer"),
            Self::Ideal => serializer.serialize_str("ideal"),
            Self::Interac => serializer.serialize_str("interac"),
            Self::KakaoPay => serializer.serialize_str("kakao_pay"),
            Self::Klarna => serializer.serialize_str("klarna"),
            Self::KlarnaPayNow => serializer.serialize_str("klarna_pay_now"),
            Self::Konbini => serializer.serialize_str("konbini"),
            Self::KrCard => serializer.serialize_str("kr_card"),
            Self::KrMarket => serializer.serialize_str("kr_market"),
            Self::Kriya => serializer.serialize_str("kriya"),
            Self::Kueski => serializer.serialize_str("kueski"),
            Self::Link => serializer.serialize_str("link"),
            Self::MbWay => serializer.serialize_str("mb_way"),
            Self::MPesa => serializer.serialize_str("m_pesa"),
            Self::MercadoPago => serializer.serialize_str("mercado_pago"),
            Self::Mobilepay => serializer.serialize_str("mobilepay"),
            Self::Modo => serializer.serialize_str("modo"),
            Self::Mondu => serializer.serialize_str("mondu"),
            Self::Multibanco => serializer.serialize_str("multibanco"),
            Self::NaverPay => serializer.serialize_str("naver_pay"),
            Self::Nequi => serializer.serialize_str("nequi"),
            Self::Netbanking => serializer.serialize_str("netbanking"),
            Self::NgBank => serializer.serialize_str("ng_bank"),
            Self::NgBankTransfer => serializer.serialize_str("ng_bank_transfer"),
            Self::NgCard => serializer.serialize_str("ng_card"),
            Self::NgMarket => serializer.serialize_str("ng_market"),
            Self::NgUssd => serializer.serialize_str("ng_ussd"),
            Self::NgWallet => serializer.serialize_str("ng_wallet"),
            Self::NzBankAccount => serializer.serialize_str("nz_bank_account"),
            Self::Oxxo => serializer.serialize_str("oxxo"),
            Self::P24 => serializer.serialize_str("p24"),
            Self::PagoEfectivo => serializer.serialize_str("pago_efectivo"),
            Self::Pse => serializer.serialize_str("pse"),
            Self::PayByBank => serializer.serialize_str("pay_by_bank"),
            Self::Payco => serializer.serialize_str("payco"),
            Self::Paynow => serializer.serialize_str("paynow"),
            Self::Paypal => serializer.serialize_str("paypal"),
            Self::Paypay => serializer.serialize_str("paypay"),
            Self::Payto => serializer.serialize_str("payto"),
            Self::Pix => serializer.serialize_str("pix"),
            Self::PlatformBalance => serializer.serialize_str("platform_balance"),
            Self::Promptpay => serializer.serialize_str("promptpay"),
            Self::Qris => serializer.serialize_str("qris"),
            Self::Rapipago => serializer.serialize_str("rapipago"),
            Self::Rechnung => serializer.serialize_str("rechnung"),
            Self::RevolutPay => serializer.serialize_str("revolut_pay"),
            Self::SamsungPay => serializer.serialize_str("samsung_pay"),
            Self::Satispay => serializer.serialize_str("satispay"),
            Self::Scalapay => serializer.serialize_str("scalapay"),
            Self::Sencillito => serializer.serialize_str("sencillito"),
            Self::SepaDebit => serializer.serialize_str("sepa_debit"),
            Self::Sequra => serializer.serialize_str("sequra"),
            Self::Servipag => serializer.serialize_str("servipag"),
            Self::Sezzle => serializer.serialize_str("sezzle"),
            Self::ShopPay => serializer.serialize_str("shop_pay"),
            Self::Shopeepay => serializer.serialize_str("shopeepay"),
            Self::Sofort => serializer.serialize_str("sofort"),
            Self::SouthKoreaMarket => serializer.serialize_str("south_korea_market"),
            Self::Spei => serializer.serialize_str("spei"),
            Self::Splitit => serializer.serialize_str("splitit"),
            Self::Sunbit => serializer.serialize_str("sunbit"),
            Self::Swish => serializer.serialize_str("swish"),
            Self::Tamara => serializer.serialize_str("tamara"),
            Self::Twint => serializer.serialize_str("twint"),
            Self::Upi => serializer.serialize_str("upi"),
            Self::UsBankAccount => serializer.serialize_str("us_bank_account"),
            Self::UsBankTransfer => serializer.serialize_str("us_bank_transfer"),
            Self::Venmo => serializer.serialize_str("venmo"),
            Self::Vipps => serializer.serialize_str("vipps"),
            Self::Webpay => serializer.serialize_str("webpay"),
            Self::WechatPay => serializer.serialize_str("wechat_pay"),
            Self::Yape => serializer.serialize_str("yape"),
            Self::Zip => serializer.serialize_str("zip"),
            Self::Coinflow => serializer.serialize_str("coinflow"),
            Self::Unknown => serializer.serialize_str("unknown"),
            Self::__Unknown(val) => serializer.serialize_str(val),
        }
    }
}

impl<'de> Deserialize<'de> for PaymentMethodTypes {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        match value.as_str() {
            "acss_debit" => Ok(Self::AcssDebit),
            "addi" => Ok(Self::Addi),
            "affirm" => Ok(Self::Affirm),
            "afterpay_clearpay" => Ok(Self::AfterpayClearpay),
            "alipay" => Ok(Self::Alipay),
            "alma" => Ok(Self::Alma),
            "amazon_pay" => Ok(Self::AmazonPay),
            "apple" => Ok(Self::Apple),
            "apple_pay" => Ok(Self::ApplePay),
            "au_bank_transfer" => Ok(Self::AuBankTransfer),
            "au_becs_debit" => Ok(Self::AuBecsDebit),
            "bacs_debit" => Ok(Self::BacsDebit),
            "bancolombia" => Ok(Self::Bancolombia),
            "bancontact" => Ok(Self::Bancontact),
            "bank_wire" => Ok(Self::BankWire),
            "billie" => Ok(Self::Billie),
            "bizum" => Ok(Self::Bizum),
            "blik" => Ok(Self::Blik),
            "boleto" => Ok(Self::Boleto),
            "bre_b" => Ok(Self::BreB),
            "ca_bank_transfer" => Ok(Self::CaBankTransfer),
            "capchase_pay" => Ok(Self::CapchasePay),
            "card" => Ok(Self::Card),
            "card_installments_three" => Ok(Self::CardInstallmentsThree),
            "card_installments_six" => Ok(Self::CardInstallmentsSix),
            "card_installments_twelve" => Ok(Self::CardInstallmentsTwelve),
            "cashapp" => Ok(Self::Cashapp),
            "claritypay" => Ok(Self::Claritypay),
            "coinbase" => Ok(Self::Coinbase),
            "crypto" => Ok(Self::Crypto),
            "custom" => Ok(Self::Custom),
            "customer_balance" => Ok(Self::CustomerBalance),
            "demo_pay" => Ok(Self::DemoPay),
            "efecty" => Ok(Self::Efecty),
            "eps" => Ok(Self::Eps),
            "eu_bank_transfer" => Ok(Self::EuBankTransfer),
            "fpx" => Ok(Self::Fpx),
            "flex_pay" => Ok(Self::FlexPay),
            "gb_bank_transfer" => Ok(Self::GbBankTransfer),
            "gcash" => Ok(Self::Gcash),
            "giropay" => Ok(Self::Giropay),
            "google_pay" => Ok(Self::GooglePay),
            "gopay" => Ok(Self::Gopay),
            "grabpay" => Ok(Self::Grabpay),
            "id_bank_transfer" => Ok(Self::IdBankTransfer),
            "ideal" => Ok(Self::Ideal),
            "interac" => Ok(Self::Interac),
            "kakao_pay" => Ok(Self::KakaoPay),
            "klarna" => Ok(Self::Klarna),
            "klarna_pay_now" => Ok(Self::KlarnaPayNow),
            "konbini" => Ok(Self::Konbini),
            "kr_card" => Ok(Self::KrCard),
            "kr_market" => Ok(Self::KrMarket),
            "kriya" => Ok(Self::Kriya),
            "kueski" => Ok(Self::Kueski),
            "link" => Ok(Self::Link),
            "mb_way" => Ok(Self::MbWay),
            "m_pesa" => Ok(Self::MPesa),
            "mercado_pago" => Ok(Self::MercadoPago),
            "mobilepay" => Ok(Self::Mobilepay),
            "modo" => Ok(Self::Modo),
            "mondu" => Ok(Self::Mondu),
            "multibanco" => Ok(Self::Multibanco),
            "naver_pay" => Ok(Self::NaverPay),
            "nequi" => Ok(Self::Nequi),
            "netbanking" => Ok(Self::Netbanking),
            "ng_bank" => Ok(Self::NgBank),
            "ng_bank_transfer" => Ok(Self::NgBankTransfer),
            "ng_card" => Ok(Self::NgCard),
            "ng_market" => Ok(Self::NgMarket),
            "ng_ussd" => Ok(Self::NgUssd),
            "ng_wallet" => Ok(Self::NgWallet),
            "nz_bank_account" => Ok(Self::NzBankAccount),
            "oxxo" => Ok(Self::Oxxo),
            "p24" => Ok(Self::P24),
            "pago_efectivo" => Ok(Self::PagoEfectivo),
            "pse" => Ok(Self::Pse),
            "pay_by_bank" => Ok(Self::PayByBank),
            "payco" => Ok(Self::Payco),
            "paynow" => Ok(Self::Paynow),
            "paypal" => Ok(Self::Paypal),
            "paypay" => Ok(Self::Paypay),
            "payto" => Ok(Self::Payto),
            "pix" => Ok(Self::Pix),
            "platform_balance" => Ok(Self::PlatformBalance),
            "promptpay" => Ok(Self::Promptpay),
            "qris" => Ok(Self::Qris),
            "rapipago" => Ok(Self::Rapipago),
            "rechnung" => Ok(Self::Rechnung),
            "revolut_pay" => Ok(Self::RevolutPay),
            "samsung_pay" => Ok(Self::SamsungPay),
            "satispay" => Ok(Self::Satispay),
            "scalapay" => Ok(Self::Scalapay),
            "sencillito" => Ok(Self::Sencillito),
            "sepa_debit" => Ok(Self::SepaDebit),
            "sequra" => Ok(Self::Sequra),
            "servipag" => Ok(Self::Servipag),
            "sezzle" => Ok(Self::Sezzle),
            "shop_pay" => Ok(Self::ShopPay),
            "shopeepay" => Ok(Self::Shopeepay),
            "sofort" => Ok(Self::Sofort),
            "south_korea_market" => Ok(Self::SouthKoreaMarket),
            "spei" => Ok(Self::Spei),
            "splitit" => Ok(Self::Splitit),
            "sunbit" => Ok(Self::Sunbit),
            "swish" => Ok(Self::Swish),
            "tamara" => Ok(Self::Tamara),
            "twint" => Ok(Self::Twint),
            "upi" => Ok(Self::Upi),
            "us_bank_account" => Ok(Self::UsBankAccount),
            "us_bank_transfer" => Ok(Self::UsBankTransfer),
            "venmo" => Ok(Self::Venmo),
            "vipps" => Ok(Self::Vipps),
            "webpay" => Ok(Self::Webpay),
            "wechat_pay" => Ok(Self::WechatPay),
            "yape" => Ok(Self::Yape),
            "zip" => Ok(Self::Zip),
            "coinflow" => Ok(Self::Coinflow),
            "unknown" => Ok(Self::Unknown),
            _ => Ok(Self::__Unknown(value)),
        }
    }
}

impl fmt::Display for PaymentMethodTypes {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::AcssDebit => write!(f, "acss_debit"),
            Self::Addi => write!(f, "addi"),
            Self::Affirm => write!(f, "affirm"),
            Self::AfterpayClearpay => write!(f, "afterpay_clearpay"),
            Self::Alipay => write!(f, "alipay"),
            Self::Alma => write!(f, "alma"),
            Self::AmazonPay => write!(f, "amazon_pay"),
            Self::Apple => write!(f, "apple"),
            Self::ApplePay => write!(f, "apple_pay"),
            Self::AuBankTransfer => write!(f, "au_bank_transfer"),
            Self::AuBecsDebit => write!(f, "au_becs_debit"),
            Self::BacsDebit => write!(f, "bacs_debit"),
            Self::Bancolombia => write!(f, "bancolombia"),
            Self::Bancontact => write!(f, "bancontact"),
            Self::BankWire => write!(f, "bank_wire"),
            Self::Billie => write!(f, "billie"),
            Self::Bizum => write!(f, "bizum"),
            Self::Blik => write!(f, "blik"),
            Self::Boleto => write!(f, "boleto"),
            Self::BreB => write!(f, "bre_b"),
            Self::CaBankTransfer => write!(f, "ca_bank_transfer"),
            Self::CapchasePay => write!(f, "capchase_pay"),
            Self::Card => write!(f, "card"),
            Self::CardInstallmentsThree => write!(f, "card_installments_three"),
            Self::CardInstallmentsSix => write!(f, "card_installments_six"),
            Self::CardInstallmentsTwelve => write!(f, "card_installments_twelve"),
            Self::Cashapp => write!(f, "cashapp"),
            Self::Claritypay => write!(f, "claritypay"),
            Self::Coinbase => write!(f, "coinbase"),
            Self::Crypto => write!(f, "crypto"),
            Self::Custom => write!(f, "custom"),
            Self::CustomerBalance => write!(f, "customer_balance"),
            Self::DemoPay => write!(f, "demo_pay"),
            Self::Efecty => write!(f, "efecty"),
            Self::Eps => write!(f, "eps"),
            Self::EuBankTransfer => write!(f, "eu_bank_transfer"),
            Self::Fpx => write!(f, "fpx"),
            Self::FlexPay => write!(f, "flex_pay"),
            Self::GbBankTransfer => write!(f, "gb_bank_transfer"),
            Self::Gcash => write!(f, "gcash"),
            Self::Giropay => write!(f, "giropay"),
            Self::GooglePay => write!(f, "google_pay"),
            Self::Gopay => write!(f, "gopay"),
            Self::Grabpay => write!(f, "grabpay"),
            Self::IdBankTransfer => write!(f, "id_bank_transfer"),
            Self::Ideal => write!(f, "ideal"),
            Self::Interac => write!(f, "interac"),
            Self::KakaoPay => write!(f, "kakao_pay"),
            Self::Klarna => write!(f, "klarna"),
            Self::KlarnaPayNow => write!(f, "klarna_pay_now"),
            Self::Konbini => write!(f, "konbini"),
            Self::KrCard => write!(f, "kr_card"),
            Self::KrMarket => write!(f, "kr_market"),
            Self::Kriya => write!(f, "kriya"),
            Self::Kueski => write!(f, "kueski"),
            Self::Link => write!(f, "link"),
            Self::MbWay => write!(f, "mb_way"),
            Self::MPesa => write!(f, "m_pesa"),
            Self::MercadoPago => write!(f, "mercado_pago"),
            Self::Mobilepay => write!(f, "mobilepay"),
            Self::Modo => write!(f, "modo"),
            Self::Mondu => write!(f, "mondu"),
            Self::Multibanco => write!(f, "multibanco"),
            Self::NaverPay => write!(f, "naver_pay"),
            Self::Nequi => write!(f, "nequi"),
            Self::Netbanking => write!(f, "netbanking"),
            Self::NgBank => write!(f, "ng_bank"),
            Self::NgBankTransfer => write!(f, "ng_bank_transfer"),
            Self::NgCard => write!(f, "ng_card"),
            Self::NgMarket => write!(f, "ng_market"),
            Self::NgUssd => write!(f, "ng_ussd"),
            Self::NgWallet => write!(f, "ng_wallet"),
            Self::NzBankAccount => write!(f, "nz_bank_account"),
            Self::Oxxo => write!(f, "oxxo"),
            Self::P24 => write!(f, "p24"),
            Self::PagoEfectivo => write!(f, "pago_efectivo"),
            Self::Pse => write!(f, "pse"),
            Self::PayByBank => write!(f, "pay_by_bank"),
            Self::Payco => write!(f, "payco"),
            Self::Paynow => write!(f, "paynow"),
            Self::Paypal => write!(f, "paypal"),
            Self::Paypay => write!(f, "paypay"),
            Self::Payto => write!(f, "payto"),
            Self::Pix => write!(f, "pix"),
            Self::PlatformBalance => write!(f, "platform_balance"),
            Self::Promptpay => write!(f, "promptpay"),
            Self::Qris => write!(f, "qris"),
            Self::Rapipago => write!(f, "rapipago"),
            Self::Rechnung => write!(f, "rechnung"),
            Self::RevolutPay => write!(f, "revolut_pay"),
            Self::SamsungPay => write!(f, "samsung_pay"),
            Self::Satispay => write!(f, "satispay"),
            Self::Scalapay => write!(f, "scalapay"),
            Self::Sencillito => write!(f, "sencillito"),
            Self::SepaDebit => write!(f, "sepa_debit"),
            Self::Sequra => write!(f, "sequra"),
            Self::Servipag => write!(f, "servipag"),
            Self::Sezzle => write!(f, "sezzle"),
            Self::ShopPay => write!(f, "shop_pay"),
            Self::Shopeepay => write!(f, "shopeepay"),
            Self::Sofort => write!(f, "sofort"),
            Self::SouthKoreaMarket => write!(f, "south_korea_market"),
            Self::Spei => write!(f, "spei"),
            Self::Splitit => write!(f, "splitit"),
            Self::Sunbit => write!(f, "sunbit"),
            Self::Swish => write!(f, "swish"),
            Self::Tamara => write!(f, "tamara"),
            Self::Twint => write!(f, "twint"),
            Self::Upi => write!(f, "upi"),
            Self::UsBankAccount => write!(f, "us_bank_account"),
            Self::UsBankTransfer => write!(f, "us_bank_transfer"),
            Self::Venmo => write!(f, "venmo"),
            Self::Vipps => write!(f, "vipps"),
            Self::Webpay => write!(f, "webpay"),
            Self::WechatPay => write!(f, "wechat_pay"),
            Self::Yape => write!(f, "yape"),
            Self::Zip => write!(f, "zip"),
            Self::Coinflow => write!(f, "coinflow"),
            Self::Unknown => write!(f, "unknown"),
            Self::__Unknown(val) => write!(f, "{}", val),
        }
    }
}
