pub use crate::prelude::*;

/// A permission action identifier, such as `company:basic:read`.
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum PermissionAction {
    AiPromptCreate,
    AccessPassBasicExport,
    AccessPassBasicRead,
    AccessPassControlCenter,
    AccessPassCreate,
    AccessPassDelete,
    AccessPassStatsExport,
    AccessPassStatsRead,
    AccessPassUpdate,
    AdCampaignBasicExport,
    AdCampaignBasicRead,
    AdCampaignConversionCreate,
    AdCampaignCreate,
    AdCampaignCreditCreate,
    AdCampaignDelete,
    AdCampaignRead,
    AdCampaignStatsRead,
    AdCampaignUpdate,
    AudienceBasicRead,
    AudienceUpdate,
    AdPublisherRead,
    AffiliateBasicRead,
    AffiliateCreate,
    AffiliateUpdate,
    AuthorizedUserCreate,
    AuthorizedUserDelete,
    AuthorizedUserUpdate,
    AuthorizedRoleCreate,
    AuthorizedRoleUpdate,
    AuthorizedRoleDelete,
    AuthorizedRoleAttach,
    AuthorizedRoleDetach,
    AppAuthorizationCreate,
    AppAuthorizationRead,
    AppAuthorizationUpdate,
    AppAuthorizationDelete,
    BountyBasicRead,
    BountyCreate,
    BountyCaptureClipCreate,
    BountyCaptureClipComplete,
    BountyCaptureClipDiscard,
    BountyUpdate,
    BountySubmissionCreate,
    BountySubmissionDelete,
    BountySubmissionVote,
    ChatManageWebhook,
    ChatModerate,
    ChatMessageCreate,
    ChatRead,
    DmsRead,
    DmsMessageManage,
    DmsChannelManage,
    ForumPostCreate,
    ForumRead,
    ForumModerate,
    CompanyAuthorizedUserRead,
    CompanyAuthorizedUserEmailRead,
    CompanyBalanceRead,
    CompanyBalanceExport,
    CompanyTokenTransactionRead,
    CompanyTokenTransactionCreate,
    CompanyLogRead,
    CompanyManageCheckout,
    CompanyManageLegal,
    CompanyBasicRead,
    CompanyUpdate,
    CompanyTransferOwnership,
    CompanyCreate,
    CompanyCreateChild,
    CompanyDelete,
    CompanyDeleteChild,
    CompanyUpdateChildFees,
    ChildCompanyBasicExport,
    SocialAccountCreate,
    SocialAccountDelete,
    SocialAccountRead,
    SocialLinkUpdate,
    CustomEmojiUpdate,
    ContentRewardsBasicExport,
    ContentRewardsBasicRead,
    ContentRewardsCreate,
    ContentRewardsDelete,
    ContentRewardsModerateSubmission,
    ContentRewardsUpdate,
    DeveloperBasicRead,
    DeveloperCreateApp,
    DeveloperManageApiKey,
    DeveloperManageOauth,
    DeveloperManageWebhook,
    DeveloperLogsRead,
    DeveloperManageBuilds,
    DeveloperUpdateApp,
    DeveloperUpdateAppAuthorization,
    EventCreate,
    ExperienceAttach,
    ExperienceCreate,
    ExperienceDelete,
    ExperienceDetach,
    ExperienceHiddenExperienceRead,
    ExperienceUpdate,
    IapRead,
    IdentityRead,
    IdentityWrite,
    IncorporationRead,
    IncorporationWrite,
    LivestreamCreate,
    LivestreamDelete,
    LivestreamManageRecording,
    LivestreamChatRead,
    LivestreamChatWrite,
    LivestreamModerate,
    MediaGenerate,
    MediaRead,
    MemberBasicExport,
    MemberBasicRead,
    MemberEmailRead,
    MemberPhoneRead,
    MemberPaymentMethodsRead,
    MemberPaymentMethodsUse,
    MemberPaymentMethodsManage,
    MemberManage,
    MembershipCancel,
    MembershipResyncAccess,
    MembershipCreate,
    MembershipUpdate,
    MembershipTransfer,
    MemberModerate,
    MemberStatsExport,
    MemberStatsRead,
    MemberJourneyRead,
    PaymentBasicExport,
    PaymentBasicRead,
    PaymentCharge,
    PaymentDispute,
    PaymentDisputeExport,
    PaymentDisputeRead,
    PaymentDisputeAlertRead,
    PaymentSetupIntentRead,
    PaymentSetupIntentManage,
    PaymentManage,
    PaymentResolutionCenter,
    PaymentResolutionCenterCaseExport,
    PaymentResolutionCenterCaseRead,
    PaymentResolutionCenterCaseManage,
    PayoutCreateDestination,
    PayoutDeleteDestination,
    PayoutDestinationRead,
    PayoutTransferFunds,
    PayoutTransferRead,
    PayoutTransferExport,
    PayoutUpdateDestination,
    PayoutWithdrawFunds,
    PayoutWithdrawalRead,
    PayoutWithdrawalExport,
    PayoutAccountRead,
    PayoutAccountUpdate,
    PlanBasicExport,
    PlanBasicRead,
    PlanCreate,
    PlanDelete,
    PlanStatsExport,
    PlanStatsRead,
    PlanUpdate,
    PlanWaitlistManage,
    PlanWaitlistExport,
    PlanWaitlistRead,
    PromoCodeBasicExport,
    PromoCodeBasicRead,
    PromoCodeCreate,
    PromoCodeDelete,
    PromoCodeUpdate,
    ReferralBasicRead,
    ReferralPartnerCreate,
    PartnerBasicRead,
    PartnerInviteCreate,
    PartnerCreate,
    StatsRead,
    SupportChatRead,
    SupportChatCreate,
    SupportChatMessageCreate,
    TrackingLinkBasicExport,
    TrackingLinkBasicRead,
    TrackingLinkCreate,
    TrackingLinkDelete,
    TrackingLinkStatsExport,
    TrackingLinkStatsRead,
    TrackingLinkUpdate,
    CoursesRead,
    CoursesUpdate,
    CourseLessonInteractionRead,
    CourseAnalyticsRead,
    LeadBasicRead,
    LeadBasicExport,
    InvoiceCreate,
    InvoiceBasicRead,
    InvoiceBasicExport,
    InvoiceUpdate,
    WebhookReceiveInvoices,
    WebhookReceiveSetupIntents,
    WebhookReceiveWithdrawals,
    WebhookReceiveSwaps,
    WebhookReceiveLedgerAccounts,
    WebhookReceiveAccounts,
    WebhookReceiveDeposits,
    WebhookReceiveTransfers,
    WebhookReceiveCardTransactions,
    WebhookReceiveCards,
    WebhookReceiveCardApplications,
    WebhookReceivePayoutMethods,
    WebhookReceiveVerifications,
    WebhookReceiveIdentityProfiles,
    WebhookReceivePayoutAccounts,
    WebhookReceiveChat,
    WebhookReceiveEntries,
    WebhookReceiveAdCampaigns,
    WebhookReceiveProducts,
    WebhookReceivePlans,
    WebhookReceiveShipments,
    WebhookReceiveMembers,
    WebhookReceiveExports,
    WebhookReceiveCourses,
    WebhookReceiveMemberships,
    WebhookReceivePayments,
    WebhookReceiveRefunds,
    WebhookReceiveDisputes,
    WebhookReceiveResolutions,
    WebhookReceiveAppPayments,
    WebhookReceiveAppMemberships,
    ShipmentCreate,
    ShipmentBasicRead,
    CheckoutConfigurationBasicRead,
    CheckoutConfigurationCreate,
    CheckoutConfigurationDelete,
    CheckoutRequestCreate,
    CheckoutRequestBasicRead,
    CryptoWalletManage,
    CryptoWalletSwap,
    AirdropLinkBasicRead,
    AirdropLinkManage,
    LeadManage,
    NotificationCreate,
    UserBalanceRead,
    UserEmailRead,
    UserStaffRead,
    OauthTokenExchange,
    Openid,
    Profile,
    Email,
    AiChatRead,
    AiChatCreate,
    AiChatDelete,
    AiChatUpdate,
    UserNotificationsRead,
    UserNotificationsUpdate,
    UserProfileUpdate,
    /// This variant is used for forward compatibility.
    /// If the server sends a value not recognized by the current SDK version,
    /// it will be captured here with the raw string value.
    __Unknown(String),
}
impl Serialize for PermissionAction {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        match self {
            Self::AiPromptCreate => serializer.serialize_str("ai_prompt:create"),
            Self::AccessPassBasicExport => serializer.serialize_str("access_pass:basic:export"),
            Self::AccessPassBasicRead => serializer.serialize_str("access_pass:basic:read"),
            Self::AccessPassControlCenter => serializer.serialize_str("access_pass:control_center"),
            Self::AccessPassCreate => serializer.serialize_str("access_pass:create"),
            Self::AccessPassDelete => serializer.serialize_str("access_pass:delete"),
            Self::AccessPassStatsExport => serializer.serialize_str("access_pass:stats:export"),
            Self::AccessPassStatsRead => serializer.serialize_str("access_pass:stats:read"),
            Self::AccessPassUpdate => serializer.serialize_str("access_pass:update"),
            Self::AdCampaignBasicExport => serializer.serialize_str("ad_campaign:basic:export"),
            Self::AdCampaignBasicRead => serializer.serialize_str("ad_campaign:basic:read"),
            Self::AdCampaignConversionCreate => {
                serializer.serialize_str("ad_campaign:conversion:create")
            }
            Self::AdCampaignCreate => serializer.serialize_str("ad_campaign:create"),
            Self::AdCampaignCreditCreate => serializer.serialize_str("ad_campaign:credit:create"),
            Self::AdCampaignDelete => serializer.serialize_str("ad_campaign:delete"),
            Self::AdCampaignRead => serializer.serialize_str("ad_campaign:read"),
            Self::AdCampaignStatsRead => serializer.serialize_str("ad_campaign:stats:read"),
            Self::AdCampaignUpdate => serializer.serialize_str("ad_campaign:update"),
            Self::AudienceBasicRead => serializer.serialize_str("audience:basic:read"),
            Self::AudienceUpdate => serializer.serialize_str("audience:update"),
            Self::AdPublisherRead => serializer.serialize_str("ad_publisher:read"),
            Self::AffiliateBasicRead => serializer.serialize_str("affiliate:basic:read"),
            Self::AffiliateCreate => serializer.serialize_str("affiliate:create"),
            Self::AffiliateUpdate => serializer.serialize_str("affiliate:update"),
            Self::AuthorizedUserCreate => serializer.serialize_str("authorized_user:create"),
            Self::AuthorizedUserDelete => serializer.serialize_str("authorized_user:delete"),
            Self::AuthorizedUserUpdate => serializer.serialize_str("authorized_user:update"),
            Self::AuthorizedRoleCreate => serializer.serialize_str("authorized_role:create"),
            Self::AuthorizedRoleUpdate => serializer.serialize_str("authorized_role:update"),
            Self::AuthorizedRoleDelete => serializer.serialize_str("authorized_role:delete"),
            Self::AuthorizedRoleAttach => serializer.serialize_str("authorized_role:attach"),
            Self::AuthorizedRoleDetach => serializer.serialize_str("authorized_role:detach"),
            Self::AppAuthorizationCreate => serializer.serialize_str("app_authorization:create"),
            Self::AppAuthorizationRead => serializer.serialize_str("app_authorization:read"),
            Self::AppAuthorizationUpdate => serializer.serialize_str("app_authorization:update"),
            Self::AppAuthorizationDelete => serializer.serialize_str("app_authorization:delete"),
            Self::BountyBasicRead => serializer.serialize_str("bounty:basic:read"),
            Self::BountyCreate => serializer.serialize_str("bounty:create"),
            Self::BountyCaptureClipCreate => serializer.serialize_str("bounty:capture_clip:create"),
            Self::BountyCaptureClipComplete => {
                serializer.serialize_str("bounty:capture_clip:complete")
            }
            Self::BountyCaptureClipDiscard => {
                serializer.serialize_str("bounty:capture_clip:discard")
            }
            Self::BountyUpdate => serializer.serialize_str("bounty:update"),
            Self::BountySubmissionCreate => serializer.serialize_str("bounty:submission:create"),
            Self::BountySubmissionDelete => serializer.serialize_str("bounty:submission:delete"),
            Self::BountySubmissionVote => serializer.serialize_str("bounty:submission:vote"),
            Self::ChatManageWebhook => serializer.serialize_str("chat:manage_webhook"),
            Self::ChatModerate => serializer.serialize_str("chat:moderate"),
            Self::ChatMessageCreate => serializer.serialize_str("chat:message:create"),
            Self::ChatRead => serializer.serialize_str("chat:read"),
            Self::DmsRead => serializer.serialize_str("dms:read"),
            Self::DmsMessageManage => serializer.serialize_str("dms:message:manage"),
            Self::DmsChannelManage => serializer.serialize_str("dms:channel:manage"),
            Self::ForumPostCreate => serializer.serialize_str("forum:post:create"),
            Self::ForumRead => serializer.serialize_str("forum:read"),
            Self::ForumModerate => serializer.serialize_str("forum:moderate"),
            Self::CompanyAuthorizedUserRead => {
                serializer.serialize_str("company:authorized_user:read")
            }
            Self::CompanyAuthorizedUserEmailRead => {
                serializer.serialize_str("company:authorized_user:email:read")
            }
            Self::CompanyBalanceRead => serializer.serialize_str("company:balance:read"),
            Self::CompanyBalanceExport => serializer.serialize_str("company:balance:export"),
            Self::CompanyTokenTransactionRead => {
                serializer.serialize_str("company_token_transaction:read")
            }
            Self::CompanyTokenTransactionCreate => {
                serializer.serialize_str("company_token_transaction:create")
            }
            Self::CompanyLogRead => serializer.serialize_str("company:log:read"),
            Self::CompanyManageCheckout => serializer.serialize_str("company:manage_checkout"),
            Self::CompanyManageLegal => serializer.serialize_str("company:manage_legal"),
            Self::CompanyBasicRead => serializer.serialize_str("company:basic:read"),
            Self::CompanyUpdate => serializer.serialize_str("company:update"),
            Self::CompanyTransferOwnership => {
                serializer.serialize_str("company:transfer_ownership")
            }
            Self::CompanyCreate => serializer.serialize_str("company:create"),
            Self::CompanyCreateChild => serializer.serialize_str("company:create_child"),
            Self::CompanyDelete => serializer.serialize_str("company:delete"),
            Self::CompanyDeleteChild => serializer.serialize_str("company:delete_child"),
            Self::CompanyUpdateChildFees => serializer.serialize_str("company:update_child_fees"),
            Self::ChildCompanyBasicExport => serializer.serialize_str("child_company:basic:export"),
            Self::SocialAccountCreate => serializer.serialize_str("social_account:create"),
            Self::SocialAccountDelete => serializer.serialize_str("social_account:delete"),
            Self::SocialAccountRead => serializer.serialize_str("social_account:read"),
            Self::SocialLinkUpdate => serializer.serialize_str("social_link:update"),
            Self::CustomEmojiUpdate => serializer.serialize_str("custom_emoji:update"),
            Self::ContentRewardsBasicExport => {
                serializer.serialize_str("content_rewards:basic:export")
            }
            Self::ContentRewardsBasicRead => serializer.serialize_str("content_rewards:basic:read"),
            Self::ContentRewardsCreate => serializer.serialize_str("content_rewards:create"),
            Self::ContentRewardsDelete => serializer.serialize_str("content_rewards:delete"),
            Self::ContentRewardsModerateSubmission => {
                serializer.serialize_str("content_rewards:moderate_submission")
            }
            Self::ContentRewardsUpdate => serializer.serialize_str("content_rewards:update"),
            Self::DeveloperBasicRead => serializer.serialize_str("developer:basic:read"),
            Self::DeveloperCreateApp => serializer.serialize_str("developer:create_app"),
            Self::DeveloperManageApiKey => serializer.serialize_str("developer:manage_api_key"),
            Self::DeveloperManageOauth => serializer.serialize_str("developer:manage_oauth"),
            Self::DeveloperManageWebhook => serializer.serialize_str("developer:manage_webhook"),
            Self::DeveloperLogsRead => serializer.serialize_str("developer:logs:read"),
            Self::DeveloperManageBuilds => serializer.serialize_str("developer:manage_builds"),
            Self::DeveloperUpdateApp => serializer.serialize_str("developer:update_app"),
            Self::DeveloperUpdateAppAuthorization => {
                serializer.serialize_str("developer:update_app_authorization")
            }
            Self::EventCreate => serializer.serialize_str("event:create"),
            Self::ExperienceAttach => serializer.serialize_str("experience:attach"),
            Self::ExperienceCreate => serializer.serialize_str("experience:create"),
            Self::ExperienceDelete => serializer.serialize_str("experience:delete"),
            Self::ExperienceDetach => serializer.serialize_str("experience:detach"),
            Self::ExperienceHiddenExperienceRead => {
                serializer.serialize_str("experience:hidden_experience:read")
            }
            Self::ExperienceUpdate => serializer.serialize_str("experience:update"),
            Self::IapRead => serializer.serialize_str("iap:read"),
            Self::IdentityRead => serializer.serialize_str("identity:read"),
            Self::IdentityWrite => serializer.serialize_str("identity:write"),
            Self::IncorporationRead => serializer.serialize_str("incorporation:read"),
            Self::IncorporationWrite => serializer.serialize_str("incorporation:write"),
            Self::LivestreamCreate => serializer.serialize_str("livestream:create"),
            Self::LivestreamDelete => serializer.serialize_str("livestream:delete"),
            Self::LivestreamManageRecording => {
                serializer.serialize_str("livestream:manage_recording")
            }
            Self::LivestreamChatRead => serializer.serialize_str("livestream:chat:read"),
            Self::LivestreamChatWrite => serializer.serialize_str("livestream:chat:write"),
            Self::LivestreamModerate => serializer.serialize_str("livestream:moderate"),
            Self::MediaGenerate => serializer.serialize_str("media:generate"),
            Self::MediaRead => serializer.serialize_str("media:read"),
            Self::MemberBasicExport => serializer.serialize_str("member:basic:export"),
            Self::MemberBasicRead => serializer.serialize_str("member:basic:read"),
            Self::MemberEmailRead => serializer.serialize_str("member:email:read"),
            Self::MemberPhoneRead => serializer.serialize_str("member:phone:read"),
            Self::MemberPaymentMethodsRead => {
                serializer.serialize_str("member:payment_methods:read")
            }
            Self::MemberPaymentMethodsUse => serializer.serialize_str("member:payment_methods:use"),
            Self::MemberPaymentMethodsManage => {
                serializer.serialize_str("member:payment_methods:manage")
            }
            Self::MemberManage => serializer.serialize_str("member:manage"),
            Self::MembershipCancel => serializer.serialize_str("membership:cancel"),
            Self::MembershipResyncAccess => serializer.serialize_str("membership:resync_access"),
            Self::MembershipCreate => serializer.serialize_str("membership:create"),
            Self::MembershipUpdate => serializer.serialize_str("membership:update"),
            Self::MembershipTransfer => serializer.serialize_str("membership:transfer"),
            Self::MemberModerate => serializer.serialize_str("member:moderate"),
            Self::MemberStatsExport => serializer.serialize_str("member:stats:export"),
            Self::MemberStatsRead => serializer.serialize_str("member:stats:read"),
            Self::MemberJourneyRead => serializer.serialize_str("member:journey:read"),
            Self::PaymentBasicExport => serializer.serialize_str("payment:basic:export"),
            Self::PaymentBasicRead => serializer.serialize_str("payment:basic:read"),
            Self::PaymentCharge => serializer.serialize_str("payment:charge"),
            Self::PaymentDispute => serializer.serialize_str("payment:dispute"),
            Self::PaymentDisputeExport => serializer.serialize_str("payment:dispute:export"),
            Self::PaymentDisputeRead => serializer.serialize_str("payment:dispute:read"),
            Self::PaymentDisputeAlertRead => serializer.serialize_str("payment:dispute_alert:read"),
            Self::PaymentSetupIntentRead => serializer.serialize_str("payment:setup_intent:read"),
            Self::PaymentSetupIntentManage => {
                serializer.serialize_str("payment:setup_intent:manage")
            }
            Self::PaymentManage => serializer.serialize_str("payment:manage"),
            Self::PaymentResolutionCenter => serializer.serialize_str("payment:resolution_center"),
            Self::PaymentResolutionCenterCaseExport => {
                serializer.serialize_str("payment:resolution_center_case:export")
            }
            Self::PaymentResolutionCenterCaseRead => {
                serializer.serialize_str("payment:resolution_center_case:read")
            }
            Self::PaymentResolutionCenterCaseManage => {
                serializer.serialize_str("payment:resolution_center_case:manage")
            }
            Self::PayoutCreateDestination => serializer.serialize_str("payout:create_destination"),
            Self::PayoutDeleteDestination => serializer.serialize_str("payout:delete_destination"),
            Self::PayoutDestinationRead => serializer.serialize_str("payout:destination:read"),
            Self::PayoutTransferFunds => serializer.serialize_str("payout:transfer_funds"),
            Self::PayoutTransferRead => serializer.serialize_str("payout:transfer:read"),
            Self::PayoutTransferExport => serializer.serialize_str("payout:transfer:export"),
            Self::PayoutUpdateDestination => serializer.serialize_str("payout:update_destination"),
            Self::PayoutWithdrawFunds => serializer.serialize_str("payout:withdraw_funds"),
            Self::PayoutWithdrawalRead => serializer.serialize_str("payout:withdrawal:read"),
            Self::PayoutWithdrawalExport => serializer.serialize_str("payout:withdrawal:export"),
            Self::PayoutAccountRead => serializer.serialize_str("payout:account:read"),
            Self::PayoutAccountUpdate => serializer.serialize_str("payout:account:update"),
            Self::PlanBasicExport => serializer.serialize_str("plan:basic:export"),
            Self::PlanBasicRead => serializer.serialize_str("plan:basic:read"),
            Self::PlanCreate => serializer.serialize_str("plan:create"),
            Self::PlanDelete => serializer.serialize_str("plan:delete"),
            Self::PlanStatsExport => serializer.serialize_str("plan:stats:export"),
            Self::PlanStatsRead => serializer.serialize_str("plan:stats:read"),
            Self::PlanUpdate => serializer.serialize_str("plan:update"),
            Self::PlanWaitlistManage => serializer.serialize_str("plan:waitlist:manage"),
            Self::PlanWaitlistExport => serializer.serialize_str("plan:waitlist:export"),
            Self::PlanWaitlistRead => serializer.serialize_str("plan:waitlist:read"),
            Self::PromoCodeBasicExport => serializer.serialize_str("promo_code:basic:export"),
            Self::PromoCodeBasicRead => serializer.serialize_str("promo_code:basic:read"),
            Self::PromoCodeCreate => serializer.serialize_str("promo_code:create"),
            Self::PromoCodeDelete => serializer.serialize_str("promo_code:delete"),
            Self::PromoCodeUpdate => serializer.serialize_str("promo_code:update"),
            Self::ReferralBasicRead => serializer.serialize_str("referral:basic:read"),
            Self::ReferralPartnerCreate => serializer.serialize_str("referral:partner:create"),
            Self::PartnerBasicRead => serializer.serialize_str("partner:basic:read"),
            Self::PartnerInviteCreate => serializer.serialize_str("partner:invite:create"),
            Self::PartnerCreate => serializer.serialize_str("partner:create"),
            Self::StatsRead => serializer.serialize_str("stats:read"),
            Self::SupportChatRead => serializer.serialize_str("support_chat:read"),
            Self::SupportChatCreate => serializer.serialize_str("support_chat:create"),
            Self::SupportChatMessageCreate => {
                serializer.serialize_str("support_chat:message:create")
            }
            Self::TrackingLinkBasicExport => serializer.serialize_str("tracking_link:basic:export"),
            Self::TrackingLinkBasicRead => serializer.serialize_str("tracking_link:basic:read"),
            Self::TrackingLinkCreate => serializer.serialize_str("tracking_link:create"),
            Self::TrackingLinkDelete => serializer.serialize_str("tracking_link:delete"),
            Self::TrackingLinkStatsExport => serializer.serialize_str("tracking_link:stats:export"),
            Self::TrackingLinkStatsRead => serializer.serialize_str("tracking_link:stats:read"),
            Self::TrackingLinkUpdate => serializer.serialize_str("tracking_link:update"),
            Self::CoursesRead => serializer.serialize_str("courses:read"),
            Self::CoursesUpdate => serializer.serialize_str("courses:update"),
            Self::CourseLessonInteractionRead => {
                serializer.serialize_str("course_lesson_interaction:read")
            }
            Self::CourseAnalyticsRead => serializer.serialize_str("course_analytics:read"),
            Self::LeadBasicRead => serializer.serialize_str("lead:basic:read"),
            Self::LeadBasicExport => serializer.serialize_str("lead:basic:export"),
            Self::InvoiceCreate => serializer.serialize_str("invoice:create"),
            Self::InvoiceBasicRead => serializer.serialize_str("invoice:basic:read"),
            Self::InvoiceBasicExport => serializer.serialize_str("invoice:basic:export"),
            Self::InvoiceUpdate => serializer.serialize_str("invoice:update"),
            Self::WebhookReceiveInvoices => serializer.serialize_str("webhook_receive:invoices"),
            Self::WebhookReceiveSetupIntents => {
                serializer.serialize_str("webhook_receive:setup_intents")
            }
            Self::WebhookReceiveWithdrawals => {
                serializer.serialize_str("webhook_receive:withdrawals")
            }
            Self::WebhookReceiveSwaps => serializer.serialize_str("webhook_receive:swaps"),
            Self::WebhookReceiveLedgerAccounts => {
                serializer.serialize_str("webhook_receive:ledger_accounts")
            }
            Self::WebhookReceiveAccounts => serializer.serialize_str("webhook_receive:accounts"),
            Self::WebhookReceiveDeposits => serializer.serialize_str("webhook_receive:deposits"),
            Self::WebhookReceiveTransfers => serializer.serialize_str("webhook_receive:transfers"),
            Self::WebhookReceiveCardTransactions => {
                serializer.serialize_str("webhook_receive:card_transactions")
            }
            Self::WebhookReceiveCards => serializer.serialize_str("webhook_receive:cards"),
            Self::WebhookReceiveCardApplications => {
                serializer.serialize_str("webhook_receive:card_applications")
            }
            Self::WebhookReceivePayoutMethods => {
                serializer.serialize_str("webhook_receive:payout_methods")
            }
            Self::WebhookReceiveVerifications => {
                serializer.serialize_str("webhook_receive:verifications")
            }
            Self::WebhookReceiveIdentityProfiles => {
                serializer.serialize_str("webhook_receive:identity_profiles")
            }
            Self::WebhookReceivePayoutAccounts => {
                serializer.serialize_str("webhook_receive:payout_accounts")
            }
            Self::WebhookReceiveChat => serializer.serialize_str("webhook_receive:chat"),
            Self::WebhookReceiveEntries => serializer.serialize_str("webhook_receive:entries"),
            Self::WebhookReceiveAdCampaigns => {
                serializer.serialize_str("webhook_receive:ad_campaigns")
            }
            Self::WebhookReceiveProducts => serializer.serialize_str("webhook_receive:products"),
            Self::WebhookReceivePlans => serializer.serialize_str("webhook_receive:plans"),
            Self::WebhookReceiveShipments => serializer.serialize_str("webhook_receive:shipments"),
            Self::WebhookReceiveMembers => serializer.serialize_str("webhook_receive:members"),
            Self::WebhookReceiveExports => serializer.serialize_str("webhook_receive:exports"),
            Self::WebhookReceiveCourses => serializer.serialize_str("webhook_receive:courses"),
            Self::WebhookReceiveMemberships => {
                serializer.serialize_str("webhook_receive:memberships")
            }
            Self::WebhookReceivePayments => serializer.serialize_str("webhook_receive:payments"),
            Self::WebhookReceiveRefunds => serializer.serialize_str("webhook_receive:refunds"),
            Self::WebhookReceiveDisputes => serializer.serialize_str("webhook_receive:disputes"),
            Self::WebhookReceiveResolutions => {
                serializer.serialize_str("webhook_receive:resolutions")
            }
            Self::WebhookReceiveAppPayments => {
                serializer.serialize_str("webhook_receive:app_payments")
            }
            Self::WebhookReceiveAppMemberships => {
                serializer.serialize_str("webhook_receive:app_memberships")
            }
            Self::ShipmentCreate => serializer.serialize_str("shipment:create"),
            Self::ShipmentBasicRead => serializer.serialize_str("shipment:basic:read"),
            Self::CheckoutConfigurationBasicRead => {
                serializer.serialize_str("checkout_configuration:basic:read")
            }
            Self::CheckoutConfigurationCreate => {
                serializer.serialize_str("checkout_configuration:create")
            }
            Self::CheckoutConfigurationDelete => {
                serializer.serialize_str("checkout_configuration:delete")
            }
            Self::CheckoutRequestCreate => serializer.serialize_str("checkout_request:create"),
            Self::CheckoutRequestBasicRead => {
                serializer.serialize_str("checkout_request:basic:read")
            }
            Self::CryptoWalletManage => serializer.serialize_str("crypto_wallet:manage"),
            Self::CryptoWalletSwap => serializer.serialize_str("crypto_wallet:swap"),
            Self::AirdropLinkBasicRead => serializer.serialize_str("airdrop_link:basic:read"),
            Self::AirdropLinkManage => serializer.serialize_str("airdrop_link:manage"),
            Self::LeadManage => serializer.serialize_str("lead:manage"),
            Self::NotificationCreate => serializer.serialize_str("notification:create"),
            Self::UserBalanceRead => serializer.serialize_str("user:balance:read"),
            Self::UserEmailRead => serializer.serialize_str("user:email:read"),
            Self::UserStaffRead => serializer.serialize_str("user:staff:read"),
            Self::OauthTokenExchange => serializer.serialize_str("oauth:token_exchange"),
            Self::Openid => serializer.serialize_str("openid"),
            Self::Profile => serializer.serialize_str("profile"),
            Self::Email => serializer.serialize_str("email"),
            Self::AiChatRead => serializer.serialize_str("ai_chat:read"),
            Self::AiChatCreate => serializer.serialize_str("ai_chat:create"),
            Self::AiChatDelete => serializer.serialize_str("ai_chat:delete"),
            Self::AiChatUpdate => serializer.serialize_str("ai_chat:update"),
            Self::UserNotificationsRead => serializer.serialize_str("user:notifications:read"),
            Self::UserNotificationsUpdate => serializer.serialize_str("user:notifications:update"),
            Self::UserProfileUpdate => serializer.serialize_str("user:profile:update"),
            Self::__Unknown(val) => serializer.serialize_str(val),
        }
    }
}

impl<'de> Deserialize<'de> for PermissionAction {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        match value.as_str() {
            "ai_prompt:create" => Ok(Self::AiPromptCreate),
            "access_pass:basic:export" => Ok(Self::AccessPassBasicExport),
            "access_pass:basic:read" => Ok(Self::AccessPassBasicRead),
            "access_pass:control_center" => Ok(Self::AccessPassControlCenter),
            "access_pass:create" => Ok(Self::AccessPassCreate),
            "access_pass:delete" => Ok(Self::AccessPassDelete),
            "access_pass:stats:export" => Ok(Self::AccessPassStatsExport),
            "access_pass:stats:read" => Ok(Self::AccessPassStatsRead),
            "access_pass:update" => Ok(Self::AccessPassUpdate),
            "ad_campaign:basic:export" => Ok(Self::AdCampaignBasicExport),
            "ad_campaign:basic:read" => Ok(Self::AdCampaignBasicRead),
            "ad_campaign:conversion:create" => Ok(Self::AdCampaignConversionCreate),
            "ad_campaign:create" => Ok(Self::AdCampaignCreate),
            "ad_campaign:credit:create" => Ok(Self::AdCampaignCreditCreate),
            "ad_campaign:delete" => Ok(Self::AdCampaignDelete),
            "ad_campaign:read" => Ok(Self::AdCampaignRead),
            "ad_campaign:stats:read" => Ok(Self::AdCampaignStatsRead),
            "ad_campaign:update" => Ok(Self::AdCampaignUpdate),
            "audience:basic:read" => Ok(Self::AudienceBasicRead),
            "audience:update" => Ok(Self::AudienceUpdate),
            "ad_publisher:read" => Ok(Self::AdPublisherRead),
            "affiliate:basic:read" => Ok(Self::AffiliateBasicRead),
            "affiliate:create" => Ok(Self::AffiliateCreate),
            "affiliate:update" => Ok(Self::AffiliateUpdate),
            "authorized_user:create" => Ok(Self::AuthorizedUserCreate),
            "authorized_user:delete" => Ok(Self::AuthorizedUserDelete),
            "authorized_user:update" => Ok(Self::AuthorizedUserUpdate),
            "authorized_role:create" => Ok(Self::AuthorizedRoleCreate),
            "authorized_role:update" => Ok(Self::AuthorizedRoleUpdate),
            "authorized_role:delete" => Ok(Self::AuthorizedRoleDelete),
            "authorized_role:attach" => Ok(Self::AuthorizedRoleAttach),
            "authorized_role:detach" => Ok(Self::AuthorizedRoleDetach),
            "app_authorization:create" => Ok(Self::AppAuthorizationCreate),
            "app_authorization:read" => Ok(Self::AppAuthorizationRead),
            "app_authorization:update" => Ok(Self::AppAuthorizationUpdate),
            "app_authorization:delete" => Ok(Self::AppAuthorizationDelete),
            "bounty:basic:read" => Ok(Self::BountyBasicRead),
            "bounty:create" => Ok(Self::BountyCreate),
            "bounty:capture_clip:create" => Ok(Self::BountyCaptureClipCreate),
            "bounty:capture_clip:complete" => Ok(Self::BountyCaptureClipComplete),
            "bounty:capture_clip:discard" => Ok(Self::BountyCaptureClipDiscard),
            "bounty:update" => Ok(Self::BountyUpdate),
            "bounty:submission:create" => Ok(Self::BountySubmissionCreate),
            "bounty:submission:delete" => Ok(Self::BountySubmissionDelete),
            "bounty:submission:vote" => Ok(Self::BountySubmissionVote),
            "chat:manage_webhook" => Ok(Self::ChatManageWebhook),
            "chat:moderate" => Ok(Self::ChatModerate),
            "chat:message:create" => Ok(Self::ChatMessageCreate),
            "chat:read" => Ok(Self::ChatRead),
            "dms:read" => Ok(Self::DmsRead),
            "dms:message:manage" => Ok(Self::DmsMessageManage),
            "dms:channel:manage" => Ok(Self::DmsChannelManage),
            "forum:post:create" => Ok(Self::ForumPostCreate),
            "forum:read" => Ok(Self::ForumRead),
            "forum:moderate" => Ok(Self::ForumModerate),
            "company:authorized_user:read" => Ok(Self::CompanyAuthorizedUserRead),
            "company:authorized_user:email:read" => Ok(Self::CompanyAuthorizedUserEmailRead),
            "company:balance:read" => Ok(Self::CompanyBalanceRead),
            "company:balance:export" => Ok(Self::CompanyBalanceExport),
            "company_token_transaction:read" => Ok(Self::CompanyTokenTransactionRead),
            "company_token_transaction:create" => Ok(Self::CompanyTokenTransactionCreate),
            "company:log:read" => Ok(Self::CompanyLogRead),
            "company:manage_checkout" => Ok(Self::CompanyManageCheckout),
            "company:manage_legal" => Ok(Self::CompanyManageLegal),
            "company:basic:read" => Ok(Self::CompanyBasicRead),
            "company:update" => Ok(Self::CompanyUpdate),
            "company:transfer_ownership" => Ok(Self::CompanyTransferOwnership),
            "company:create" => Ok(Self::CompanyCreate),
            "company:create_child" => Ok(Self::CompanyCreateChild),
            "company:delete" => Ok(Self::CompanyDelete),
            "company:delete_child" => Ok(Self::CompanyDeleteChild),
            "company:update_child_fees" => Ok(Self::CompanyUpdateChildFees),
            "child_company:basic:export" => Ok(Self::ChildCompanyBasicExport),
            "social_account:create" => Ok(Self::SocialAccountCreate),
            "social_account:delete" => Ok(Self::SocialAccountDelete),
            "social_account:read" => Ok(Self::SocialAccountRead),
            "social_link:update" => Ok(Self::SocialLinkUpdate),
            "custom_emoji:update" => Ok(Self::CustomEmojiUpdate),
            "content_rewards:basic:export" => Ok(Self::ContentRewardsBasicExport),
            "content_rewards:basic:read" => Ok(Self::ContentRewardsBasicRead),
            "content_rewards:create" => Ok(Self::ContentRewardsCreate),
            "content_rewards:delete" => Ok(Self::ContentRewardsDelete),
            "content_rewards:moderate_submission" => Ok(Self::ContentRewardsModerateSubmission),
            "content_rewards:update" => Ok(Self::ContentRewardsUpdate),
            "developer:basic:read" => Ok(Self::DeveloperBasicRead),
            "developer:create_app" => Ok(Self::DeveloperCreateApp),
            "developer:manage_api_key" => Ok(Self::DeveloperManageApiKey),
            "developer:manage_oauth" => Ok(Self::DeveloperManageOauth),
            "developer:manage_webhook" => Ok(Self::DeveloperManageWebhook),
            "developer:logs:read" => Ok(Self::DeveloperLogsRead),
            "developer:manage_builds" => Ok(Self::DeveloperManageBuilds),
            "developer:update_app" => Ok(Self::DeveloperUpdateApp),
            "developer:update_app_authorization" => Ok(Self::DeveloperUpdateAppAuthorization),
            "event:create" => Ok(Self::EventCreate),
            "experience:attach" => Ok(Self::ExperienceAttach),
            "experience:create" => Ok(Self::ExperienceCreate),
            "experience:delete" => Ok(Self::ExperienceDelete),
            "experience:detach" => Ok(Self::ExperienceDetach),
            "experience:hidden_experience:read" => Ok(Self::ExperienceHiddenExperienceRead),
            "experience:update" => Ok(Self::ExperienceUpdate),
            "iap:read" => Ok(Self::IapRead),
            "identity:read" => Ok(Self::IdentityRead),
            "identity:write" => Ok(Self::IdentityWrite),
            "incorporation:read" => Ok(Self::IncorporationRead),
            "incorporation:write" => Ok(Self::IncorporationWrite),
            "livestream:create" => Ok(Self::LivestreamCreate),
            "livestream:delete" => Ok(Self::LivestreamDelete),
            "livestream:manage_recording" => Ok(Self::LivestreamManageRecording),
            "livestream:chat:read" => Ok(Self::LivestreamChatRead),
            "livestream:chat:write" => Ok(Self::LivestreamChatWrite),
            "livestream:moderate" => Ok(Self::LivestreamModerate),
            "media:generate" => Ok(Self::MediaGenerate),
            "media:read" => Ok(Self::MediaRead),
            "member:basic:export" => Ok(Self::MemberBasicExport),
            "member:basic:read" => Ok(Self::MemberBasicRead),
            "member:email:read" => Ok(Self::MemberEmailRead),
            "member:phone:read" => Ok(Self::MemberPhoneRead),
            "member:payment_methods:read" => Ok(Self::MemberPaymentMethodsRead),
            "member:payment_methods:use" => Ok(Self::MemberPaymentMethodsUse),
            "member:payment_methods:manage" => Ok(Self::MemberPaymentMethodsManage),
            "member:manage" => Ok(Self::MemberManage),
            "membership:cancel" => Ok(Self::MembershipCancel),
            "membership:resync_access" => Ok(Self::MembershipResyncAccess),
            "membership:create" => Ok(Self::MembershipCreate),
            "membership:update" => Ok(Self::MembershipUpdate),
            "membership:transfer" => Ok(Self::MembershipTransfer),
            "member:moderate" => Ok(Self::MemberModerate),
            "member:stats:export" => Ok(Self::MemberStatsExport),
            "member:stats:read" => Ok(Self::MemberStatsRead),
            "member:journey:read" => Ok(Self::MemberJourneyRead),
            "payment:basic:export" => Ok(Self::PaymentBasicExport),
            "payment:basic:read" => Ok(Self::PaymentBasicRead),
            "payment:charge" => Ok(Self::PaymentCharge),
            "payment:dispute" => Ok(Self::PaymentDispute),
            "payment:dispute:export" => Ok(Self::PaymentDisputeExport),
            "payment:dispute:read" => Ok(Self::PaymentDisputeRead),
            "payment:dispute_alert:read" => Ok(Self::PaymentDisputeAlertRead),
            "payment:setup_intent:read" => Ok(Self::PaymentSetupIntentRead),
            "payment:setup_intent:manage" => Ok(Self::PaymentSetupIntentManage),
            "payment:manage" => Ok(Self::PaymentManage),
            "payment:resolution_center" => Ok(Self::PaymentResolutionCenter),
            "payment:resolution_center_case:export" => Ok(Self::PaymentResolutionCenterCaseExport),
            "payment:resolution_center_case:read" => Ok(Self::PaymentResolutionCenterCaseRead),
            "payment:resolution_center_case:manage" => Ok(Self::PaymentResolutionCenterCaseManage),
            "payout:create_destination" => Ok(Self::PayoutCreateDestination),
            "payout:delete_destination" => Ok(Self::PayoutDeleteDestination),
            "payout:destination:read" => Ok(Self::PayoutDestinationRead),
            "payout:transfer_funds" => Ok(Self::PayoutTransferFunds),
            "payout:transfer:read" => Ok(Self::PayoutTransferRead),
            "payout:transfer:export" => Ok(Self::PayoutTransferExport),
            "payout:update_destination" => Ok(Self::PayoutUpdateDestination),
            "payout:withdraw_funds" => Ok(Self::PayoutWithdrawFunds),
            "payout:withdrawal:read" => Ok(Self::PayoutWithdrawalRead),
            "payout:withdrawal:export" => Ok(Self::PayoutWithdrawalExport),
            "payout:account:read" => Ok(Self::PayoutAccountRead),
            "payout:account:update" => Ok(Self::PayoutAccountUpdate),
            "plan:basic:export" => Ok(Self::PlanBasicExport),
            "plan:basic:read" => Ok(Self::PlanBasicRead),
            "plan:create" => Ok(Self::PlanCreate),
            "plan:delete" => Ok(Self::PlanDelete),
            "plan:stats:export" => Ok(Self::PlanStatsExport),
            "plan:stats:read" => Ok(Self::PlanStatsRead),
            "plan:update" => Ok(Self::PlanUpdate),
            "plan:waitlist:manage" => Ok(Self::PlanWaitlistManage),
            "plan:waitlist:export" => Ok(Self::PlanWaitlistExport),
            "plan:waitlist:read" => Ok(Self::PlanWaitlistRead),
            "promo_code:basic:export" => Ok(Self::PromoCodeBasicExport),
            "promo_code:basic:read" => Ok(Self::PromoCodeBasicRead),
            "promo_code:create" => Ok(Self::PromoCodeCreate),
            "promo_code:delete" => Ok(Self::PromoCodeDelete),
            "promo_code:update" => Ok(Self::PromoCodeUpdate),
            "referral:basic:read" => Ok(Self::ReferralBasicRead),
            "referral:partner:create" => Ok(Self::ReferralPartnerCreate),
            "partner:basic:read" => Ok(Self::PartnerBasicRead),
            "partner:invite:create" => Ok(Self::PartnerInviteCreate),
            "partner:create" => Ok(Self::PartnerCreate),
            "stats:read" => Ok(Self::StatsRead),
            "support_chat:read" => Ok(Self::SupportChatRead),
            "support_chat:create" => Ok(Self::SupportChatCreate),
            "support_chat:message:create" => Ok(Self::SupportChatMessageCreate),
            "tracking_link:basic:export" => Ok(Self::TrackingLinkBasicExport),
            "tracking_link:basic:read" => Ok(Self::TrackingLinkBasicRead),
            "tracking_link:create" => Ok(Self::TrackingLinkCreate),
            "tracking_link:delete" => Ok(Self::TrackingLinkDelete),
            "tracking_link:stats:export" => Ok(Self::TrackingLinkStatsExport),
            "tracking_link:stats:read" => Ok(Self::TrackingLinkStatsRead),
            "tracking_link:update" => Ok(Self::TrackingLinkUpdate),
            "courses:read" => Ok(Self::CoursesRead),
            "courses:update" => Ok(Self::CoursesUpdate),
            "course_lesson_interaction:read" => Ok(Self::CourseLessonInteractionRead),
            "course_analytics:read" => Ok(Self::CourseAnalyticsRead),
            "lead:basic:read" => Ok(Self::LeadBasicRead),
            "lead:basic:export" => Ok(Self::LeadBasicExport),
            "invoice:create" => Ok(Self::InvoiceCreate),
            "invoice:basic:read" => Ok(Self::InvoiceBasicRead),
            "invoice:basic:export" => Ok(Self::InvoiceBasicExport),
            "invoice:update" => Ok(Self::InvoiceUpdate),
            "webhook_receive:invoices" => Ok(Self::WebhookReceiveInvoices),
            "webhook_receive:setup_intents" => Ok(Self::WebhookReceiveSetupIntents),
            "webhook_receive:withdrawals" => Ok(Self::WebhookReceiveWithdrawals),
            "webhook_receive:swaps" => Ok(Self::WebhookReceiveSwaps),
            "webhook_receive:ledger_accounts" => Ok(Self::WebhookReceiveLedgerAccounts),
            "webhook_receive:accounts" => Ok(Self::WebhookReceiveAccounts),
            "webhook_receive:deposits" => Ok(Self::WebhookReceiveDeposits),
            "webhook_receive:transfers" => Ok(Self::WebhookReceiveTransfers),
            "webhook_receive:card_transactions" => Ok(Self::WebhookReceiveCardTransactions),
            "webhook_receive:cards" => Ok(Self::WebhookReceiveCards),
            "webhook_receive:card_applications" => Ok(Self::WebhookReceiveCardApplications),
            "webhook_receive:payout_methods" => Ok(Self::WebhookReceivePayoutMethods),
            "webhook_receive:verifications" => Ok(Self::WebhookReceiveVerifications),
            "webhook_receive:identity_profiles" => Ok(Self::WebhookReceiveIdentityProfiles),
            "webhook_receive:payout_accounts" => Ok(Self::WebhookReceivePayoutAccounts),
            "webhook_receive:chat" => Ok(Self::WebhookReceiveChat),
            "webhook_receive:entries" => Ok(Self::WebhookReceiveEntries),
            "webhook_receive:ad_campaigns" => Ok(Self::WebhookReceiveAdCampaigns),
            "webhook_receive:products" => Ok(Self::WebhookReceiveProducts),
            "webhook_receive:plans" => Ok(Self::WebhookReceivePlans),
            "webhook_receive:shipments" => Ok(Self::WebhookReceiveShipments),
            "webhook_receive:members" => Ok(Self::WebhookReceiveMembers),
            "webhook_receive:exports" => Ok(Self::WebhookReceiveExports),
            "webhook_receive:courses" => Ok(Self::WebhookReceiveCourses),
            "webhook_receive:memberships" => Ok(Self::WebhookReceiveMemberships),
            "webhook_receive:payments" => Ok(Self::WebhookReceivePayments),
            "webhook_receive:refunds" => Ok(Self::WebhookReceiveRefunds),
            "webhook_receive:disputes" => Ok(Self::WebhookReceiveDisputes),
            "webhook_receive:resolutions" => Ok(Self::WebhookReceiveResolutions),
            "webhook_receive:app_payments" => Ok(Self::WebhookReceiveAppPayments),
            "webhook_receive:app_memberships" => Ok(Self::WebhookReceiveAppMemberships),
            "shipment:create" => Ok(Self::ShipmentCreate),
            "shipment:basic:read" => Ok(Self::ShipmentBasicRead),
            "checkout_configuration:basic:read" => Ok(Self::CheckoutConfigurationBasicRead),
            "checkout_configuration:create" => Ok(Self::CheckoutConfigurationCreate),
            "checkout_configuration:delete" => Ok(Self::CheckoutConfigurationDelete),
            "checkout_request:create" => Ok(Self::CheckoutRequestCreate),
            "checkout_request:basic:read" => Ok(Self::CheckoutRequestBasicRead),
            "crypto_wallet:manage" => Ok(Self::CryptoWalletManage),
            "crypto_wallet:swap" => Ok(Self::CryptoWalletSwap),
            "airdrop_link:basic:read" => Ok(Self::AirdropLinkBasicRead),
            "airdrop_link:manage" => Ok(Self::AirdropLinkManage),
            "lead:manage" => Ok(Self::LeadManage),
            "notification:create" => Ok(Self::NotificationCreate),
            "user:balance:read" => Ok(Self::UserBalanceRead),
            "user:email:read" => Ok(Self::UserEmailRead),
            "user:staff:read" => Ok(Self::UserStaffRead),
            "oauth:token_exchange" => Ok(Self::OauthTokenExchange),
            "openid" => Ok(Self::Openid),
            "profile" => Ok(Self::Profile),
            "email" => Ok(Self::Email),
            "ai_chat:read" => Ok(Self::AiChatRead),
            "ai_chat:create" => Ok(Self::AiChatCreate),
            "ai_chat:delete" => Ok(Self::AiChatDelete),
            "ai_chat:update" => Ok(Self::AiChatUpdate),
            "user:notifications:read" => Ok(Self::UserNotificationsRead),
            "user:notifications:update" => Ok(Self::UserNotificationsUpdate),
            "user:profile:update" => Ok(Self::UserProfileUpdate),
            _ => Ok(Self::__Unknown(value)),
        }
    }
}

impl fmt::Display for PermissionAction {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::AiPromptCreate => write!(f, "ai_prompt:create"),
            Self::AccessPassBasicExport => write!(f, "access_pass:basic:export"),
            Self::AccessPassBasicRead => write!(f, "access_pass:basic:read"),
            Self::AccessPassControlCenter => write!(f, "access_pass:control_center"),
            Self::AccessPassCreate => write!(f, "access_pass:create"),
            Self::AccessPassDelete => write!(f, "access_pass:delete"),
            Self::AccessPassStatsExport => write!(f, "access_pass:stats:export"),
            Self::AccessPassStatsRead => write!(f, "access_pass:stats:read"),
            Self::AccessPassUpdate => write!(f, "access_pass:update"),
            Self::AdCampaignBasicExport => write!(f, "ad_campaign:basic:export"),
            Self::AdCampaignBasicRead => write!(f, "ad_campaign:basic:read"),
            Self::AdCampaignConversionCreate => write!(f, "ad_campaign:conversion:create"),
            Self::AdCampaignCreate => write!(f, "ad_campaign:create"),
            Self::AdCampaignCreditCreate => write!(f, "ad_campaign:credit:create"),
            Self::AdCampaignDelete => write!(f, "ad_campaign:delete"),
            Self::AdCampaignRead => write!(f, "ad_campaign:read"),
            Self::AdCampaignStatsRead => write!(f, "ad_campaign:stats:read"),
            Self::AdCampaignUpdate => write!(f, "ad_campaign:update"),
            Self::AudienceBasicRead => write!(f, "audience:basic:read"),
            Self::AudienceUpdate => write!(f, "audience:update"),
            Self::AdPublisherRead => write!(f, "ad_publisher:read"),
            Self::AffiliateBasicRead => write!(f, "affiliate:basic:read"),
            Self::AffiliateCreate => write!(f, "affiliate:create"),
            Self::AffiliateUpdate => write!(f, "affiliate:update"),
            Self::AuthorizedUserCreate => write!(f, "authorized_user:create"),
            Self::AuthorizedUserDelete => write!(f, "authorized_user:delete"),
            Self::AuthorizedUserUpdate => write!(f, "authorized_user:update"),
            Self::AuthorizedRoleCreate => write!(f, "authorized_role:create"),
            Self::AuthorizedRoleUpdate => write!(f, "authorized_role:update"),
            Self::AuthorizedRoleDelete => write!(f, "authorized_role:delete"),
            Self::AuthorizedRoleAttach => write!(f, "authorized_role:attach"),
            Self::AuthorizedRoleDetach => write!(f, "authorized_role:detach"),
            Self::AppAuthorizationCreate => write!(f, "app_authorization:create"),
            Self::AppAuthorizationRead => write!(f, "app_authorization:read"),
            Self::AppAuthorizationUpdate => write!(f, "app_authorization:update"),
            Self::AppAuthorizationDelete => write!(f, "app_authorization:delete"),
            Self::BountyBasicRead => write!(f, "bounty:basic:read"),
            Self::BountyCreate => write!(f, "bounty:create"),
            Self::BountyCaptureClipCreate => write!(f, "bounty:capture_clip:create"),
            Self::BountyCaptureClipComplete => write!(f, "bounty:capture_clip:complete"),
            Self::BountyCaptureClipDiscard => write!(f, "bounty:capture_clip:discard"),
            Self::BountyUpdate => write!(f, "bounty:update"),
            Self::BountySubmissionCreate => write!(f, "bounty:submission:create"),
            Self::BountySubmissionDelete => write!(f, "bounty:submission:delete"),
            Self::BountySubmissionVote => write!(f, "bounty:submission:vote"),
            Self::ChatManageWebhook => write!(f, "chat:manage_webhook"),
            Self::ChatModerate => write!(f, "chat:moderate"),
            Self::ChatMessageCreate => write!(f, "chat:message:create"),
            Self::ChatRead => write!(f, "chat:read"),
            Self::DmsRead => write!(f, "dms:read"),
            Self::DmsMessageManage => write!(f, "dms:message:manage"),
            Self::DmsChannelManage => write!(f, "dms:channel:manage"),
            Self::ForumPostCreate => write!(f, "forum:post:create"),
            Self::ForumRead => write!(f, "forum:read"),
            Self::ForumModerate => write!(f, "forum:moderate"),
            Self::CompanyAuthorizedUserRead => write!(f, "company:authorized_user:read"),
            Self::CompanyAuthorizedUserEmailRead => write!(f, "company:authorized_user:email:read"),
            Self::CompanyBalanceRead => write!(f, "company:balance:read"),
            Self::CompanyBalanceExport => write!(f, "company:balance:export"),
            Self::CompanyTokenTransactionRead => write!(f, "company_token_transaction:read"),
            Self::CompanyTokenTransactionCreate => write!(f, "company_token_transaction:create"),
            Self::CompanyLogRead => write!(f, "company:log:read"),
            Self::CompanyManageCheckout => write!(f, "company:manage_checkout"),
            Self::CompanyManageLegal => write!(f, "company:manage_legal"),
            Self::CompanyBasicRead => write!(f, "company:basic:read"),
            Self::CompanyUpdate => write!(f, "company:update"),
            Self::CompanyTransferOwnership => write!(f, "company:transfer_ownership"),
            Self::CompanyCreate => write!(f, "company:create"),
            Self::CompanyCreateChild => write!(f, "company:create_child"),
            Self::CompanyDelete => write!(f, "company:delete"),
            Self::CompanyDeleteChild => write!(f, "company:delete_child"),
            Self::CompanyUpdateChildFees => write!(f, "company:update_child_fees"),
            Self::ChildCompanyBasicExport => write!(f, "child_company:basic:export"),
            Self::SocialAccountCreate => write!(f, "social_account:create"),
            Self::SocialAccountDelete => write!(f, "social_account:delete"),
            Self::SocialAccountRead => write!(f, "social_account:read"),
            Self::SocialLinkUpdate => write!(f, "social_link:update"),
            Self::CustomEmojiUpdate => write!(f, "custom_emoji:update"),
            Self::ContentRewardsBasicExport => write!(f, "content_rewards:basic:export"),
            Self::ContentRewardsBasicRead => write!(f, "content_rewards:basic:read"),
            Self::ContentRewardsCreate => write!(f, "content_rewards:create"),
            Self::ContentRewardsDelete => write!(f, "content_rewards:delete"),
            Self::ContentRewardsModerateSubmission => {
                write!(f, "content_rewards:moderate_submission")
            }
            Self::ContentRewardsUpdate => write!(f, "content_rewards:update"),
            Self::DeveloperBasicRead => write!(f, "developer:basic:read"),
            Self::DeveloperCreateApp => write!(f, "developer:create_app"),
            Self::DeveloperManageApiKey => write!(f, "developer:manage_api_key"),
            Self::DeveloperManageOauth => write!(f, "developer:manage_oauth"),
            Self::DeveloperManageWebhook => write!(f, "developer:manage_webhook"),
            Self::DeveloperLogsRead => write!(f, "developer:logs:read"),
            Self::DeveloperManageBuilds => write!(f, "developer:manage_builds"),
            Self::DeveloperUpdateApp => write!(f, "developer:update_app"),
            Self::DeveloperUpdateAppAuthorization => {
                write!(f, "developer:update_app_authorization")
            }
            Self::EventCreate => write!(f, "event:create"),
            Self::ExperienceAttach => write!(f, "experience:attach"),
            Self::ExperienceCreate => write!(f, "experience:create"),
            Self::ExperienceDelete => write!(f, "experience:delete"),
            Self::ExperienceDetach => write!(f, "experience:detach"),
            Self::ExperienceHiddenExperienceRead => write!(f, "experience:hidden_experience:read"),
            Self::ExperienceUpdate => write!(f, "experience:update"),
            Self::IapRead => write!(f, "iap:read"),
            Self::IdentityRead => write!(f, "identity:read"),
            Self::IdentityWrite => write!(f, "identity:write"),
            Self::IncorporationRead => write!(f, "incorporation:read"),
            Self::IncorporationWrite => write!(f, "incorporation:write"),
            Self::LivestreamCreate => write!(f, "livestream:create"),
            Self::LivestreamDelete => write!(f, "livestream:delete"),
            Self::LivestreamManageRecording => write!(f, "livestream:manage_recording"),
            Self::LivestreamChatRead => write!(f, "livestream:chat:read"),
            Self::LivestreamChatWrite => write!(f, "livestream:chat:write"),
            Self::LivestreamModerate => write!(f, "livestream:moderate"),
            Self::MediaGenerate => write!(f, "media:generate"),
            Self::MediaRead => write!(f, "media:read"),
            Self::MemberBasicExport => write!(f, "member:basic:export"),
            Self::MemberBasicRead => write!(f, "member:basic:read"),
            Self::MemberEmailRead => write!(f, "member:email:read"),
            Self::MemberPhoneRead => write!(f, "member:phone:read"),
            Self::MemberPaymentMethodsRead => write!(f, "member:payment_methods:read"),
            Self::MemberPaymentMethodsUse => write!(f, "member:payment_methods:use"),
            Self::MemberPaymentMethodsManage => write!(f, "member:payment_methods:manage"),
            Self::MemberManage => write!(f, "member:manage"),
            Self::MembershipCancel => write!(f, "membership:cancel"),
            Self::MembershipResyncAccess => write!(f, "membership:resync_access"),
            Self::MembershipCreate => write!(f, "membership:create"),
            Self::MembershipUpdate => write!(f, "membership:update"),
            Self::MembershipTransfer => write!(f, "membership:transfer"),
            Self::MemberModerate => write!(f, "member:moderate"),
            Self::MemberStatsExport => write!(f, "member:stats:export"),
            Self::MemberStatsRead => write!(f, "member:stats:read"),
            Self::MemberJourneyRead => write!(f, "member:journey:read"),
            Self::PaymentBasicExport => write!(f, "payment:basic:export"),
            Self::PaymentBasicRead => write!(f, "payment:basic:read"),
            Self::PaymentCharge => write!(f, "payment:charge"),
            Self::PaymentDispute => write!(f, "payment:dispute"),
            Self::PaymentDisputeExport => write!(f, "payment:dispute:export"),
            Self::PaymentDisputeRead => write!(f, "payment:dispute:read"),
            Self::PaymentDisputeAlertRead => write!(f, "payment:dispute_alert:read"),
            Self::PaymentSetupIntentRead => write!(f, "payment:setup_intent:read"),
            Self::PaymentSetupIntentManage => write!(f, "payment:setup_intent:manage"),
            Self::PaymentManage => write!(f, "payment:manage"),
            Self::PaymentResolutionCenter => write!(f, "payment:resolution_center"),
            Self::PaymentResolutionCenterCaseExport => {
                write!(f, "payment:resolution_center_case:export")
            }
            Self::PaymentResolutionCenterCaseRead => {
                write!(f, "payment:resolution_center_case:read")
            }
            Self::PaymentResolutionCenterCaseManage => {
                write!(f, "payment:resolution_center_case:manage")
            }
            Self::PayoutCreateDestination => write!(f, "payout:create_destination"),
            Self::PayoutDeleteDestination => write!(f, "payout:delete_destination"),
            Self::PayoutDestinationRead => write!(f, "payout:destination:read"),
            Self::PayoutTransferFunds => write!(f, "payout:transfer_funds"),
            Self::PayoutTransferRead => write!(f, "payout:transfer:read"),
            Self::PayoutTransferExport => write!(f, "payout:transfer:export"),
            Self::PayoutUpdateDestination => write!(f, "payout:update_destination"),
            Self::PayoutWithdrawFunds => write!(f, "payout:withdraw_funds"),
            Self::PayoutWithdrawalRead => write!(f, "payout:withdrawal:read"),
            Self::PayoutWithdrawalExport => write!(f, "payout:withdrawal:export"),
            Self::PayoutAccountRead => write!(f, "payout:account:read"),
            Self::PayoutAccountUpdate => write!(f, "payout:account:update"),
            Self::PlanBasicExport => write!(f, "plan:basic:export"),
            Self::PlanBasicRead => write!(f, "plan:basic:read"),
            Self::PlanCreate => write!(f, "plan:create"),
            Self::PlanDelete => write!(f, "plan:delete"),
            Self::PlanStatsExport => write!(f, "plan:stats:export"),
            Self::PlanStatsRead => write!(f, "plan:stats:read"),
            Self::PlanUpdate => write!(f, "plan:update"),
            Self::PlanWaitlistManage => write!(f, "plan:waitlist:manage"),
            Self::PlanWaitlistExport => write!(f, "plan:waitlist:export"),
            Self::PlanWaitlistRead => write!(f, "plan:waitlist:read"),
            Self::PromoCodeBasicExport => write!(f, "promo_code:basic:export"),
            Self::PromoCodeBasicRead => write!(f, "promo_code:basic:read"),
            Self::PromoCodeCreate => write!(f, "promo_code:create"),
            Self::PromoCodeDelete => write!(f, "promo_code:delete"),
            Self::PromoCodeUpdate => write!(f, "promo_code:update"),
            Self::ReferralBasicRead => write!(f, "referral:basic:read"),
            Self::ReferralPartnerCreate => write!(f, "referral:partner:create"),
            Self::PartnerBasicRead => write!(f, "partner:basic:read"),
            Self::PartnerInviteCreate => write!(f, "partner:invite:create"),
            Self::PartnerCreate => write!(f, "partner:create"),
            Self::StatsRead => write!(f, "stats:read"),
            Self::SupportChatRead => write!(f, "support_chat:read"),
            Self::SupportChatCreate => write!(f, "support_chat:create"),
            Self::SupportChatMessageCreate => write!(f, "support_chat:message:create"),
            Self::TrackingLinkBasicExport => write!(f, "tracking_link:basic:export"),
            Self::TrackingLinkBasicRead => write!(f, "tracking_link:basic:read"),
            Self::TrackingLinkCreate => write!(f, "tracking_link:create"),
            Self::TrackingLinkDelete => write!(f, "tracking_link:delete"),
            Self::TrackingLinkStatsExport => write!(f, "tracking_link:stats:export"),
            Self::TrackingLinkStatsRead => write!(f, "tracking_link:stats:read"),
            Self::TrackingLinkUpdate => write!(f, "tracking_link:update"),
            Self::CoursesRead => write!(f, "courses:read"),
            Self::CoursesUpdate => write!(f, "courses:update"),
            Self::CourseLessonInteractionRead => write!(f, "course_lesson_interaction:read"),
            Self::CourseAnalyticsRead => write!(f, "course_analytics:read"),
            Self::LeadBasicRead => write!(f, "lead:basic:read"),
            Self::LeadBasicExport => write!(f, "lead:basic:export"),
            Self::InvoiceCreate => write!(f, "invoice:create"),
            Self::InvoiceBasicRead => write!(f, "invoice:basic:read"),
            Self::InvoiceBasicExport => write!(f, "invoice:basic:export"),
            Self::InvoiceUpdate => write!(f, "invoice:update"),
            Self::WebhookReceiveInvoices => write!(f, "webhook_receive:invoices"),
            Self::WebhookReceiveSetupIntents => write!(f, "webhook_receive:setup_intents"),
            Self::WebhookReceiveWithdrawals => write!(f, "webhook_receive:withdrawals"),
            Self::WebhookReceiveSwaps => write!(f, "webhook_receive:swaps"),
            Self::WebhookReceiveLedgerAccounts => write!(f, "webhook_receive:ledger_accounts"),
            Self::WebhookReceiveAccounts => write!(f, "webhook_receive:accounts"),
            Self::WebhookReceiveDeposits => write!(f, "webhook_receive:deposits"),
            Self::WebhookReceiveTransfers => write!(f, "webhook_receive:transfers"),
            Self::WebhookReceiveCardTransactions => write!(f, "webhook_receive:card_transactions"),
            Self::WebhookReceiveCards => write!(f, "webhook_receive:cards"),
            Self::WebhookReceiveCardApplications => write!(f, "webhook_receive:card_applications"),
            Self::WebhookReceivePayoutMethods => write!(f, "webhook_receive:payout_methods"),
            Self::WebhookReceiveVerifications => write!(f, "webhook_receive:verifications"),
            Self::WebhookReceiveIdentityProfiles => write!(f, "webhook_receive:identity_profiles"),
            Self::WebhookReceivePayoutAccounts => write!(f, "webhook_receive:payout_accounts"),
            Self::WebhookReceiveChat => write!(f, "webhook_receive:chat"),
            Self::WebhookReceiveEntries => write!(f, "webhook_receive:entries"),
            Self::WebhookReceiveAdCampaigns => write!(f, "webhook_receive:ad_campaigns"),
            Self::WebhookReceiveProducts => write!(f, "webhook_receive:products"),
            Self::WebhookReceivePlans => write!(f, "webhook_receive:plans"),
            Self::WebhookReceiveShipments => write!(f, "webhook_receive:shipments"),
            Self::WebhookReceiveMembers => write!(f, "webhook_receive:members"),
            Self::WebhookReceiveExports => write!(f, "webhook_receive:exports"),
            Self::WebhookReceiveCourses => write!(f, "webhook_receive:courses"),
            Self::WebhookReceiveMemberships => write!(f, "webhook_receive:memberships"),
            Self::WebhookReceivePayments => write!(f, "webhook_receive:payments"),
            Self::WebhookReceiveRefunds => write!(f, "webhook_receive:refunds"),
            Self::WebhookReceiveDisputes => write!(f, "webhook_receive:disputes"),
            Self::WebhookReceiveResolutions => write!(f, "webhook_receive:resolutions"),
            Self::WebhookReceiveAppPayments => write!(f, "webhook_receive:app_payments"),
            Self::WebhookReceiveAppMemberships => write!(f, "webhook_receive:app_memberships"),
            Self::ShipmentCreate => write!(f, "shipment:create"),
            Self::ShipmentBasicRead => write!(f, "shipment:basic:read"),
            Self::CheckoutConfigurationBasicRead => write!(f, "checkout_configuration:basic:read"),
            Self::CheckoutConfigurationCreate => write!(f, "checkout_configuration:create"),
            Self::CheckoutConfigurationDelete => write!(f, "checkout_configuration:delete"),
            Self::CheckoutRequestCreate => write!(f, "checkout_request:create"),
            Self::CheckoutRequestBasicRead => write!(f, "checkout_request:basic:read"),
            Self::CryptoWalletManage => write!(f, "crypto_wallet:manage"),
            Self::CryptoWalletSwap => write!(f, "crypto_wallet:swap"),
            Self::AirdropLinkBasicRead => write!(f, "airdrop_link:basic:read"),
            Self::AirdropLinkManage => write!(f, "airdrop_link:manage"),
            Self::LeadManage => write!(f, "lead:manage"),
            Self::NotificationCreate => write!(f, "notification:create"),
            Self::UserBalanceRead => write!(f, "user:balance:read"),
            Self::UserEmailRead => write!(f, "user:email:read"),
            Self::UserStaffRead => write!(f, "user:staff:read"),
            Self::OauthTokenExchange => write!(f, "oauth:token_exchange"),
            Self::Openid => write!(f, "openid"),
            Self::Profile => write!(f, "profile"),
            Self::Email => write!(f, "email"),
            Self::AiChatRead => write!(f, "ai_chat:read"),
            Self::AiChatCreate => write!(f, "ai_chat:create"),
            Self::AiChatDelete => write!(f, "ai_chat:delete"),
            Self::AiChatUpdate => write!(f, "ai_chat:update"),
            Self::UserNotificationsRead => write!(f, "user:notifications:read"),
            Self::UserNotificationsUpdate => write!(f, "user:notifications:update"),
            Self::UserProfileUpdate => write!(f, "user:profile:update"),
            Self::__Unknown(val) => write!(f, "{}", val),
        }
    }
}
