pub use crate::prelude::*;

/// Currency used for a fixed-amount discount.
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum PromoCodeCurrency {
    Usd,
    Sgd,
    Inr,
    Aud,
    Brl,
    Cad,
    Dkk,
    Eur,
    Nok,
    Gbp,
    Sek,
    Chf,
    Hkd,
    Huf,
    Jpy,
    Mxn,
    Myr,
    Pln,
    Czk,
    Nzd,
    Aed,
    Eth,
    Ape,
    Cop,
    Ron,
    Thb,
    Bgn,
    Idr,
    Dop,
    Php,
    Try,
    Krw,
    Twd,
    Vnd,
    Pkr,
    Clp,
    Uyu,
    Ars,
    Zar,
    Dzd,
    Tnd,
    Mad,
    Kes,
    Kwd,
    Jod,
    All,
    Xcd,
    Amd,
    Bsd,
    Bhd,
    Bob,
    Bam,
    Khr,
    Crc,
    Xof,
    Egp,
    Etb,
    Gmd,
    Ghs,
    Gtq,
    Gyd,
    Ils,
    Jmd,
    Mop,
    Mga,
    Mur,
    Mdl,
    Mnt,
    Nad,
    Ngn,
    Mkd,
    Omr,
    Pyg,
    Pen,
    Qar,
    Rwf,
    Sar,
    Rsd,
    Lkr,
    Tzs,
    Ttd,
    Uzs,
    Rub,
    Btc,
    Cny,
    Usdt,
    Kzt,
    Awg,
    WhopUsd,
    Xau,
    /// This variant is used for forward compatibility.
    /// If the server sends a value not recognized by the current SDK version,
    /// it will be captured here with the raw string value.
    __Unknown(String),
}
impl Serialize for PromoCodeCurrency {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        match self {
            Self::Usd => serializer.serialize_str("usd"),
            Self::Sgd => serializer.serialize_str("sgd"),
            Self::Inr => serializer.serialize_str("inr"),
            Self::Aud => serializer.serialize_str("aud"),
            Self::Brl => serializer.serialize_str("brl"),
            Self::Cad => serializer.serialize_str("cad"),
            Self::Dkk => serializer.serialize_str("dkk"),
            Self::Eur => serializer.serialize_str("eur"),
            Self::Nok => serializer.serialize_str("nok"),
            Self::Gbp => serializer.serialize_str("gbp"),
            Self::Sek => serializer.serialize_str("sek"),
            Self::Chf => serializer.serialize_str("chf"),
            Self::Hkd => serializer.serialize_str("hkd"),
            Self::Huf => serializer.serialize_str("huf"),
            Self::Jpy => serializer.serialize_str("jpy"),
            Self::Mxn => serializer.serialize_str("mxn"),
            Self::Myr => serializer.serialize_str("myr"),
            Self::Pln => serializer.serialize_str("pln"),
            Self::Czk => serializer.serialize_str("czk"),
            Self::Nzd => serializer.serialize_str("nzd"),
            Self::Aed => serializer.serialize_str("aed"),
            Self::Eth => serializer.serialize_str("eth"),
            Self::Ape => serializer.serialize_str("ape"),
            Self::Cop => serializer.serialize_str("cop"),
            Self::Ron => serializer.serialize_str("ron"),
            Self::Thb => serializer.serialize_str("thb"),
            Self::Bgn => serializer.serialize_str("bgn"),
            Self::Idr => serializer.serialize_str("idr"),
            Self::Dop => serializer.serialize_str("dop"),
            Self::Php => serializer.serialize_str("php"),
            Self::Try => serializer.serialize_str("try"),
            Self::Krw => serializer.serialize_str("krw"),
            Self::Twd => serializer.serialize_str("twd"),
            Self::Vnd => serializer.serialize_str("vnd"),
            Self::Pkr => serializer.serialize_str("pkr"),
            Self::Clp => serializer.serialize_str("clp"),
            Self::Uyu => serializer.serialize_str("uyu"),
            Self::Ars => serializer.serialize_str("ars"),
            Self::Zar => serializer.serialize_str("zar"),
            Self::Dzd => serializer.serialize_str("dzd"),
            Self::Tnd => serializer.serialize_str("tnd"),
            Self::Mad => serializer.serialize_str("mad"),
            Self::Kes => serializer.serialize_str("kes"),
            Self::Kwd => serializer.serialize_str("kwd"),
            Self::Jod => serializer.serialize_str("jod"),
            Self::All => serializer.serialize_str("all"),
            Self::Xcd => serializer.serialize_str("xcd"),
            Self::Amd => serializer.serialize_str("amd"),
            Self::Bsd => serializer.serialize_str("bsd"),
            Self::Bhd => serializer.serialize_str("bhd"),
            Self::Bob => serializer.serialize_str("bob"),
            Self::Bam => serializer.serialize_str("bam"),
            Self::Khr => serializer.serialize_str("khr"),
            Self::Crc => serializer.serialize_str("crc"),
            Self::Xof => serializer.serialize_str("xof"),
            Self::Egp => serializer.serialize_str("egp"),
            Self::Etb => serializer.serialize_str("etb"),
            Self::Gmd => serializer.serialize_str("gmd"),
            Self::Ghs => serializer.serialize_str("ghs"),
            Self::Gtq => serializer.serialize_str("gtq"),
            Self::Gyd => serializer.serialize_str("gyd"),
            Self::Ils => serializer.serialize_str("ils"),
            Self::Jmd => serializer.serialize_str("jmd"),
            Self::Mop => serializer.serialize_str("mop"),
            Self::Mga => serializer.serialize_str("mga"),
            Self::Mur => serializer.serialize_str("mur"),
            Self::Mdl => serializer.serialize_str("mdl"),
            Self::Mnt => serializer.serialize_str("mnt"),
            Self::Nad => serializer.serialize_str("nad"),
            Self::Ngn => serializer.serialize_str("ngn"),
            Self::Mkd => serializer.serialize_str("mkd"),
            Self::Omr => serializer.serialize_str("omr"),
            Self::Pyg => serializer.serialize_str("pyg"),
            Self::Pen => serializer.serialize_str("pen"),
            Self::Qar => serializer.serialize_str("qar"),
            Self::Rwf => serializer.serialize_str("rwf"),
            Self::Sar => serializer.serialize_str("sar"),
            Self::Rsd => serializer.serialize_str("rsd"),
            Self::Lkr => serializer.serialize_str("lkr"),
            Self::Tzs => serializer.serialize_str("tzs"),
            Self::Ttd => serializer.serialize_str("ttd"),
            Self::Uzs => serializer.serialize_str("uzs"),
            Self::Rub => serializer.serialize_str("rub"),
            Self::Btc => serializer.serialize_str("btc"),
            Self::Cny => serializer.serialize_str("cny"),
            Self::Usdt => serializer.serialize_str("usdt"),
            Self::Kzt => serializer.serialize_str("kzt"),
            Self::Awg => serializer.serialize_str("awg"),
            Self::WhopUsd => serializer.serialize_str("whop_usd"),
            Self::Xau => serializer.serialize_str("xau"),
            Self::__Unknown(val) => serializer.serialize_str(val),
        }
    }
}

impl<'de> Deserialize<'de> for PromoCodeCurrency {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        match value.as_str() {
            "usd" => Ok(Self::Usd),
            "sgd" => Ok(Self::Sgd),
            "inr" => Ok(Self::Inr),
            "aud" => Ok(Self::Aud),
            "brl" => Ok(Self::Brl),
            "cad" => Ok(Self::Cad),
            "dkk" => Ok(Self::Dkk),
            "eur" => Ok(Self::Eur),
            "nok" => Ok(Self::Nok),
            "gbp" => Ok(Self::Gbp),
            "sek" => Ok(Self::Sek),
            "chf" => Ok(Self::Chf),
            "hkd" => Ok(Self::Hkd),
            "huf" => Ok(Self::Huf),
            "jpy" => Ok(Self::Jpy),
            "mxn" => Ok(Self::Mxn),
            "myr" => Ok(Self::Myr),
            "pln" => Ok(Self::Pln),
            "czk" => Ok(Self::Czk),
            "nzd" => Ok(Self::Nzd),
            "aed" => Ok(Self::Aed),
            "eth" => Ok(Self::Eth),
            "ape" => Ok(Self::Ape),
            "cop" => Ok(Self::Cop),
            "ron" => Ok(Self::Ron),
            "thb" => Ok(Self::Thb),
            "bgn" => Ok(Self::Bgn),
            "idr" => Ok(Self::Idr),
            "dop" => Ok(Self::Dop),
            "php" => Ok(Self::Php),
            "try" => Ok(Self::Try),
            "krw" => Ok(Self::Krw),
            "twd" => Ok(Self::Twd),
            "vnd" => Ok(Self::Vnd),
            "pkr" => Ok(Self::Pkr),
            "clp" => Ok(Self::Clp),
            "uyu" => Ok(Self::Uyu),
            "ars" => Ok(Self::Ars),
            "zar" => Ok(Self::Zar),
            "dzd" => Ok(Self::Dzd),
            "tnd" => Ok(Self::Tnd),
            "mad" => Ok(Self::Mad),
            "kes" => Ok(Self::Kes),
            "kwd" => Ok(Self::Kwd),
            "jod" => Ok(Self::Jod),
            "all" => Ok(Self::All),
            "xcd" => Ok(Self::Xcd),
            "amd" => Ok(Self::Amd),
            "bsd" => Ok(Self::Bsd),
            "bhd" => Ok(Self::Bhd),
            "bob" => Ok(Self::Bob),
            "bam" => Ok(Self::Bam),
            "khr" => Ok(Self::Khr),
            "crc" => Ok(Self::Crc),
            "xof" => Ok(Self::Xof),
            "egp" => Ok(Self::Egp),
            "etb" => Ok(Self::Etb),
            "gmd" => Ok(Self::Gmd),
            "ghs" => Ok(Self::Ghs),
            "gtq" => Ok(Self::Gtq),
            "gyd" => Ok(Self::Gyd),
            "ils" => Ok(Self::Ils),
            "jmd" => Ok(Self::Jmd),
            "mop" => Ok(Self::Mop),
            "mga" => Ok(Self::Mga),
            "mur" => Ok(Self::Mur),
            "mdl" => Ok(Self::Mdl),
            "mnt" => Ok(Self::Mnt),
            "nad" => Ok(Self::Nad),
            "ngn" => Ok(Self::Ngn),
            "mkd" => Ok(Self::Mkd),
            "omr" => Ok(Self::Omr),
            "pyg" => Ok(Self::Pyg),
            "pen" => Ok(Self::Pen),
            "qar" => Ok(Self::Qar),
            "rwf" => Ok(Self::Rwf),
            "sar" => Ok(Self::Sar),
            "rsd" => Ok(Self::Rsd),
            "lkr" => Ok(Self::Lkr),
            "tzs" => Ok(Self::Tzs),
            "ttd" => Ok(Self::Ttd),
            "uzs" => Ok(Self::Uzs),
            "rub" => Ok(Self::Rub),
            "btc" => Ok(Self::Btc),
            "cny" => Ok(Self::Cny),
            "usdt" => Ok(Self::Usdt),
            "kzt" => Ok(Self::Kzt),
            "awg" => Ok(Self::Awg),
            "whop_usd" => Ok(Self::WhopUsd),
            "xau" => Ok(Self::Xau),
            _ => Ok(Self::__Unknown(value)),
        }
    }
}

impl fmt::Display for PromoCodeCurrency {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Usd => write!(f, "usd"),
            Self::Sgd => write!(f, "sgd"),
            Self::Inr => write!(f, "inr"),
            Self::Aud => write!(f, "aud"),
            Self::Brl => write!(f, "brl"),
            Self::Cad => write!(f, "cad"),
            Self::Dkk => write!(f, "dkk"),
            Self::Eur => write!(f, "eur"),
            Self::Nok => write!(f, "nok"),
            Self::Gbp => write!(f, "gbp"),
            Self::Sek => write!(f, "sek"),
            Self::Chf => write!(f, "chf"),
            Self::Hkd => write!(f, "hkd"),
            Self::Huf => write!(f, "huf"),
            Self::Jpy => write!(f, "jpy"),
            Self::Mxn => write!(f, "mxn"),
            Self::Myr => write!(f, "myr"),
            Self::Pln => write!(f, "pln"),
            Self::Czk => write!(f, "czk"),
            Self::Nzd => write!(f, "nzd"),
            Self::Aed => write!(f, "aed"),
            Self::Eth => write!(f, "eth"),
            Self::Ape => write!(f, "ape"),
            Self::Cop => write!(f, "cop"),
            Self::Ron => write!(f, "ron"),
            Self::Thb => write!(f, "thb"),
            Self::Bgn => write!(f, "bgn"),
            Self::Idr => write!(f, "idr"),
            Self::Dop => write!(f, "dop"),
            Self::Php => write!(f, "php"),
            Self::Try => write!(f, "try"),
            Self::Krw => write!(f, "krw"),
            Self::Twd => write!(f, "twd"),
            Self::Vnd => write!(f, "vnd"),
            Self::Pkr => write!(f, "pkr"),
            Self::Clp => write!(f, "clp"),
            Self::Uyu => write!(f, "uyu"),
            Self::Ars => write!(f, "ars"),
            Self::Zar => write!(f, "zar"),
            Self::Dzd => write!(f, "dzd"),
            Self::Tnd => write!(f, "tnd"),
            Self::Mad => write!(f, "mad"),
            Self::Kes => write!(f, "kes"),
            Self::Kwd => write!(f, "kwd"),
            Self::Jod => write!(f, "jod"),
            Self::All => write!(f, "all"),
            Self::Xcd => write!(f, "xcd"),
            Self::Amd => write!(f, "amd"),
            Self::Bsd => write!(f, "bsd"),
            Self::Bhd => write!(f, "bhd"),
            Self::Bob => write!(f, "bob"),
            Self::Bam => write!(f, "bam"),
            Self::Khr => write!(f, "khr"),
            Self::Crc => write!(f, "crc"),
            Self::Xof => write!(f, "xof"),
            Self::Egp => write!(f, "egp"),
            Self::Etb => write!(f, "etb"),
            Self::Gmd => write!(f, "gmd"),
            Self::Ghs => write!(f, "ghs"),
            Self::Gtq => write!(f, "gtq"),
            Self::Gyd => write!(f, "gyd"),
            Self::Ils => write!(f, "ils"),
            Self::Jmd => write!(f, "jmd"),
            Self::Mop => write!(f, "mop"),
            Self::Mga => write!(f, "mga"),
            Self::Mur => write!(f, "mur"),
            Self::Mdl => write!(f, "mdl"),
            Self::Mnt => write!(f, "mnt"),
            Self::Nad => write!(f, "nad"),
            Self::Ngn => write!(f, "ngn"),
            Self::Mkd => write!(f, "mkd"),
            Self::Omr => write!(f, "omr"),
            Self::Pyg => write!(f, "pyg"),
            Self::Pen => write!(f, "pen"),
            Self::Qar => write!(f, "qar"),
            Self::Rwf => write!(f, "rwf"),
            Self::Sar => write!(f, "sar"),
            Self::Rsd => write!(f, "rsd"),
            Self::Lkr => write!(f, "lkr"),
            Self::Tzs => write!(f, "tzs"),
            Self::Ttd => write!(f, "ttd"),
            Self::Uzs => write!(f, "uzs"),
            Self::Rub => write!(f, "rub"),
            Self::Btc => write!(f, "btc"),
            Self::Cny => write!(f, "cny"),
            Self::Usdt => write!(f, "usdt"),
            Self::Kzt => write!(f, "kzt"),
            Self::Awg => write!(f, "awg"),
            Self::WhopUsd => write!(f, "whop_usd"),
            Self::Xau => write!(f, "xau"),
            Self::__Unknown(val) => write!(f, "{}", val),
        }
    }
}
