pub use crate::prelude::*;

/// Autogenerated input type of CreateSetupIntent
#[derive(Debug, Clone, Serialize, Deserialize, Default, PartialEq)]
pub struct CreateSetupIntentsRequestBodyConfirmationToken {
    /// The ID of the company to save the payment method for.
    #[serde(default)]
    pub account_id: String,
    /// A confirmation token ID (ctok_) describing a payment method the buyer just supplied. Provide this or payment_method_id, not both.
    #[serde(default)]
    pub confirmation_token: String,
    /// The currency the saved payment method will be used with. Controls which currency-specific payment methods are available. Defaults to usd.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub currency: Option<Currencies>,
    /// Overrides the buyer email carried on the confirmation token, resolving or creating the Whop user the method belongs to. Ignored when the caller IS the buyer or the confirmation token was created by a signed-in buyer, and unless confirmation_token is provided.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// Custom metadata to attach to the setup intent.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<HashMap<String, serde_json::Value>>,
    /// Where the buyer continues after completing an off-site step. Must be an absolute https URL without credentials (http is allowed for localhost), at most 2,048 characters.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub return_url: Option<String>,
}

impl CreateSetupIntentsRequestBodyConfirmationToken {
    pub fn builder() -> CreateSetupIntentsRequestBodyConfirmationTokenBuilder {
        <CreateSetupIntentsRequestBodyConfirmationTokenBuilder as Default>::default()
    }
}

#[derive(Clone, PartialEq, Default, Debug)]
#[non_exhaustive]
pub struct CreateSetupIntentsRequestBodyConfirmationTokenBuilder {
    account_id: Option<String>,
    confirmation_token: Option<String>,
    currency: Option<Currencies>,
    email: Option<String>,
    metadata: Option<HashMap<String, serde_json::Value>>,
    return_url: Option<String>,
}

impl CreateSetupIntentsRequestBodyConfirmationTokenBuilder {
    pub fn account_id(mut self, value: impl Into<String>) -> Self {
        self.account_id = Some(value.into());
        self
    }

    pub fn confirmation_token(mut self, value: impl Into<String>) -> Self {
        self.confirmation_token = Some(value.into());
        self
    }

    pub fn currency(mut self, value: Currencies) -> Self {
        self.currency = Some(value);
        self
    }

    pub fn email(mut self, value: impl Into<String>) -> Self {
        self.email = Some(value.into());
        self
    }

    pub fn metadata(mut self, value: HashMap<String, serde_json::Value>) -> Self {
        self.metadata = Some(value);
        self
    }

    pub fn return_url(mut self, value: impl Into<String>) -> Self {
        self.return_url = Some(value.into());
        self
    }

    /// Consumes the builder and constructs a [`CreateSetupIntentsRequestBodyConfirmationToken`].
    /// This method will fail if any of the following fields are not set:
    /// - [`account_id`](CreateSetupIntentsRequestBodyConfirmationTokenBuilder::account_id)
    /// - [`confirmation_token`](CreateSetupIntentsRequestBodyConfirmationTokenBuilder::confirmation_token)
    pub fn build(self) -> Result<CreateSetupIntentsRequestBodyConfirmationToken, BuildError> {
        Ok(CreateSetupIntentsRequestBodyConfirmationToken {
            account_id: self
                .account_id
                .ok_or_else(|| BuildError::missing_field("account_id"))?,
            confirmation_token: self
                .confirmation_token
                .ok_or_else(|| BuildError::missing_field("confirmation_token"))?,
            currency: self.currency,
            email: self.email,
            metadata: self.metadata,
            return_url: self.return_url,
        })
    }
}
