pub use crate::prelude::*;

/// Autogenerated input type of CreateSetupIntent
#[derive(Debug, Clone, Serialize, Deserialize, Default, PartialEq)]
pub struct CreateSetupIntentsRequestPaymentMethodId {
    /// The ID of the company to save the payment method for.
    #[serde(default)]
    pub company_id: String,
    /// The currency the saved payment method will be used with. Controls which currency-specific payment methods are available. Defaults to usd.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub currency: Option<Currencies>,
    /// Overrides the buyer email carried on the confirmation token, resolving or creating the Whop user the method belongs to. Ignored when the caller IS the buyer or the confirmation token was created by a signed-in buyer, and unless confirmation_token is provided.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// Custom metadata to attach to the setup intent.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<HashMap<String, serde_json::Value>>,
    /// An existing payment method (payt_) to re-verify and save. Provide this or confirmation_token, not both.
    #[serde(default)]
    pub payment_method_id: String,
    /// Where the buyer continues after completing an off-site step. Must be an absolute https URL without credentials (http is allowed for localhost), at most 2,048 characters.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub return_url: Option<String>,
}

impl CreateSetupIntentsRequestPaymentMethodId {
    pub fn builder() -> CreateSetupIntentsRequestPaymentMethodIdBuilder {
        <CreateSetupIntentsRequestPaymentMethodIdBuilder as Default>::default()
    }
}

#[derive(Clone, PartialEq, Default, Debug)]
#[non_exhaustive]
pub struct CreateSetupIntentsRequestPaymentMethodIdBuilder {
    company_id: Option<String>,
    currency: Option<Currencies>,
    email: Option<String>,
    metadata: Option<HashMap<String, serde_json::Value>>,
    payment_method_id: Option<String>,
    return_url: Option<String>,
}

impl CreateSetupIntentsRequestPaymentMethodIdBuilder {
    pub fn company_id(mut self, value: impl Into<String>) -> Self {
        self.company_id = Some(value.into());
        self
    }

    pub fn currency(mut self, value: Currencies) -> Self {
        self.currency = Some(value);
        self
    }

    pub fn email(mut self, value: impl Into<String>) -> Self {
        self.email = Some(value.into());
        self
    }

    pub fn metadata(mut self, value: HashMap<String, serde_json::Value>) -> Self {
        self.metadata = Some(value);
        self
    }

    pub fn payment_method_id(mut self, value: impl Into<String>) -> Self {
        self.payment_method_id = Some(value.into());
        self
    }

    pub fn return_url(mut self, value: impl Into<String>) -> Self {
        self.return_url = Some(value.into());
        self
    }

    /// Consumes the builder and constructs a [`CreateSetupIntentsRequestPaymentMethodId`].
    /// This method will fail if any of the following fields are not set:
    /// - [`company_id`](CreateSetupIntentsRequestPaymentMethodIdBuilder::company_id)
    /// - [`payment_method_id`](CreateSetupIntentsRequestPaymentMethodIdBuilder::payment_method_id)
    pub fn build(self) -> Result<CreateSetupIntentsRequestPaymentMethodId, BuildError> {
        Ok(CreateSetupIntentsRequestPaymentMethodId {
            company_id: self
                .company_id
                .ok_or_else(|| BuildError::missing_field("company_id"))?,
            currency: self.currency,
            email: self.email,
            metadata: self.metadata,
            payment_method_id: self
                .payment_method_id
                .ok_or_else(|| BuildError::missing_field("payment_method_id"))?,
            return_url: self.return_url,
        })
    }
}
