pub use crate::prelude::*;

/// The post's call-to-action button, for example shop_now (Facebook only; null for Instagram and TikTok).
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum SocialAccountPostCallToAction {
    LearnMore,
    ShopNow,
    SignUp,
    Subscribe,
    GetStarted,
    BookNow,
    ApplyNow,
    ContactUs,
    Download,
    OrderNow,
    BuyNow,
    GetQuote,
    MessagePage,
    WhatsappMessage,
    InstagramMessage,
    CallNow,
    GetDirections,
    SendUpdates,
    GetOffer,
    WatchMore,
    ListenNow,
    PlayGame,
    OpenLink,
    NoButton,
    GetOfferView,
    GetEventTickets,
    SeeMenu,
    RequestTime,
    EventRsvp,
    SeeDetails,
    ViewInstagramProfile,
    /// This variant is used for forward compatibility.
    /// If the server sends a value not recognized by the current SDK version,
    /// it will be captured here with the raw string value.
    __Unknown(String),
}
impl Serialize for SocialAccountPostCallToAction {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        match self {
            Self::LearnMore => serializer.serialize_str("learn_more"),
            Self::ShopNow => serializer.serialize_str("shop_now"),
            Self::SignUp => serializer.serialize_str("sign_up"),
            Self::Subscribe => serializer.serialize_str("subscribe"),
            Self::GetStarted => serializer.serialize_str("get_started"),
            Self::BookNow => serializer.serialize_str("book_now"),
            Self::ApplyNow => serializer.serialize_str("apply_now"),
            Self::ContactUs => serializer.serialize_str("contact_us"),
            Self::Download => serializer.serialize_str("download"),
            Self::OrderNow => serializer.serialize_str("order_now"),
            Self::BuyNow => serializer.serialize_str("buy_now"),
            Self::GetQuote => serializer.serialize_str("get_quote"),
            Self::MessagePage => serializer.serialize_str("message_page"),
            Self::WhatsappMessage => serializer.serialize_str("whatsapp_message"),
            Self::InstagramMessage => serializer.serialize_str("instagram_message"),
            Self::CallNow => serializer.serialize_str("call_now"),
            Self::GetDirections => serializer.serialize_str("get_directions"),
            Self::SendUpdates => serializer.serialize_str("send_updates"),
            Self::GetOffer => serializer.serialize_str("get_offer"),
            Self::WatchMore => serializer.serialize_str("watch_more"),
            Self::ListenNow => serializer.serialize_str("listen_now"),
            Self::PlayGame => serializer.serialize_str("play_game"),
            Self::OpenLink => serializer.serialize_str("open_link"),
            Self::NoButton => serializer.serialize_str("no_button"),
            Self::GetOfferView => serializer.serialize_str("get_offer_view"),
            Self::GetEventTickets => serializer.serialize_str("get_event_tickets"),
            Self::SeeMenu => serializer.serialize_str("see_menu"),
            Self::RequestTime => serializer.serialize_str("request_time"),
            Self::EventRsvp => serializer.serialize_str("event_rsvp"),
            Self::SeeDetails => serializer.serialize_str("see_details"),
            Self::ViewInstagramProfile => serializer.serialize_str("view_instagram_profile"),
            Self::__Unknown(val) => serializer.serialize_str(val),
        }
    }
}

impl<'de> Deserialize<'de> for SocialAccountPostCallToAction {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        match value.as_str() {
            "learn_more" => Ok(Self::LearnMore),
            "shop_now" => Ok(Self::ShopNow),
            "sign_up" => Ok(Self::SignUp),
            "subscribe" => Ok(Self::Subscribe),
            "get_started" => Ok(Self::GetStarted),
            "book_now" => Ok(Self::BookNow),
            "apply_now" => Ok(Self::ApplyNow),
            "contact_us" => Ok(Self::ContactUs),
            "download" => Ok(Self::Download),
            "order_now" => Ok(Self::OrderNow),
            "buy_now" => Ok(Self::BuyNow),
            "get_quote" => Ok(Self::GetQuote),
            "message_page" => Ok(Self::MessagePage),
            "whatsapp_message" => Ok(Self::WhatsappMessage),
            "instagram_message" => Ok(Self::InstagramMessage),
            "call_now" => Ok(Self::CallNow),
            "get_directions" => Ok(Self::GetDirections),
            "send_updates" => Ok(Self::SendUpdates),
            "get_offer" => Ok(Self::GetOffer),
            "watch_more" => Ok(Self::WatchMore),
            "listen_now" => Ok(Self::ListenNow),
            "play_game" => Ok(Self::PlayGame),
            "open_link" => Ok(Self::OpenLink),
            "no_button" => Ok(Self::NoButton),
            "get_offer_view" => Ok(Self::GetOfferView),
            "get_event_tickets" => Ok(Self::GetEventTickets),
            "see_menu" => Ok(Self::SeeMenu),
            "request_time" => Ok(Self::RequestTime),
            "event_rsvp" => Ok(Self::EventRsvp),
            "see_details" => Ok(Self::SeeDetails),
            "view_instagram_profile" => Ok(Self::ViewInstagramProfile),
            _ => Ok(Self::__Unknown(value)),
        }
    }
}

impl fmt::Display for SocialAccountPostCallToAction {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::LearnMore => write!(f, "learn_more"),
            Self::ShopNow => write!(f, "shop_now"),
            Self::SignUp => write!(f, "sign_up"),
            Self::Subscribe => write!(f, "subscribe"),
            Self::GetStarted => write!(f, "get_started"),
            Self::BookNow => write!(f, "book_now"),
            Self::ApplyNow => write!(f, "apply_now"),
            Self::ContactUs => write!(f, "contact_us"),
            Self::Download => write!(f, "download"),
            Self::OrderNow => write!(f, "order_now"),
            Self::BuyNow => write!(f, "buy_now"),
            Self::GetQuote => write!(f, "get_quote"),
            Self::MessagePage => write!(f, "message_page"),
            Self::WhatsappMessage => write!(f, "whatsapp_message"),
            Self::InstagramMessage => write!(f, "instagram_message"),
            Self::CallNow => write!(f, "call_now"),
            Self::GetDirections => write!(f, "get_directions"),
            Self::SendUpdates => write!(f, "send_updates"),
            Self::GetOffer => write!(f, "get_offer"),
            Self::WatchMore => write!(f, "watch_more"),
            Self::ListenNow => write!(f, "listen_now"),
            Self::PlayGame => write!(f, "play_game"),
            Self::OpenLink => write!(f, "open_link"),
            Self::NoButton => write!(f, "no_button"),
            Self::GetOfferView => write!(f, "get_offer_view"),
            Self::GetEventTickets => write!(f, "get_event_tickets"),
            Self::SeeMenu => write!(f, "see_menu"),
            Self::RequestTime => write!(f, "request_time"),
            Self::EventRsvp => write!(f, "event_rsvp"),
            Self::SeeDetails => write!(f, "see_details"),
            Self::ViewInstagramProfile => write!(f, "view_instagram_profile"),
            Self::__Unknown(val) => write!(f, "{}", val),
        }
    }
}
