pub use crate::prelude::*;

/// The type of tax identifier
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum TaxIdentifierTypes {
    AdNrt,
    AoTin,
    ArCuit,
    AlTin,
    AmTin,
    AwTin,
    AuAbn,
    AuArn,
    EuVat,
    AzTin,
    BsTin,
    BhVat,
    BdBin,
    BbTin,
    ByTin,
    BjIfu,
    BoTin,
    BaTin,
    BrCnpj,
    BrCpf,
    BgUic,
    BfIfu,
    KhTin,
    CmNiu,
    CaBn,
    CaGstHst,
    CaPstBc,
    CaPstMb,
    CaPstSk,
    CaQst,
    CvNif,
    ClTin,
    CnTin,
    CoNit,
    CdNif,
    CrTin,
    HrOib,
    DoRcn,
    EcRuc,
    EgTin,
    SvNit,
    EtTin,
    EuOssVat,
    GeVat,
    GhTin,
    DeStn,
    GbVat,
    GnNif,
    HkBr,
    HuTin,
    IsVat,
    InGst,
    IdNpwp,
    IlVat,
    JpCn,
    JpRn,
    JpTrn,
    KzBin,
    KePin,
    KgTin,
    LaTin,
    LiUid,
    LiVat,
    MyFrp,
    MyItn,
    MySst,
    MrNif,
    MxRfc,
    MdVat,
    MePib,
    MaVat,
    NpPan,
    NzGst,
    NgTin,
    MkVat,
    NoVat,
    NoVoec,
    OmVat,
    PeRuc,
    PhTin,
    PlNip,
    RoTin,
    RuInn,
    RuKpp,
    SaVat,
    SnNinea,
    RsPib,
    SgGst,
    SgUen,
    SiTin,
    ZaVat,
    KrBrn,
    EsCif,
    ChUid,
    ChVat,
    TwVat,
    TjTin,
    TzVat,
    ThVat,
    TrTin,
    UgTin,
    UaVat,
    AeTrn,
    UsEin,
    UyRuc,
    UzTin,
    UzVat,
    VeRif,
    VnTin,
    ZmTin,
    ZwTin,
    SrFin,
    XiVat,
    /// This variant is used for forward compatibility.
    /// If the server sends a value not recognized by the current SDK version,
    /// it will be captured here with the raw string value.
    __Unknown(String),
}
impl Serialize for TaxIdentifierTypes {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        match self {
            Self::AdNrt => serializer.serialize_str("ad_nrt"),
            Self::AoTin => serializer.serialize_str("ao_tin"),
            Self::ArCuit => serializer.serialize_str("ar_cuit"),
            Self::AlTin => serializer.serialize_str("al_tin"),
            Self::AmTin => serializer.serialize_str("am_tin"),
            Self::AwTin => serializer.serialize_str("aw_tin"),
            Self::AuAbn => serializer.serialize_str("au_abn"),
            Self::AuArn => serializer.serialize_str("au_arn"),
            Self::EuVat => serializer.serialize_str("eu_vat"),
            Self::AzTin => serializer.serialize_str("az_tin"),
            Self::BsTin => serializer.serialize_str("bs_tin"),
            Self::BhVat => serializer.serialize_str("bh_vat"),
            Self::BdBin => serializer.serialize_str("bd_bin"),
            Self::BbTin => serializer.serialize_str("bb_tin"),
            Self::ByTin => serializer.serialize_str("by_tin"),
            Self::BjIfu => serializer.serialize_str("bj_ifu"),
            Self::BoTin => serializer.serialize_str("bo_tin"),
            Self::BaTin => serializer.serialize_str("ba_tin"),
            Self::BrCnpj => serializer.serialize_str("br_cnpj"),
            Self::BrCpf => serializer.serialize_str("br_cpf"),
            Self::BgUic => serializer.serialize_str("bg_uic"),
            Self::BfIfu => serializer.serialize_str("bf_ifu"),
            Self::KhTin => serializer.serialize_str("kh_tin"),
            Self::CmNiu => serializer.serialize_str("cm_niu"),
            Self::CaBn => serializer.serialize_str("ca_bn"),
            Self::CaGstHst => serializer.serialize_str("ca_gst_hst"),
            Self::CaPstBc => serializer.serialize_str("ca_pst_bc"),
            Self::CaPstMb => serializer.serialize_str("ca_pst_mb"),
            Self::CaPstSk => serializer.serialize_str("ca_pst_sk"),
            Self::CaQst => serializer.serialize_str("ca_qst"),
            Self::CvNif => serializer.serialize_str("cv_nif"),
            Self::ClTin => serializer.serialize_str("cl_tin"),
            Self::CnTin => serializer.serialize_str("cn_tin"),
            Self::CoNit => serializer.serialize_str("co_nit"),
            Self::CdNif => serializer.serialize_str("cd_nif"),
            Self::CrTin => serializer.serialize_str("cr_tin"),
            Self::HrOib => serializer.serialize_str("hr_oib"),
            Self::DoRcn => serializer.serialize_str("do_rcn"),
            Self::EcRuc => serializer.serialize_str("ec_ruc"),
            Self::EgTin => serializer.serialize_str("eg_tin"),
            Self::SvNit => serializer.serialize_str("sv_nit"),
            Self::EtTin => serializer.serialize_str("et_tin"),
            Self::EuOssVat => serializer.serialize_str("eu_oss_vat"),
            Self::GeVat => serializer.serialize_str("ge_vat"),
            Self::GhTin => serializer.serialize_str("gh_tin"),
            Self::DeStn => serializer.serialize_str("de_stn"),
            Self::GbVat => serializer.serialize_str("gb_vat"),
            Self::GnNif => serializer.serialize_str("gn_nif"),
            Self::HkBr => serializer.serialize_str("hk_br"),
            Self::HuTin => serializer.serialize_str("hu_tin"),
            Self::IsVat => serializer.serialize_str("is_vat"),
            Self::InGst => serializer.serialize_str("in_gst"),
            Self::IdNpwp => serializer.serialize_str("id_npwp"),
            Self::IlVat => serializer.serialize_str("il_vat"),
            Self::JpCn => serializer.serialize_str("jp_cn"),
            Self::JpRn => serializer.serialize_str("jp_rn"),
            Self::JpTrn => serializer.serialize_str("jp_trn"),
            Self::KzBin => serializer.serialize_str("kz_bin"),
            Self::KePin => serializer.serialize_str("ke_pin"),
            Self::KgTin => serializer.serialize_str("kg_tin"),
            Self::LaTin => serializer.serialize_str("la_tin"),
            Self::LiUid => serializer.serialize_str("li_uid"),
            Self::LiVat => serializer.serialize_str("li_vat"),
            Self::MyFrp => serializer.serialize_str("my_frp"),
            Self::MyItn => serializer.serialize_str("my_itn"),
            Self::MySst => serializer.serialize_str("my_sst"),
            Self::MrNif => serializer.serialize_str("mr_nif"),
            Self::MxRfc => serializer.serialize_str("mx_rfc"),
            Self::MdVat => serializer.serialize_str("md_vat"),
            Self::MePib => serializer.serialize_str("me_pib"),
            Self::MaVat => serializer.serialize_str("ma_vat"),
            Self::NpPan => serializer.serialize_str("np_pan"),
            Self::NzGst => serializer.serialize_str("nz_gst"),
            Self::NgTin => serializer.serialize_str("ng_tin"),
            Self::MkVat => serializer.serialize_str("mk_vat"),
            Self::NoVat => serializer.serialize_str("no_vat"),
            Self::NoVoec => serializer.serialize_str("no_voec"),
            Self::OmVat => serializer.serialize_str("om_vat"),
            Self::PeRuc => serializer.serialize_str("pe_ruc"),
            Self::PhTin => serializer.serialize_str("ph_tin"),
            Self::PlNip => serializer.serialize_str("pl_nip"),
            Self::RoTin => serializer.serialize_str("ro_tin"),
            Self::RuInn => serializer.serialize_str("ru_inn"),
            Self::RuKpp => serializer.serialize_str("ru_kpp"),
            Self::SaVat => serializer.serialize_str("sa_vat"),
            Self::SnNinea => serializer.serialize_str("sn_ninea"),
            Self::RsPib => serializer.serialize_str("rs_pib"),
            Self::SgGst => serializer.serialize_str("sg_gst"),
            Self::SgUen => serializer.serialize_str("sg_uen"),
            Self::SiTin => serializer.serialize_str("si_tin"),
            Self::ZaVat => serializer.serialize_str("za_vat"),
            Self::KrBrn => serializer.serialize_str("kr_brn"),
            Self::EsCif => serializer.serialize_str("es_cif"),
            Self::ChUid => serializer.serialize_str("ch_uid"),
            Self::ChVat => serializer.serialize_str("ch_vat"),
            Self::TwVat => serializer.serialize_str("tw_vat"),
            Self::TjTin => serializer.serialize_str("tj_tin"),
            Self::TzVat => serializer.serialize_str("tz_vat"),
            Self::ThVat => serializer.serialize_str("th_vat"),
            Self::TrTin => serializer.serialize_str("tr_tin"),
            Self::UgTin => serializer.serialize_str("ug_tin"),
            Self::UaVat => serializer.serialize_str("ua_vat"),
            Self::AeTrn => serializer.serialize_str("ae_trn"),
            Self::UsEin => serializer.serialize_str("us_ein"),
            Self::UyRuc => serializer.serialize_str("uy_ruc"),
            Self::UzTin => serializer.serialize_str("uz_tin"),
            Self::UzVat => serializer.serialize_str("uz_vat"),
            Self::VeRif => serializer.serialize_str("ve_rif"),
            Self::VnTin => serializer.serialize_str("vn_tin"),
            Self::ZmTin => serializer.serialize_str("zm_tin"),
            Self::ZwTin => serializer.serialize_str("zw_tin"),
            Self::SrFin => serializer.serialize_str("sr_fin"),
            Self::XiVat => serializer.serialize_str("xi_vat"),
            Self::__Unknown(val) => serializer.serialize_str(val),
        }
    }
}

impl<'de> Deserialize<'de> for TaxIdentifierTypes {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        match value.as_str() {
            "ad_nrt" => Ok(Self::AdNrt),
            "ao_tin" => Ok(Self::AoTin),
            "ar_cuit" => Ok(Self::ArCuit),
            "al_tin" => Ok(Self::AlTin),
            "am_tin" => Ok(Self::AmTin),
            "aw_tin" => Ok(Self::AwTin),
            "au_abn" => Ok(Self::AuAbn),
            "au_arn" => Ok(Self::AuArn),
            "eu_vat" => Ok(Self::EuVat),
            "az_tin" => Ok(Self::AzTin),
            "bs_tin" => Ok(Self::BsTin),
            "bh_vat" => Ok(Self::BhVat),
            "bd_bin" => Ok(Self::BdBin),
            "bb_tin" => Ok(Self::BbTin),
            "by_tin" => Ok(Self::ByTin),
            "bj_ifu" => Ok(Self::BjIfu),
            "bo_tin" => Ok(Self::BoTin),
            "ba_tin" => Ok(Self::BaTin),
            "br_cnpj" => Ok(Self::BrCnpj),
            "br_cpf" => Ok(Self::BrCpf),
            "bg_uic" => Ok(Self::BgUic),
            "bf_ifu" => Ok(Self::BfIfu),
            "kh_tin" => Ok(Self::KhTin),
            "cm_niu" => Ok(Self::CmNiu),
            "ca_bn" => Ok(Self::CaBn),
            "ca_gst_hst" => Ok(Self::CaGstHst),
            "ca_pst_bc" => Ok(Self::CaPstBc),
            "ca_pst_mb" => Ok(Self::CaPstMb),
            "ca_pst_sk" => Ok(Self::CaPstSk),
            "ca_qst" => Ok(Self::CaQst),
            "cv_nif" => Ok(Self::CvNif),
            "cl_tin" => Ok(Self::ClTin),
            "cn_tin" => Ok(Self::CnTin),
            "co_nit" => Ok(Self::CoNit),
            "cd_nif" => Ok(Self::CdNif),
            "cr_tin" => Ok(Self::CrTin),
            "hr_oib" => Ok(Self::HrOib),
            "do_rcn" => Ok(Self::DoRcn),
            "ec_ruc" => Ok(Self::EcRuc),
            "eg_tin" => Ok(Self::EgTin),
            "sv_nit" => Ok(Self::SvNit),
            "et_tin" => Ok(Self::EtTin),
            "eu_oss_vat" => Ok(Self::EuOssVat),
            "ge_vat" => Ok(Self::GeVat),
            "gh_tin" => Ok(Self::GhTin),
            "de_stn" => Ok(Self::DeStn),
            "gb_vat" => Ok(Self::GbVat),
            "gn_nif" => Ok(Self::GnNif),
            "hk_br" => Ok(Self::HkBr),
            "hu_tin" => Ok(Self::HuTin),
            "is_vat" => Ok(Self::IsVat),
            "in_gst" => Ok(Self::InGst),
            "id_npwp" => Ok(Self::IdNpwp),
            "il_vat" => Ok(Self::IlVat),
            "jp_cn" => Ok(Self::JpCn),
            "jp_rn" => Ok(Self::JpRn),
            "jp_trn" => Ok(Self::JpTrn),
            "kz_bin" => Ok(Self::KzBin),
            "ke_pin" => Ok(Self::KePin),
            "kg_tin" => Ok(Self::KgTin),
            "la_tin" => Ok(Self::LaTin),
            "li_uid" => Ok(Self::LiUid),
            "li_vat" => Ok(Self::LiVat),
            "my_frp" => Ok(Self::MyFrp),
            "my_itn" => Ok(Self::MyItn),
            "my_sst" => Ok(Self::MySst),
            "mr_nif" => Ok(Self::MrNif),
            "mx_rfc" => Ok(Self::MxRfc),
            "md_vat" => Ok(Self::MdVat),
            "me_pib" => Ok(Self::MePib),
            "ma_vat" => Ok(Self::MaVat),
            "np_pan" => Ok(Self::NpPan),
            "nz_gst" => Ok(Self::NzGst),
            "ng_tin" => Ok(Self::NgTin),
            "mk_vat" => Ok(Self::MkVat),
            "no_vat" => Ok(Self::NoVat),
            "no_voec" => Ok(Self::NoVoec),
            "om_vat" => Ok(Self::OmVat),
            "pe_ruc" => Ok(Self::PeRuc),
            "ph_tin" => Ok(Self::PhTin),
            "pl_nip" => Ok(Self::PlNip),
            "ro_tin" => Ok(Self::RoTin),
            "ru_inn" => Ok(Self::RuInn),
            "ru_kpp" => Ok(Self::RuKpp),
            "sa_vat" => Ok(Self::SaVat),
            "sn_ninea" => Ok(Self::SnNinea),
            "rs_pib" => Ok(Self::RsPib),
            "sg_gst" => Ok(Self::SgGst),
            "sg_uen" => Ok(Self::SgUen),
            "si_tin" => Ok(Self::SiTin),
            "za_vat" => Ok(Self::ZaVat),
            "kr_brn" => Ok(Self::KrBrn),
            "es_cif" => Ok(Self::EsCif),
            "ch_uid" => Ok(Self::ChUid),
            "ch_vat" => Ok(Self::ChVat),
            "tw_vat" => Ok(Self::TwVat),
            "tj_tin" => Ok(Self::TjTin),
            "tz_vat" => Ok(Self::TzVat),
            "th_vat" => Ok(Self::ThVat),
            "tr_tin" => Ok(Self::TrTin),
            "ug_tin" => Ok(Self::UgTin),
            "ua_vat" => Ok(Self::UaVat),
            "ae_trn" => Ok(Self::AeTrn),
            "us_ein" => Ok(Self::UsEin),
            "uy_ruc" => Ok(Self::UyRuc),
            "uz_tin" => Ok(Self::UzTin),
            "uz_vat" => Ok(Self::UzVat),
            "ve_rif" => Ok(Self::VeRif),
            "vn_tin" => Ok(Self::VnTin),
            "zm_tin" => Ok(Self::ZmTin),
            "zw_tin" => Ok(Self::ZwTin),
            "sr_fin" => Ok(Self::SrFin),
            "xi_vat" => Ok(Self::XiVat),
            _ => Ok(Self::__Unknown(value)),
        }
    }
}

impl fmt::Display for TaxIdentifierTypes {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::AdNrt => write!(f, "ad_nrt"),
            Self::AoTin => write!(f, "ao_tin"),
            Self::ArCuit => write!(f, "ar_cuit"),
            Self::AlTin => write!(f, "al_tin"),
            Self::AmTin => write!(f, "am_tin"),
            Self::AwTin => write!(f, "aw_tin"),
            Self::AuAbn => write!(f, "au_abn"),
            Self::AuArn => write!(f, "au_arn"),
            Self::EuVat => write!(f, "eu_vat"),
            Self::AzTin => write!(f, "az_tin"),
            Self::BsTin => write!(f, "bs_tin"),
            Self::BhVat => write!(f, "bh_vat"),
            Self::BdBin => write!(f, "bd_bin"),
            Self::BbTin => write!(f, "bb_tin"),
            Self::ByTin => write!(f, "by_tin"),
            Self::BjIfu => write!(f, "bj_ifu"),
            Self::BoTin => write!(f, "bo_tin"),
            Self::BaTin => write!(f, "ba_tin"),
            Self::BrCnpj => write!(f, "br_cnpj"),
            Self::BrCpf => write!(f, "br_cpf"),
            Self::BgUic => write!(f, "bg_uic"),
            Self::BfIfu => write!(f, "bf_ifu"),
            Self::KhTin => write!(f, "kh_tin"),
            Self::CmNiu => write!(f, "cm_niu"),
            Self::CaBn => write!(f, "ca_bn"),
            Self::CaGstHst => write!(f, "ca_gst_hst"),
            Self::CaPstBc => write!(f, "ca_pst_bc"),
            Self::CaPstMb => write!(f, "ca_pst_mb"),
            Self::CaPstSk => write!(f, "ca_pst_sk"),
            Self::CaQst => write!(f, "ca_qst"),
            Self::CvNif => write!(f, "cv_nif"),
            Self::ClTin => write!(f, "cl_tin"),
            Self::CnTin => write!(f, "cn_tin"),
            Self::CoNit => write!(f, "co_nit"),
            Self::CdNif => write!(f, "cd_nif"),
            Self::CrTin => write!(f, "cr_tin"),
            Self::HrOib => write!(f, "hr_oib"),
            Self::DoRcn => write!(f, "do_rcn"),
            Self::EcRuc => write!(f, "ec_ruc"),
            Self::EgTin => write!(f, "eg_tin"),
            Self::SvNit => write!(f, "sv_nit"),
            Self::EtTin => write!(f, "et_tin"),
            Self::EuOssVat => write!(f, "eu_oss_vat"),
            Self::GeVat => write!(f, "ge_vat"),
            Self::GhTin => write!(f, "gh_tin"),
            Self::DeStn => write!(f, "de_stn"),
            Self::GbVat => write!(f, "gb_vat"),
            Self::GnNif => write!(f, "gn_nif"),
            Self::HkBr => write!(f, "hk_br"),
            Self::HuTin => write!(f, "hu_tin"),
            Self::IsVat => write!(f, "is_vat"),
            Self::InGst => write!(f, "in_gst"),
            Self::IdNpwp => write!(f, "id_npwp"),
            Self::IlVat => write!(f, "il_vat"),
            Self::JpCn => write!(f, "jp_cn"),
            Self::JpRn => write!(f, "jp_rn"),
            Self::JpTrn => write!(f, "jp_trn"),
            Self::KzBin => write!(f, "kz_bin"),
            Self::KePin => write!(f, "ke_pin"),
            Self::KgTin => write!(f, "kg_tin"),
            Self::LaTin => write!(f, "la_tin"),
            Self::LiUid => write!(f, "li_uid"),
            Self::LiVat => write!(f, "li_vat"),
            Self::MyFrp => write!(f, "my_frp"),
            Self::MyItn => write!(f, "my_itn"),
            Self::MySst => write!(f, "my_sst"),
            Self::MrNif => write!(f, "mr_nif"),
            Self::MxRfc => write!(f, "mx_rfc"),
            Self::MdVat => write!(f, "md_vat"),
            Self::MePib => write!(f, "me_pib"),
            Self::MaVat => write!(f, "ma_vat"),
            Self::NpPan => write!(f, "np_pan"),
            Self::NzGst => write!(f, "nz_gst"),
            Self::NgTin => write!(f, "ng_tin"),
            Self::MkVat => write!(f, "mk_vat"),
            Self::NoVat => write!(f, "no_vat"),
            Self::NoVoec => write!(f, "no_voec"),
            Self::OmVat => write!(f, "om_vat"),
            Self::PeRuc => write!(f, "pe_ruc"),
            Self::PhTin => write!(f, "ph_tin"),
            Self::PlNip => write!(f, "pl_nip"),
            Self::RoTin => write!(f, "ro_tin"),
            Self::RuInn => write!(f, "ru_inn"),
            Self::RuKpp => write!(f, "ru_kpp"),
            Self::SaVat => write!(f, "sa_vat"),
            Self::SnNinea => write!(f, "sn_ninea"),
            Self::RsPib => write!(f, "rs_pib"),
            Self::SgGst => write!(f, "sg_gst"),
            Self::SgUen => write!(f, "sg_uen"),
            Self::SiTin => write!(f, "si_tin"),
            Self::ZaVat => write!(f, "za_vat"),
            Self::KrBrn => write!(f, "kr_brn"),
            Self::EsCif => write!(f, "es_cif"),
            Self::ChUid => write!(f, "ch_uid"),
            Self::ChVat => write!(f, "ch_vat"),
            Self::TwVat => write!(f, "tw_vat"),
            Self::TjTin => write!(f, "tj_tin"),
            Self::TzVat => write!(f, "tz_vat"),
            Self::ThVat => write!(f, "th_vat"),
            Self::TrTin => write!(f, "tr_tin"),
            Self::UgTin => write!(f, "ug_tin"),
            Self::UaVat => write!(f, "ua_vat"),
            Self::AeTrn => write!(f, "ae_trn"),
            Self::UsEin => write!(f, "us_ein"),
            Self::UyRuc => write!(f, "uy_ruc"),
            Self::UzTin => write!(f, "uz_tin"),
            Self::UzVat => write!(f, "uz_vat"),
            Self::VeRif => write!(f, "ve_rif"),
            Self::VnTin => write!(f, "vn_tin"),
            Self::ZmTin => write!(f, "zm_tin"),
            Self::ZwTin => write!(f, "zw_tin"),
            Self::SrFin => write!(f, "sr_fin"),
            Self::XiVat => write!(f, "xi_vat"),
            Self::__Unknown(val) => write!(f, "{}", val),
        }
    }
}
